// Icons explain existing milestones. Viewing a badge never changes progress.
const investigationBadgeInfo={
 'Portfolio presenter':{meaning:'Recognises filing a version of your thesis for presentation.',condition:'File a thesis portfolio locally. Filing does not certify its historical claims.',art:'<path d="M13 8H32L38 14V33H13ZM30 8V16H38M19 21H31M19 27H27M8 38H42M17 38V43M33 38V43"/>'},
 'Source scout':{meaning:'Recognises beginning to check the sources behind a record.',condition:'Expand a relevant source in a story. Opening it does not establish that its passage supports a claim.',art:'<path d="M8 10H23V34H8ZM23 10H38V34H23M12 17H19M12 23H19"/><circle cx="34" cy="29" r="8"/><path d="M40 35L46 42"/>'},
 'Link examiner':{meaning:'Recognises inspecting the reasoning behind a recorded connection.',condition:'Open a relevant connection explanation in a story. The milestone recognises inspection, not proof of causation.',art:'<path d="M20 15L25 10Q31 4 37 10T37 22L31 28M28 33L23 38Q17 44 11 38T11 26L17 20M17 31L31 17"/>'},
 'Story explorer':{meaning:'Recognises investigating a guided story’s evidence trail.',condition:'Visit every scene, expand a relevant source, inspect a connection and complete the story’s required decisions.',art:'<circle cx="24" cy="24" r="17"/><path d="M30 17L27 27L17 31L20 21ZM24 3V7M24 41V45M3 24H7M41 24H45"/>'},
 'Evidence interpreter':{meaning:'Recognises working through the relief story’s evidence layers.',condition:'Complete all four evidence interpretations in the relief story. Household benefit remains a separate research question.',art:'<path d="M10 38L31 17M28 14L35 7L43 15L36 22M7 41L13 40L8 35M14 11H23M18 7V15M31 35H40M35 31V39"/>'},
 'Case builder':{meaning:'Recognises assembling a bounded guided case.',condition:'Earn one case file by selecting its supporting records, evidence limit and next research move.',art:'<path d="M9 13H20L24 18H40V39H9ZM12 8H30V18M17 28L22 33L33 23"/>'},
 '1816 Investigator':{meaning:'Recognises completing the guided evidence expedition.',condition:'Earn all three case files and both evidence challenges. This recognises completed activities, not a certified historical conclusion.',art:'<path d="M16 6H32V18Q32 29 24 31Q16 29 16 18ZM16 10H8V15Q8 23 17 23M32 10H40V15Q40 23 31 23M24 31V39M16 42H32M18 39H30"/>'},
 'Draft contributor':{meaning:'Recognises recording a sourced proposal for extending the corpus.',condition:'Save a sourced proposal in a story. It remains an unreviewed local draft; it is not published evidence.',art:'<path d="M12 8H30L36 14V40H12M29 8V16H36M18 22H28M18 29H25M30 34L40 24L44 28L34 38L28 40Z"/>'},
 'Claim challenger':{meaning:'Recognises testing a claim that goes beyond a sequence of events.',condition:'Complete the Claim challenge, unlocked after your first case file.',art:'<path d="M24 5L39 11V23Q39 34 24 42Q9 34 9 23V11ZM19 18Q19 12 24 12T29 18Q29 22 24 24V28M24 33V34"/>'},
 'Comparative investigator':{meaning:'Recognises comparing different kinds of evidence while respecting their limits.',condition:'Complete the cross-story comparison challenge, unlocked after all three case files.',art:'<path d="M24 8V40M12 40H36M8 14H40M12 14L5 28H19ZM36 14L29 28H43ZM5 28Q12 35 19 28M29 28Q36 35 43 28"/>'}
};
let selectedInvestigationBadge=null;
function badgeIcon(name){return `<svg viewBox="0 0 48 48" aria-hidden="true" focusable="false" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">${investigationBadgeInfo[name].art}</svg>`;}
function badgeExplanationHtml(name,earned){const info=investigationBadgeInfo[name];return info?`<h3>${escapeHtml(name)} <small>${earned?'Earned':'Not earned yet'}</small></h3><p>${escapeHtml(info.meaning)}</p><p><strong>${earned?'Earning condition':'To earn it'}:</strong> ${escapeHtml(info.condition)}</p>`:'<p>Point to a badge, focus it with your keyboard, or tap it to see its meaning and how to earn it.</p>';}
function badgePresentationHtml(badges){const selected=badges.find(([name])=>name===selectedInvestigationBadge);return `<div class="earned-badges" role="group" aria-label="Investigation badges">${badges.map(([name,earned])=>`<button type="button" class="badge-token ${earned?'earned':'locked'}" data-investigation-badge="${escapeAttr(name)}" data-badge-earned="${earned}" aria-label="${escapeAttr(name)} · ${earned?'Earned':'Not earned yet'}" aria-controls="badgeExplanation" title="${escapeAttr(name+' · '+(earned?'Earned':'Not earned yet')+' — '+investigationBadgeInfo[name].meaning+' '+investigationBadgeInfo[name].condition)}" ${selected?.[0]===name?'data-selected="true"':''}>${badgeIcon(name)}<span class="badge-state" aria-hidden="true">${earned?'✓':'<svg viewBox="0 0 16 16" fill="none" stroke="currentColor" stroke-width="1.5"><rect x="3" y="7" width="10" height="7" rx="1"/><path d="M5 7V4a3 3 0 016 0v3"/></svg>'}</span></button>`).join('')}</div><section id="badgeExplanation" class="badge-explanation" aria-label="Badge meaning and earning condition" aria-live="polite">${badgeExplanationHtml(selected?.[0],selected?.[1])}</section>`;}
function showInvestigationBadge(button){selectedInvestigationBadge=button.dataset.investigationBadge;const root=button.closest('.earned-badges');root.querySelectorAll('[data-investigation-badge]').forEach(b=>{if(b===button)b.dataset.selected='true';else delete b.dataset.selected;});document.getElementById('badgeExplanation').innerHTML=badgeExplanationHtml(selectedInvestigationBadge,button.dataset.badgeEarned==='true');}
for(const type of ['mouseover','focusin','click'])document.addEventListener(type,e=>{const button=e.target.closest('[data-investigation-badge]');if(button&&selectedInvestigationBadge!==button.dataset.investigationBadge)showInvestigationBadge(button);});
