const caseFileTasks={
 harvests:{conclusion:'Damaging weather and grain-price pressure are recorded in the Czech Lands, while Korean records report good rice harvests; the outcome cannot be generalized everywhere.',records:['WT-1816-0006','WT-1816-0045','WT-1816-0008'],required:['WT-1816-0006','WT-1816-0045'],limits:['Good aggregate harvest reports do not establish household access or absence of local hardship.','Good rice harvests prove no Korean household suffered.'],next:['Compare provincial crop calendars, tax records and household food access.','Assume the same weather and harvest outcome in every region.']},
 relief:{conclusion:'Public purchases and subsidized rye authorization document a response to food pressure; the recorded evidence does not establish household benefit.',records:['WT-1816-0035','WT-1816-0034','WT-1816-0033'],required:['WT-1816-0035','WT-1816-0034'],limits:['Authorization and grain arrival are not evidence of distribution to poorer households.','The decree proves relief reached every intended household.'],next:['Find dated distribution or sales ledgers with recipients, quantities and prices.','Treat authorization as proof of successful delivery.']},
 andes:{conclusion:'Workshops and military preparation contributed to the recorded Andean crossing; the later battle result needs its own causal explanation.',records:['WT-1816-0060','WT-1816-0030','WT-1816-0031'],required:['WT-1816-0060','WT-1816-0030'],limits:['A crossing followed by victory establishes sequence, not a complete cause of victory.','Victory proves all supplies arrived and preparation was the only cause.'],next:['Compare workshop accounts, provisioning lists, route journals and losses by column.','Use the battle result alone to reconstruct every delivery.']}
};
function filedCases(){return storyCatalog.filter(s=>storyProgress(s.id).caseFiled);}
function expeditionFinished(){return filedCases().length===storyCatalog.length&&['causation','comparison'].every(id=>investigationProgress.challenges.includes(id));}
function caseFileHtml(config){
 const p=storyProgress(config.id),task=caseFileTasks[config.id],ready=completedStory(config);
 if(!ready)return `<section class="case-goal"><h2>Your destination: a defensible case file</h2><p>Visit every scene, expand a relevant source and examine a connection${config.id==='relief'?', then solve all four evidence layers':''}. That unlocks the case-file desk.</p><button class="story-next" disabled>Case-file desk locked</button></section>`;
 if(p.caseFiled)return `<section class="case-victory"><p class="eyebrow">Case completed · 75 points earned once</p><h2>You built a defensible case.</h2><p>${escapeHtml(task.conclusion)}</p><p><strong>Still open:</strong> ${escapeHtml(config.question)}</p><div class="story-actions"><button class="story-next" data-thread-thesis="${config.thread}">Develop this thread into a thesis →</button><button class="story-back" data-download-case="${config.id}">Download your case file</button><button class="story-back" data-story-home>See the next expedition goal →</button></div><p>This completes the learning case. It does not close the historical research gap or certify independent source verification.</p></section>`;
 return `<section class="case-goal"><p class="eyebrow">Final task · earn a completed case and 75 points</p><h2>Build your case file.</h2><p>Success means supporting a bounded conclusion, recording a limit and choosing the next evidence to seek.</p><form id="caseFileForm"><fieldset><legend>1. Select the records that support this conclusion</legend><p>${escapeHtml(task.conclusion)}</p>${task.records.map(id=>`<label class="case-record-choice"><input type="checkbox" name="records" value="${id}"><span>${escapeHtml(obs(id).title)}<small>${escapeHtml(obs(id).place)} · ${escapeHtml(obs(id).startDate)}</small></span><button type="button" class="story-link" data-story-evidence="${id}">Inspect</button></label>`).join('')}</fieldset><label>2. What is the important limit?<select name="limit" required><option value="">Choose a limit</option>${task.limits.map((text,i)=>`<option value="${i}">${escapeHtml(text)}</option>`).join('')}</select></label><label>3. What evidence would you seek next?<select name="next" required><option value="">Choose the next research move</option>${task.next.map((text,i)=>`<option value="${i}">${escapeHtml(text)}</option>`).join('')}</select></label><button class="story-next" type="submit">Present my case</button></form><p id="caseFileFeedback" role="status"></p></section>`;
}
function submitCaseFile(e){if(e.target.id!=='caseFileForm')return;e.preventDefault();const config=storyCatalog.find(s=>s.id===story.id),task=caseFileTasks[story.id];if(!config||!completedStory(config))return;const form=new FormData(e.target),chosen=form.getAll('records'),feedback=document.getElementById('caseFileFeedback');
 if(!task.required.every(id=>chosen.includes(id))){feedback.textContent='Your case needs the paired records: choose evidence for both parts of the conclusion. Use Inspect to revisit the clues.';return;}
 if(form.get('limit')!=='0'||form.get('next')!=='0'){feedback.textContent='Reconsider the boundary of the evidence. What cannot these records establish, and what new source would test it? No points lost.';return;}
 recordProgress('caseFiled',true);renderStory();document.querySelector('.case-victory').setAttribute('tabindex','-1');document.querySelector('.case-victory').focus();
}
function downloadCaseFile(id){const config=storyCatalog.find(s=>s.id===id),task=caseFileTasks[id];if(!config||!storyProgress(id).caseFiled)return;
 const records=task.required.map(id=>obs(id)),refs=[...new Set(records.flatMap(o=>o.sourceRefs))].map(id=>source(id));
 const text=`# WorldThreads case file: ${config.title}\n\nStatus: completed learning case; open historical research remains.\n\n## Supported conclusion\n${task.conclusion}\n\n## Evidence\n${records.map(o=>`- ${o.title} (${o.id}): ${o.observation}`).join('\n')}\n\n## Limit\n${task.limits[0]}\n\n## Next evidence to seek\n${task.next[0]}\n\n## Open question\n${config.question}\n\n## Sources\n${refs.map(s=>`- ${s.title}: ${s.url}`).join('\n')}\n\nThis guided case-file exercise does not certify independent source verification.\n`;
 const url=URL.createObjectURL(new Blob([text],{type:'text/markdown'}));const a=document.createElement('a');a.href=url;a.download='worldthreads-'+id+'-case-file.md';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);
}
function expeditionHtml(){const cases=filedCases(),methods=investigationProgress.challenges.length,count=cases.length+methods;const next=cases.length===0?'Build your first case file to unlock the claim challenge.':cases.length<3?'Claim challenge unlocked. Build the remaining case files and test your evidence skills.':!investigationProgress.challenges.includes('causation')?'Complete the claim challenge.':!investigationProgress.challenges.includes('comparison')?'Complete the cross-story comparison.':'Expedition complete. Next: research a gap, test a rival explanation and present a thesis portfolio.';
 return `<section class="expedition-goal"><details><summary>${expeditionFinished()?'Expedition completed · explore what comes next':'Your expedition · goals and next steps'}</summary><div class="expedition-overview"><div><p class="eyebrow">Your goal · complete the 1816 evidence expedition</p><h2>${expeditionFinished()?'Expedition completed · 1816 Investigator earned':'Build 3 cases. Master 2 evidence challenges.'}</h2><p>${next}</p><p class="expedition-prize">${expeditionFinished()?'Earned: 1816 Investigator badge and 150 bonus points. Advanced cross-story research board unlocked.':'Earn the 1816 Investigator badge, 150 bonus points and unlock the advanced cross-story research board.'}</p></div><div class="expedition-meter"><strong>${count}/5 milestones</strong><progress value="${count}" max="5" aria-label="Expedition milestones">${count}/5</progress><small>Case files ${cases.length}/3 · Challenges ${methods}/2</small></div></div>${expeditionFinished()?'<div class="expedition-actions"><button class="story-next" data-open-thesis>Build your own thesis →</button></div>':''}<h3>What counts as success?</h3><p>A case is earned by investigating its evidence and assembling a supported conclusion, a limit and a next research move. Badges recognise skills; collecting every badge is optional. Draft contributions do not have to be made to finish the expedition. A separate research round ends when you file a thesis portfolio with evidence interpretations, an open research plan and a rival test. Neither finish certifies a historical conclusion.</p>${expeditionFinished()?`<p>Thesis workspace unlocked: turn your cases into an argument, evidence table and chapter plan.</p><p>Open-research board unlocked: pick a real gap and propose the evidence needed.</p><div class="gap-links">${storyCatalog.map(s=>`<button class="story-back" data-extend-case="${s.id}">Extend: ${escapeHtml(s.short)}</button>`).join('')}</div>`:''}</details></section>`;
}
function caseStagesHtml(config){const p=storyProgress(config.id),ready=completedStory(config);return `<div class="case-stages" role="group" aria-label="Investigation stages">${[['Discover',p.visited.length>0],['Investigate',ready],['Build the case',p.caseFiled],['Case earned',p.caseFiled]].map(([name,done],i)=>`<span class="${done?'done':''}" ${i===(p.caseFiled?3:ready?2:p.visited.length?1:0)?'aria-current="step"':''}>${done?'✓':i+1} ${name}</span>`).join('')}</div><p class="case-destination">${p.caseFiled?'Destination reached: a bounded case with a next research question.':ready?'Next goal: assemble the case file at the final scene.':'Destination: earn a case file by finding evidence, testing connections and defending a bounded conclusion.'}</p>`;}
