const examinerFields=[
 ['testRival','A rival explanation that could fit the observations'],
 ['testOwnPrediction','What would you expect to find if your explanation holds?'],
 ['testRivalPrediction','What different evidence would you expect under the rival explanation?'],
 ['testDiscriminator','Which source or comparison could distinguish those predictions?'],
 ['testReason','Why does the available evidence justify your decision?'],
 ['testRevisedArgument','Your revised statement (required to narrow or suspend)']
];
const examinerResults=[['pending','Evidence unavailable or not yet checked'],['own','Provisionally favors my explanation'],['rival','Provisionally favors the rival'],['neither','Does not distinguish the explanations']];
const examinerDecisions=[['retain','Retain provisionally'],['narrow','Narrow or revise'],['suspend','Suspend the conclusion']];
function examinerHtml(draft){const field=(key,label)=>`<label>${label}<textarea form="thesisForm" name="${key}" maxlength="4000">${escapeHtml(draft[key]||'')}</textarea></label>`;const options=(list,value)=>'<option value="">Choose your assessment</option>'+list.map(([id,label])=>`<option value="${id}" ${id===value?'selected':''}>${label}</option>`).join('');const records=[...new Set(Array.from({length:3},(_,i)=>draft['record'+i]).concat(draft.testRecord||[]).filter(Boolean))].map(thesisRecord).filter(Boolean);
 return `<details id="examinerRound" class="examiner-round"><summary>The examiner’s challenge · try to break your explanation</summary><p>Two explanations may fit the same facts. Predict what each would leave behind, identify a discriminating source, then decide what you can defend. This is a research exercise; no contrary historical fact is invented.</p><input type="hidden" form="thesisForm" name="testArgument" value="${escapeAttr(draft.testArgument??draft.argument??'')}"><p id="examinerFrame"></p><button type="button" class="story-link" data-reframe-examiner>Frame this test around my current argument</button><div class="examiner-steps"><span>1. Rival</span><span>2. Test</span><span>3. Revise</span></div>${examinerFields.slice(0,4).map(([key,label])=>field(key,label)).join('')}<label>Record used in this test (optional while evidence is missing)<select form="thesisForm" name="testRecord"><option value="">No selected record yet</option>${records.map(o=>`<option value="${o.id}" ${draft.testRecord===o.id?'selected':''}>${escapeHtml(o.title||'Unreviewed local candidate')}</option>`).join('')}</select></label><div id="examinerEvidence"></div><p>Choosing a record does not establish that it tests the rival. Verify its passage, provenance and fit to your predictions.</p><label>Your provisional assessment of the evidence<select form="thesisForm" name="testResult">${options(examinerResults,draft.testResult)}</select></label><label>What happens to your thesis?<select form="thesisForm" name="testDecision">${options(examinerDecisions,draft.testDecision)}</select></label>${examinerFields.slice(4).map(([key,label])=>field(key,label)).join('')}<button type="button" class="story-next" data-apply-examiner>Record my decision and update the argument</button><p id="examinerStatus" role="status">A pending test can lead to a narrower claim or suspended conclusion. Retaining an argument provisionally does not mean it passed.</p><div id="examinerHistory"></div></details>`;
}
function renderExaminerEvidence(draft){const select=document.querySelector('[name=testRecord]'),root=document.getElementById('examinerEvidence');if(!select||!root)return;const ids=[...new Set(Array.from({length:3},(_,i)=>draft['record'+i]).concat(draft.testRecord||[]).filter(Boolean))],records=ids.map(thesisRecord).filter(Boolean);if(select!==document.activeElement&&select.dataset.optionIds!==ids.join('|')){select.dataset.optionIds=ids.join('|');select.innerHTML='<option value="">No selected record yet</option>'+records.map(o=>`<option value="${escapeAttr(o.id)}" ${draft.testRecord===o.id?'selected':''}>${escapeHtml(o.title||'Unreviewed local candidate')}</option>`).join('');}const o=thesisRecord(draft.testRecord);if(root.dataset.recordId===(o?.id||'none'))return;root.dataset.recordId=o?.id||'none';root.innerHTML=o?`<p><strong>${o.reviewStatus?'Unreviewed candidate':'Recorded observation'}:</strong> ${escapeHtml(o.observation||o.claim)}</p><p>Limits: ${escapeHtml(o.uncertainty||o.limits||'Verify the passage and define the scope.')}</p>${o.reviewStatus?`<a href="${escapeAttr(o.url)}" target="_blank" rel="noreferrer">Inspect supplied source ↗</a>`:`<button type="button" class="story-link" data-story-evidence="${o.id}">Inspect the test record and sources ↗</button>`}`:'<p>No record linked. Keep the result pending until suitable evidence is available.</p>';}
function renderExaminerHistory(draft){renderExaminerEvidence(draft);const frame=document.getElementById('examinerFrame');if(frame){const argument=document.querySelector('[name=testArgument]').value;frame.textContent=argument===draft.argument?'Test framed around: '+(argument||'Write your argument first.'):'Argument changed. This test still concerns: '+(argument||'[No argument]')+'. Reframe it and review both predictions before recording another decision.';}const root=document.getElementById('examinerHistory');if(!root)return;const rounds=Array.isArray(draft.argumentRevisions)?draft.argumentRevisions:[],signature=JSON.stringify(rounds);if(root.dataset.signature===signature)return;root.dataset.signature=signature;root.innerHTML=`<details><summary>Argument history · ${rounds.length} ${rounds.length===1?'decision':'decisions'}</summary><p>These are your research decisions, not an examiner’s certification.</p>${rounds.map(round=>`<article class="examiner-history"><p><strong>${escapeHtml(round.decision)}</strong> · ${escapeHtml(examinerDate(round.at))}</p><p>Before: ${escapeHtml(round.before)}</p><p>After: ${escapeHtml(round.after)}</p><p>Reason: ${escapeHtml(round.reason)}</p><p>Assessment: ${escapeHtml(round.result)} · ${escapeHtml(round.recordId||'No record selected')}</p></article>`).join('')||'<p>No challenge decisions recorded yet.</p>'}</details>`;}
function applyExaminerDecision(){const form=document.getElementById('thesisForm'),status=document.getElementById('examinerStatus');if(!form||!status)return;const previous=readThesisDraft(),values={...previous,...Object.fromEntries(new FormData(form))};
 if(values.testArgument!==values.argument){status.textContent='Decision not recorded. Your argument changed. Reframe the test and review its predictions first.';return;}
 const missing=['argument','testRival','testOwnPrediction','testRivalPrediction','testDiscriminator','testReason'].some(key=>!String(values[key]||'').trim());const decision=examinerDecisions.find(([id])=>id===values.testDecision),result=examinerResults.find(([id])=>id===values.testResult);
 if(missing||!decision||!result){status.textContent='Decision not recorded. State your argument, rival, both predictions, the discriminating source, assessment, decision and reason first.';return;}
 const before=values.argument,after=values.testDecision==='retain'?before:String(values.testRevisedArgument||'').trim();
 if(!after||(values.testDecision!=='retain'&&after.trim()===before.trim())){status.textContent='Decision not recorded. Write a changed statement to narrow or suspend, or choose Retain provisionally if the argument stays the same.';return;}
 const record=thesisRecord(values.testRecord);if(values.testResult!=='pending'&&!record){status.textContent='Decision not recorded. Link a test record before assessing its result, or leave the assessment pending. Import outside evidence as a local candidate first.';return;}if(values.testRecord&&!record){status.textContent='Decision not recorded. The selected test record is unavailable; choose an available record or leave the test pending.';return;}
 const round={at:new Date().toISOString(),before,after,decision:decision[1],result:result[1],reason:values.testReason,rival:values.testRival,ownPrediction:values.testOwnPrediction,rivalPrediction:values.testRivalPrediction,discriminator:values.testDiscriminator,recordId:record?.id||null,recordSource:record?.url||record?.sourceRefs?.join(', ')||null,reviewStatus:'Unreviewed writer decision'};
 const revisions=Array.isArray(previous.argumentRevisions)?previous.argumentRevisions:[],last=revisions.at(-1);if(last&&['before','after','decision','result','reason','rival','ownPrediction','rivalPrediction','discriminator','recordId'].every(key=>last[key]===round[key])){status.textContent='This unchanged decision is already recorded. No duplicate added.';return;}
 values.argument=after;values.argumentDisposition=decision[1];values.argumentRevisions=[...revisions,round];values.savedAt=round.at;
 try{localStorage.setItem(THESIS_KEY,JSON.stringify(values));form.elements.argument.value=after;renderArgumentBoard(values);renderDefenseFeedback(values);renderExaminerHistory(values);renderPortfolio(values);document.querySelector('[data-download-thesis]').disabled=false;status.textContent='Decision saved locally. '+(before!==after?'The argument changed; reassess its earlier evidence assignments.':'The argument is retained provisionally; the research test remains your responsibility.');}catch{status.textContent='Browser storage is unavailable. The decision and argument were not updated.';}
}
function examinerExport(draft){const value=key=>String(draft[key]||'').trim()||'[Not yet drafted]';let text='## Examiner challenge and argument decisions\n\nStatus: unreviewed writer assessments, not independently evaluated conclusions.\n\n';text+=`Test framed around: ${value('testArgument')}\n\n${draft.testArgument!==draft.argument?'Argument changed; this test needs reframing before another decision.\n\n':''}`;for(const [key,label] of examinerFields.slice(0,4))text+=`${label}: ${value(key)}\n\n`;text+=`Assessment: ${examinerResults.find(([id])=>id===draft.testResult)?.[1]||'[Not selected]'}\n\n`;
 for(const round of Array.isArray(draft.argumentRevisions)?draft.argumentRevisions:[])text+=`### ${round.decision} · ${round.at}\n\nBefore: ${round.before}\n\nAfter: ${round.after}\n\nRival: ${round.rival}\n\nOwn prediction: ${round.ownPrediction}\n\nRival prediction: ${round.rivalPrediction}\n\nDiscriminating evidence: ${round.discriminator}\n\nRecord: ${round.recordId||'[None selected]'}\n\nSource reference as supplied: ${round.recordSource||'[None selected]'}\n\nAssessment: ${round.result}\n\nReason: ${round.reason}\n\n`;
 return text;
}
document.addEventListener('click',e=>{if(e.target.closest('[data-apply-examiner]'))applyExaminerDecision();if(e.target.closest('[data-reframe-examiner]')){const form=document.getElementById('thesisForm');form.elements.testArgument.value=form.elements.argument.value;for(const key of ['testResult','testDecision','testRevisedArgument'])form.elements[key].value='';saveThesisDraft({target:document.getElementById('thesisForm'),preventDefault(){}});document.getElementById('examinerStatus').textContent='Test reframed. Review the retained rival, predictions and research notes; choose a fresh assessment and decision. Earlier decisions remain in your history.';}});

function examinerDate(at){const date=new Date(at);return Number.isNaN(date.getTime())?String(at):new Intl.DateTimeFormat(undefined,{dateStyle:"medium",timeStyle:"short"}).format(date);}
