/* A guided route through the evidence, with a bounded neighbourhood graph. */
(function(){
 const $=id=>document.getElementById(id),node=(tag,text,cls)=>{const e=document.createElement(tag);if(text!==undefined)e.textContent=text;if(cls)e.className=cls;return e;};
 let selected=null,currentThread=null,trail=[],view='discover',initialized=false;
 function button(text,action,cls='nav-btn'){const b=node('button',text,cls);b.type='button';b.onclick=action;return b;}
 function show(next){view=next;for(const id of ['discover','explore','research'])$(id+'View').hidden=id!==next;document.querySelectorAll('.site-header [data-view]').forEach(b=>{b.classList.toggle('active',b.dataset.view===next);b.setAttribute('aria-current',b.dataset.view===next?'page':'false');});if(next==='research')$('researchContext').textContent='Starting from: '+(WorldThreadsApp.state.threads.find(t=>t.id===WorldThreadsApp.state.threadId)?.title||'1816');if(next!=='discover')$('evidenceLibrary').hidden=true;else $('evidenceLibrary').hidden=false;window.scrollTo({top:0,behavior:'smooth'});if(next==='explore')renderNetwork();}
 function tab(which){for(const [name,id] of [['prepare','prepareResearch'],['return','returnResearch'],['progress','progressResearch']])$(id).hidden=name!==which;document.querySelectorAll('[data-research-tab]').forEach(b=>b.classList.toggle('active',b.dataset.researchTab===which));}
 function showEvidence(){show('research');tab('return');$('evidenceDisclosure').open=true;}
 function chooseThread(t){WorldThreadsApp.state.threadId=t.id;selected=t.nodeIds[0];trail=[selected];currentThread=t.id;WorldThreadsApp.render();show('explore');}
 function selectFact(id){const s=WorldThreadsApp.state,current=s.threads.find(t=>t.id===s.threadId);if(!current?.nodeIds.includes(id)){const branch=s.threads.find(t=>t.nodeIds.includes(id)&&t.nodeIds.includes(selected))||s.threads.find(t=>t.nodeIds.includes(id));if(branch){s.threadId=branch.id;currentThread=branch.id;}else if($('connectionDepth').value==='0')$('connectionDepth').value='1';}selected=id;if(trail.at(-1)!==id)trail.push(id);WorldThreadsApp.render();renderNetwork();}
 function palette(o){return {EARTH:'#d99561',BIOSPHERE:'#65ad84','PRODUCTION & RESOURCES':'#c0a553','HUMAN SYSTEMS':'#739bcb','POWER & CULTURE':'#b48aca'}[o?.system]||'#8aa59a';}
 function gallery(){const root=$('threadGallery');root.replaceChildren();WorldThreadsApp.state.threads.forEach((t,i)=>{const card=button('',()=>chooseThread(t),'thread-entry');const graphic=node('div',undefined,'entry-graphic');const ns='http://www.w3.org/2000/svg',svg=document.createElementNS(ns,'svg');svg.setAttribute('viewBox','0 0 300 90');svg.setAttribute('aria-hidden','true');const ids=t.nodeIds.slice(0,6);ids.forEach((id,j)=>{const cx=30+j*240/Math.max(1,ids.length-1),cy=j%2?56:30;if(j){const line=document.createElementNS(ns,'path');line.setAttribute('d',`M ${30+(j-1)*240/Math.max(1,ids.length-1)} ${j%2?30:56} Q ${cx-20} 12 ${cx} ${cy}`);line.setAttribute('stroke','var(--border)');line.setAttribute('fill','none');svg.append(line);}const c=document.createElementNS(ns,'circle');c.setAttribute('cx',cx);c.setAttribute('cy',cy);c.setAttribute('r',j===0?10:7);c.setAttribute('fill',palette(WorldThreadsApp.obs(id)));svg.append(c);});graphic.append(svg);card.append(graphic,node('small',t.subtitle||t.scope||'1816'),node('h3',t.title),node('p',`${t.nodeIds.length} facts · ${(t.relationshipIds||[]).length} recorded connections`),node('span','Follow this thread →','entry-link'));root.append(card);});}
 function renderNetwork(){if(!initialized)return;const app=WorldThreadsApp,s=app.state,t=s.threads.find(t=>t.id===s.threadId);if(!t)return;if(currentThread!==t.id){currentThread=t.id;selected=t.nodeIds[0];trail=[selected];}if(!app.obs(selected))selected=t.nodeIds[0];$('exploreTitle').textContent=t.title;$('exploreDescription').textContent=t.description;const depth=Number($('connectionDepth').value),ids=new Set(depth?[selected]:t.nodeIds);let frontier=new Set(ids);for(let hop=0;hop<depth;hop++){const next=new Set();for(const r of s.relationships){if(frontier.has(r.subjectId))next.add(r.objectId);if(frontier.has(r.objectId))next.add(r.subjectId);}for(const id of next)ids.add(id);frontier=next;}
 const records=[...ids].map(id=>app.obs(id)).filter(Boolean),rels=s.relationships.filter(r=>ids.has(r.subjectId)&&ids.has(r.objectId)&&(depth||t.relationshipIds?.includes(r.id)));const canvas=$('networkCanvas');canvas.replaceChildren();const positions=new Map(),width=900,height=Math.max(480,Math.ceil(records.length/3)*160+60);canvas.style.minHeight=height+'px';const ns='http://www.w3.org/2000/svg',svg=document.createElementNS(ns,'svg');svg.setAttribute('viewBox',`0 0 ${width} ${height}`);svg.setAttribute('preserveAspectRatio','none');svg.setAttribute('aria-hidden','true');svg.classList.add('network-lines');canvas.append(svg);const defs=document.createElementNS(ns,'defs'),marker=document.createElementNS(ns,'marker');marker.id='network-direction';marker.setAttribute('viewBox','0 0 10 10');marker.setAttribute('refX','5');marker.setAttribute('refY','5');marker.setAttribute('markerWidth','8');marker.setAttribute('markerHeight','8');marker.setAttribute('orient','auto');const arrow=document.createElementNS(ns,'path');arrow.setAttribute('d','M 1 1 L 9 5 L 1 9 z');arrow.setAttribute('fill','var(--link)');marker.append(arrow);defs.append(marker);svg.append(defs);
 records.forEach((o,i)=>{const col=i%3,row=Math.floor(i/3);positions.set(o.id,{x:150+col*300,y:90+row*160});});for(const r of rels){const a=positions.get(r.subjectId),b=positions.get(r.objectId);const line=document.createElementNS(ns,'path');const mx=(a.x+b.x)/2,my=(a.y+b.y)/2+(a.y===b.y?70:0);line.setAttribute('d',`M ${a.x} ${a.y} Q ${a.x} ${my} ${mx} ${my} Q ${b.x} ${my} ${b.x} ${b.y}`);line.setAttribute('marker-mid','url(#network-direction)');line.setAttribute('fill','none');line.setAttribute('stroke','var(--link)');line.setAttribute('stroke-width',r.confidence==='High'?'3':'2');if(r.communityStatus==='provisional'||r.communityStatus==='disputed')line.setAttribute('stroke-dasharray','2 7');else if(['ASSOCIATED','CONTESTED'].includes(r.causalStatus))line.setAttribute('stroke-dasharray','8 6');svg.append(line);}
 for(const o of records){const p=positions.get(o.id),b=button('',()=>selectFact(o.id),'network-fact'+(o.id===selected?' selected':''));b.style.left=p.x/width*100+'%';b.style.top=p.y+'px';b.style.setProperty('--node-color',palette(o));b.setAttribute('aria-pressed',String(o.id===selected));b.append(node('small',o.place||o.system),node('strong',o.title));canvas.append(b);}reader(rels);
 }
 function reader(){const app=WorldThreadsApp,o=app.obs(selected),root=$('factReader');root.replaceChildren();if(!o)return;const crumbs=node('div',undefined,'journey-trail');crumbs.append(node('small','YOUR PATH'));trail.slice(-4).forEach((id,i)=>crumbs.append(button((i?'→ ':'')+(app.obs(id)?.title||id),()=>{selected=id;trail=trail.slice(0,trail.lastIndexOf(id)+1);renderNetwork();},'trail-link')));root.append(crumbs,node('p',o.system+' · '+o.startDate,'eyebrow'),node('h3',o.title),node('p',o.observation),node('p',o.place+' · '+(o.communityStatus?WorldThreadsCommunityUI?.statusLabel(o.communityStatus):o.confidence+' confidence'),'reader-meta'),button('Inspect sources & evidence',()=>openDetail(o)));
 const connections=app.state.relationships.filter(r=>r.subjectId===selected||r.objectId===selected);root.append(node('h4','Where does this lead?'));if(!connections.length)root.append(node('p','No connection has been recorded here yet. This is an open end to investigate.'));for(const r of connections){const id=r.subjectId===selected?r.objectId:r.subjectId,other=app.obs(id);if(!other)continue;const row=node('div',undefined,'next-connection');row.append(node('small',(r.subjectId===selected?'Leads toward':'Connects from')+' · '+r.causalStatus.toLowerCase().replaceAll('_',' ')+' · '+r.confidence),button(other.title+' →',()=>selectFact(id),'next-fact'),button('Why this connection?',()=>openRelationship(r),'trail-link'));root.append(row);}const research=node('div',undefined,'reader-research');research.append(node('h4','What would you explore next?'),node('p','Follow a consequence, test another cause, or investigate a place you know.'),button('Continue this thread ↗',()=>{show('research');tab('prepare');$('researchDirection').value='continue_thread';$('personalQuestion').value='What follows from '+o.title+' in 1816?';}),button('Explore another perspective',()=>{show('research');tab('prepare');$('researchDirection').value='new_thread';}));root.append(research);
 }
 function initialize(){if(initialized)return;initialized=true;const main=document.querySelector('main');$('originalThreadMount').append(document.querySelector('.thread-panel'));document.querySelector('.layout').remove();document.querySelector('.data-strip').remove();$('libraryMount').append(document.querySelector('.filters'),document.querySelector('.observations-panel'));const contribute=$('contribute'),prepare=node('section',undefined,'research-stage'),returned=node('section',undefined,'research-stage'),progress=node('section',undefined,'research-stage');prepare.id='prepareResearch';returned.id='returnResearch';progress.id='progressResearch';let returning=false;for(const child of [...contribute.children]){if(child.tagName==='H4'&&child.textContent==='Return your findings')returning=true;(returning?returned:prepare).append(child);}progress.append($('receiptPanel'));contribute.replaceChildren(prepare,returned,progress);const evidence=$('evidenceContribute'),details=node('details',undefined,'evidence-disclosure');details.id='evidenceDisclosure';details.append(node('summary','Have a source that supports or questions an existing claim?'),evidence);returned.append(details);const activity=$('communityActivity').closest('section');progress.append(activity);$('researchMount').append(contribute);const badgeTitle=[...prepare.querySelectorAll('h4')].find(x=>x.textContent==='Recognition for discoveries');const badges=node('details',undefined,'collection-context');badges.append(node('summary','Recognition for discoveries'));if(badgeTitle){badges.append(badgeTitle.nextElementSibling,$('contributionBadges'));badgeTitle.remove();prepare.append(badges);}const optional=node('details',undefined,'collection-context');optional.append(node('summary','Choose a suggested mission or refine the research scope'));for(const id of ['proposedThreadTitle','researchMission','missionBrief','researchGap','gapQuestion']){const field=$(id),label=prepare.querySelector('label[for="'+id+'"]');if(label)optional.append(label);optional.append(field);}prepare.insertBefore(optional,$('makeResearchPrompt'));document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>show(b.dataset.view));document.querySelectorAll('[data-research-tab]').forEach(b=>b.onclick=()=>tab(b.dataset.researchTab));$('connectionDepth').onchange=renderNetwork;$('resetJourney').onclick=()=>{selected=WorldThreadsApp.state.threads.find(t=>t.id===WorldThreadsApp.state.threadId).nodeIds[0];trail=[selected];renderNetwork();};$('startExploring').onclick=()=>$('threadGallery').scrollIntoView({behavior:'smooth'});tab('prepare');gallery();renderNetwork();show('discover');if(location.hash.startsWith('#receipt=')){show('research');tab('progress');} }
 window.WorldThreadsExplore={show,showEvidence};if(window.WorldThreadsApp?.state.observations.length)initialize();window.addEventListener('worldthreads-ready',initialize);window.addEventListener('worldthreads-rendered',()=>{if(initialized){gallery();renderNetwork();}});
})();
