import {VERSION,safePage,cleanContext,cleanDiagnostics,validateFeedback} from './feedback-core.mjs';
const endpoint=document.querySelector('meta[name="worldthreads-feedback-api"]')?.content||'https://worldthreads-feedback.stewartd.workers.dev/api/feedback';
const {errors,requests}=window.WorldThreadsFeedbackLog||{errors:[],requests:[]};const actions=[];
const push=(list,value,max)=>{list.push(value);if(list.length>max)list.shift();};
const controls=['data-thesis-stage','data-start-story','data-board-record','data-board-role','data-story-step','data-story-choice','data-object','data-thread','data-story-evidence','data-investigation-challenge','data-case-answer','data-case-clue','data-view','data-research-tab','data-lead-id'];
document.addEventListener('click',e=>{if(e.target.closest('.wt-feedback-dialog,.wt-feedback-launch'))return;const el=e.target.closest('button,a,summary');if(!el)return;const attr=controls.find(k=>el.hasAttribute(k));if(attr)push(actions,{control:attr,value:el.getAttribute(attr)},12);else if(['storyMode','objectsMode','researchMode','threadThesis','closeDialog','startInvestigation','startExploring','browseThreads','resumeJourney','caseCluePicker'].includes(el.id))push(actions,{control:el.id,value:null},12);});
function context(){
 const isThesis=!!document.querySelector('.thesis-workspace');const draft=isThesis&&typeof readThesisDraft==='function'?readThesisDraft():{},view=document.getElementById('researchLibrary')&&!document.getElementById('researchLibrary').hidden?'research':document.getElementById('objectExplorer')&&!document.getElementById('objectExplorer').hidden?'objects':'story';
 const legacy=window.WorldThreadsExplore?.feedbackState?.()||{};
 const legacyView=['discover','explore','research','group'].find(id=>document.getElementById(id+'View')&&!document.getElementById(id+'View').hidden);
 const evidenceDialog=document.getElementById('detailDialog');const detail=evidenceDialog?.open?(typeof inspector!=='undefined'?inspector.history?.[inspector.index]:{kind:evidenceDialog.dataset.feedbackKind,id:evidenceDialog.dataset.feedbackId}):null;
 const storyId=view==='story'&&!isThesis&&typeof story!=='undefined'?story.id:null;const activeStory=storyId&&typeof storyCatalog!=='undefined'?storyCatalog.find(s=>s.id===storyId):null;
 const progressLabel=document.querySelector('.progress-summary strong');const points=progressLabel?Number(progressLabel.textContent.match(/\d+/)?.[0]||0):null;
 const activeStage=document.querySelector('.thesis-route [aria-current="step"],.thesis-route [aria-pressed="true"]');
 const stage=activeStage?.dataset.thesisStage||(['present','research','defense','evidence'].find(s=>document.getElementById({present:'thesisPortfolio',research:'researchDesk',defense:'examinerRound',evidence:'argumentBoard'}[s])?.open)||'topic');
 const appSource=document.querySelector('script[src^="app.js"]')?.getAttribute('src');const appVersion=appSource?new URL(appSource,location.href).searchParams.get('v')||document.querySelector('footer span')?.textContent.match(/v[\d.]+/)?.[0]:null;
 return cleanContext({appVersion,dataStatus:document.getElementById('retryLoad')?'unavailable':typeof state!=='undefined'&&state.observations.length?'ready':'loading',view:legacy.view||legacyView||view,selectionId:legacy.selected||window.WorldThreadsExplore?.startingFact?.()?.id||null,caseState:legacy.caseState||null,stage:document.querySelector('.thesis-workspace')?stage:legacyView==='research'?document.querySelector('[data-research-tab].active')?.dataset.researchTab||null:null,storyId,step:storyId?story.step:null,threadId:draft.threadId||legacy.currentThread||activeStory?.thread||(typeof state!=='undefined'?state.threadId:null),objectId:draft.objectId||(detail?.kind==='object'?detail.id:null),inspector:detail,evidence:Array.from({length:3},(_,i)=>({id:draft['record'+i],role:draft['role'+i]})),filters:typeof state!=='undefined'?{system:state.system,region:state.region,period:state.period,objectType:typeof objectBrowse!=='undefined'?objectBrowse.type:null}:{},progress:{points,cases:typeof filedCases==='function'?filedCases().length:null,badges:document.querySelector('.earned-badges')?document.querySelectorAll('.earned-badges .earned').length:null}});
}
const dialog=document.createElement('dialog');dialog.className='wt-feedback-dialog';dialog.setAttribute('aria-labelledby','wtFeedbackTitle');
dialog.innerHTML=`<form id="wtFeedbackForm"><div class="wt-feedback-heading"><h2 id="wtFeedbackTitle">Share feedback</h2><button type="button" data-feedback-close aria-label="Close feedback">×</button></div><p>What felt confusing, broke, or could work better?</p><label>Feedback type<select name="kind"><option value="problem">Something is broken</option><option value="suggestion">Suggestion</option><option value="question">Question or confusing step</option><option value="history">Historical evidence or correction</option></select></label><label>Your feedback<textarea name="note" required maxlength="4000" rows="5" placeholder="What were you trying to do? What happened instead?"></textarea></label><label>Email, if you would like a reply<input name="email" type="email" maxlength="200" autocomplete="email"></label><div hidden><label>Website<input name="website" tabindex="-1" autocomplete="off"></label></div><label class="wt-feedback-check"><input type="checkbox" name="diagnostics" checked>Include device details and recent UI actions to help reproduce this</label><details><summary>See the state data that will be sent</summary><p>The current view, record IDs and progress go with your message. Device details and recent UI actions are optional. Thesis text, search text, research notes, source contents and browser storage are excluded. Error and failed-request locations are included, not messages, stacks or request contents.</p><pre id="wtFeedbackState" tabindex="0" role="region" aria-label="Captured interface state"></pre></details><p class="wt-feedback-privacy">Sent privately to the WorldThreads operator. It does not publish historical evidence or earn points. Reports are deleted 180 days after being marked done, with a maximum retention of one year.</p><p id="wtFeedbackStatus" role="status" aria-live="polite"></p><div class="wt-feedback-buttons"><button type="button" data-feedback-close>Cancel</button><button type="submit">Send feedback</button></div></form>`;
document.body.append(dialog);
const form=dialog.querySelector('form'),status=dialog.querySelector('#wtFeedbackStatus'),statePreview=dialog.querySelector('#wtFeedbackState'),send=form.querySelector('[type=submit]');
let opener=null,snapshot=null,diagnosticSnapshot=null,pendingId=null,pendingFingerprint=null,sending=false;
function currentPayload(){return {requestId:pendingId||crypto.randomUUID(),kind:form.elements.kind.value,note:form.elements.note.value,email:form.elements.email.value,website:form.elements.website.value,page:snapshot.page,context:snapshot.context,diagnostics:form.elements.diagnostics.checked?diagnosticSnapshot:null};}
function updatePreview(){statePreview.textContent=JSON.stringify({page:snapshot.page,version:VERSION,context:snapshot.context,diagnostics:form.elements.diagnostics.checked?diagnosticSnapshot:null},null,2);}
function openFeedback(button){opener=button;snapshot={page:safePage(location.href),context:context()};diagnosticSnapshot=cleanDiagnostics({viewport:{width:innerWidth,height:innerHeight,scale:devicePixelRatio},browser:navigator.userAgent,errors,requests,actions});status.textContent='';updatePreview();dialog.showModal();form.elements.note.focus();}
function closeFeedback(){if(sending){status.textContent='Your message is being sent. Wait for the result before closing.';return;}dialog.close();}
dialog.querySelectorAll('[data-feedback-close]').forEach(b=>b.addEventListener('click',closeFeedback));
dialog.addEventListener('cancel',e=>{if(sending){e.preventDefault();status.textContent='Your message is being sent. Wait for the result before closing.';}});
dialog.addEventListener('close',()=>{if(opener?.isConnected)opener.focus();});
form.elements.diagnostics.addEventListener('change',updatePreview);
form.addEventListener('submit',async e=>{e.preventDefault();if(sending)return;if(!form.reportValidity())return;let payload;try{payload=validateFeedback(currentPayload());}catch(error){status.textContent=error.message;return;}
 const fingerprint=JSON.stringify({...payload,requestId:null});if(fingerprint!==pendingFingerprint){pendingId=crypto.randomUUID();pendingFingerprint=fingerprint;}payload.requestId=pendingId;
 sending=true;send.disabled=true;status.textContent='Sending feedback…';
 try{const response=await fetch(endpoint,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload),signal:AbortSignal.timeout(15000),credentials:'omit'});const result=await response.json().catch(()=>({}));if(!response.ok||!result.ok||result.receipt!==payload.requestId)throw Error(result.error||'Feedback could not be saved. Please retry; your message is still here.');
  status.textContent='Feedback saved. Thank you. Reference: '+result.receipt.slice(0,8)+'.';form.elements.note.value='';form.elements.email.value='';pendingId=null;pendingFingerprint=null;
 }catch(error){status.textContent=error.name==='TimeoutError'||error instanceof TypeError?'Feedback could not be sent. Check your connection and retry; your message is still here.':error.message;}finally{sending=false;send.disabled=false;}
});
function launchButton(label,inline=false){const button=document.createElement('button');button.type='button';button.className='wt-feedback-launch'+(inline?' wt-feedback-inline':'');button.textContent=label;button.addEventListener('click',()=>openFeedback(button));return button;}
document.body.append(launchButton('Share feedback'));
document.getElementById('detailDialog')?.append(launchButton('Share feedback about this evidence',true));
