// Evidence-led media for the harvest story. UI exploration never creates evidence or rewards.
const harvestMedia={
 photo:'https://assets.science.nasa.gov/dynamicimage/assets/science/esd/eo/images/imagerecords/39000/39412/ISS020-E-06563_lrg.jpg?crop=faces%2Cfocalpoint&fit=clip&h=960&w=1440',
 nasa:'https://science.nasa.gov/earth/earth-observatory/mount-tambora-volcano-sumbawa-island-indonesia-39412/',
 aerosols:'https://science.nasa.gov/science-research/earth-science/climate-science/aerosols-small-particles-with-big-climate-effects/',
 korea:'https://link.springer.com/article/10.1007/s10584-023-03480-w'
};
function harvestLocator(){
 const places=[['tambora','Tambora',118,-8,1],['bohemia','Czech Lands',15,50,2],['korea','Korea',127,37,4]];
 return `<section class="harvest-locator" aria-label="Places in this investigation"><div class="harvest-earth"><svg viewBox="0 0 720 360" aria-hidden="true" focusable="false"><path d="${harvestWorldLand}" class="harvest-land"/><path d="M0 180H720M360 0V360" class="earth-grid"/>${places.map(([,label,lon,lat],i)=>`<circle cx="${(lon+180)*2}" cy="${(90-lat)*2}" r="5" class="locator-dot"/><text x="${(lon+180)*2+9}" y="${(90-lat)*2+4}" class="locator-number">${i+1}</text>`).join('')}</svg>${places.map(([id,label,lon,lat,unlock],i)=>`<button class="place-pin ${story.step>=unlock?'place-revealed':''}" style="left:${(lon+180)/3.6}%;top:${(90-lat)/1.8}%" data-harvest-place="${id}" aria-pressed="false">${i+1} · ${escapeHtml(label)}<span>${story.step>=unlock?'Evidence available':'Place to investigate'}</span></button>`).join('')}</div><div id="harvestPlace" class="harvest-place-card" role="status">Select a place. Compare where the records come from before connecting their outcomes.</div><p class="media-note">Approximate place markers on modern coastlines · no historical borders or atmospheric transport paths. <a href="https://www.naturalearthdata.com/about/terms-of-use/" target="_blank" rel="noopener">Natural Earth, public domain</a>.</p></section>`;
}
const mechanismFrames=[
 ['An eruption introduces material into the atmosphere.','The April 1815 eruption is documented. This diagram illustrates a mechanism, not the eruption’s appearance.'],
 ['Volcanic gases can form sulfate aerosols.','The bright band represents particles in the atmosphere. Its size and density are illustrative.'],
 ['Some sunlight is reflected; less reaches the surface.','Cooling is part of the explanation. Local weather, crops and access to food still need separate evidence.']
];
function harvestMechanism(){
 return `<section class="mechanism-film" hidden aria-label="Volcanic mechanism animation" data-frame="0"><svg viewBox="0 0 640 260" role="img" aria-label="Conceptual diagram of a volcano, atmospheric particles and sunlight"><circle cx="548" cy="47" r="25" class="film-sun"/><path d="M0 222Q170 191 300 220T640 211V260H0Z" class="film-ground"/><path d="M65 221L148 127L221 221Z" class="film-volcano"/><path d="M130 146L148 127L164 149" class="film-crater"/><path class="film-plume" d="M150 124Q95 92 156 60Q205 26 252 63"/><g class="film-aerosols">${Array.from({length:18},(_,i)=>`<circle cx="${190+i*20}" cy="${66+(i%3)*13}" r="5"/>`).join('')}</g><path class="film-ray incoming" d="M527 66L457 106"/><path class="film-ray reflected" d="M457 106L399 26"/><path class="film-ray surface-ray" d="M457 106L335 219"/><text x="20" y="28">Conceptual explanation · not to scale</text></svg><div class="film-controls"><button type="button" data-film-play aria-pressed="false">Play explanation</button><button type="button" data-film-reset>Restart</button><label>Explanation step <input id="filmScrub" type="range" min="0" max="2" value="0" step="1" aria-label="Explanation step"></label></div><p id="filmCaption" role="status"><strong>${mechanismFrames[0][0]}</strong> ${mechanismFrames[0][1]}</p><p class="media-note">Three illustrated steps, with pause and scrubbing. <a href="${harvestMedia.aerosols}" target="_blank" rel="noopener">Mechanism background: NASA</a>. <button class="story-link" data-story-claim="REL-0005">Inspect the historical attribution and its limits ↗</button></p></section>`;
}
function koreaMeasure(measure='prefectures'){
 if(measure==='paddies')return `<div class="paddy-measure"><svg viewBox="0 0 150 150" role="img" aria-label="11.2 percent of assessed paddy area was tax exempt"><circle cx="75" cy="75" r="55" class="paddy-base"/><circle cx="75" cy="75" r="55" class="paddy-share" pathLength="100" stroke-dasharray="11.2 88.8" transform="rotate(-90 75 75)"/><text x="75" y="83" text-anchor="middle">11.2%</text></svg><div><h3>Tax exemption measures a different thing.</h3><p>Share of assessed paddy area reported tax exempt in 1816, across six assessed provinces.</p><p>It is not a percentage of households fed or a measurement of crop tonnage.</p></div></div>`;
 return `<div class="prefecture-count" role="img" aria-label="17 of 336 prefectures reported poor crop yields in 1816; each marker represents one prefecture, not its location">${Array.from({length:336},(_,i)=>`<span class="prefecture ${i<17?'poor-report':''}" aria-hidden="true"></span>`).join('')}</div><div class="count-legend"><span><i class="poor-key"></i>17 poor-yield reports</span><span><i></i>319 remaining prefectures</span></div><p><strong>17 of 336</strong> prefectures reported poor yields. Markers represent administrative counts, not locations or equal areas.</p><p class="media-note">A good aggregate harvest does not establish food access in every household.</p>`;
}
function harvestVisual(){
 if(story.step===0)return `<div class="harvest-exhibit"><p class="eyebrow">One year · three places to investigate</p>${harvestLocator()}</div>`;
 if(story.step===1)return `<div class="harvest-exhibit"><div class="measure-controls" role="group" aria-label="Choose how to explore the eruption"><button data-harvest-view="photo" aria-pressed="true">Explore the real volcano</button><button data-harvest-view="mechanism" aria-pressed="false">See the climate mechanism</button></div><figure class="caldera-evidence"><div class="caldera-window"><img id="calderaPhoto" src="${harvestMedia.photo}" alt="NASA astronaut photograph of Tambora’s caldera in 2009, with a crater lake and steep walls" referrerpolicy="no-referrer" onerror="this.hidden=true;this.parentElement.querySelector('.photo-fallback').hidden=false"><p class="photo-fallback" hidden>Photograph unavailable here. The NASA source remains available below.</p></div><label class="photo-zoom">Explore the caldera <input type="range" id="calderaZoom" min="1" max="2.5" step=".1" value="1" aria-label="Caldera photograph zoom"></label><figcaption>Modern physical context, not 1815 footage. NASA / ISS Expedition 20, ISS020-E-6563; caption dates acquisition to 3 June 2009. <a href="${harvestMedia.nasa}" target="_blank" rel="noopener">Image, credit and source ↗</a></figcaption></figure>${harvestMechanism()}</div>`;
 if(story.step===2)return '';
 if(story.step===3)return `<section class="harvest-exhibit" aria-label="Two hypotheses to test"><div class="hypothesis-scenes"><div>${storySceneArt('harvests')}<strong>One outcome everywhere?</strong></div><div>${storySceneArt('relief')}<strong>Different local outcomes?</strong></div></div><p class="media-note">Illustrated hypotheses, not observed results. Make your prediction below before revealing the next record.</p></section>`;
 if(story.step===4&&!harvestInquiry.revealed)return '';
 if(story.step===4)return `<section class="harvest-exhibit korea-evidence" aria-label="Korean administrative evidence"><h2 id="koreaEvidenceHeading" tabindex="-1">What do the Korean reports show?</h2><p class="media-note">1816 · administrative evidence, not household food access.</p><div class="measure-controls" role="group" aria-label="Choose an evidence measure"><button data-korea-measure="prefectures" aria-pressed="true">Prefecture reports</button><button data-korea-measure="paddies" aria-pressed="false">Paddy tax exemption</button></div><div id="koreaMeasure">${koreaMeasure()}</div><details class="harvest-detail"><summary>Sources and how to read these measures</summary><p class="media-note">WorldThreads redrawing of figures reported by Sungwoo Kim (2023), section 3 / figure 2; based on historical administrative records. <a href="${harvestMedia.korea}" target="_blank" rel="noopener">Inspect the scholarly analysis ↗</a> · <a href="https://creativecommons.org/licenses/by/4.0/" target="_blank" rel="noopener">CC BY 4.0</a>. <button class="story-link" data-story-evidence="WT-1816-0045">Check the source, denominators and limits ↗</button></p></details></section>`;
 return `<details class="harvest-detail optional-investigation"><summary>Another investigation: did relief reach households?</summary><section class="harvest-exhibit" aria-label="Evidence boundary"><div class="evidence-chain"><button data-story-evidence="WT-1816-0006">${recordIcon('prices')}<strong>Price pressure</strong><small>Evidence in the Czech Lands</small></button><span class="chain-link">Different place & evidence</span><button data-story-evidence="WT-1816-0035">${recordIcon('decree')}<strong>Relief authorized</strong><small>Amsterdam · June 1817</small></button><span class="chain-link uncertain-link">Delivery remains unverified</span><button class="missing-evidence" data-harvest-frontier><span class="missing-symbol">?</span><strong>Who received it?</strong><small>Investigate the missing records</small></button></div><p class="media-note">These are research questions across regions, not a demonstrated delivery chain. Authorization is not evidence of household benefit.</p></section></details>`;
}
let harvestFilmTimer=null;
function stopHarvestFilm(){if(harvestFilmTimer!==null)clearInterval(harvestFilmTimer);harvestFilmTimer=null;const b=document.querySelector('[data-film-play]');if(b){b.textContent='Play explanation';b.setAttribute('aria-pressed','false');}}
function setFilmFrame(n){const film=document.querySelector('.mechanism-film');if(!film)return;film.dataset.frame=String(n);document.getElementById('filmScrub').value=n;document.getElementById('filmCaption').innerHTML=`<strong>${mechanismFrames[n][0]}</strong> ${mechanismFrames[n][1]}`;}
function bindHarvestVisuals(){
 document.getElementById('storyJourney').addEventListener('click',e=>{
  const view=e.target.closest('[data-harvest-view]');if(view){stopHarvestFilm();document.querySelector('.caldera-evidence').hidden=view.dataset.harvestView!=='photo';document.querySelector('.mechanism-film').hidden=view.dataset.harvestView!=='mechanism';document.querySelectorAll('[data-harvest-view]').forEach(b=>b.setAttribute('aria-pressed',String(b===view)));return;}
  const place=e.target.closest('[data-harvest-place]');if(place){const id=place.dataset.harvestPlace;const info={tambora:['Tambora · April 1815','Eruption evidence','WT-1816-0008',1],bohemia:['Czech Lands · 1816–1817','Weather, harvest and price evidence','WT-1816-0006',2],korea:['Chosŏn Korea · 1816','Crop-report evidence','WT-1816-0045',4]}[id];document.querySelectorAll('[data-harvest-place]').forEach(b=>b.setAttribute('aria-pressed',String(b===place)));document.getElementById('harvestPlace').innerHTML=`<strong>${info[0]}</strong><p>${info[1]} ${story.step>=info[3]?`<button class="story-link" data-story-evidence="${info[2]}">Inspect this record ↗</button>`:'will unfold in a later step. Make your prediction before comparing outcomes.'}</p>`;return;}
  const metric=e.target.closest('[data-korea-measure]');if(metric){document.getElementById('koreaMeasure').innerHTML=koreaMeasure(metric.dataset.koreaMeasure);document.querySelectorAll('[data-korea-measure]').forEach(b=>b.setAttribute('aria-pressed',String(b===metric)));return;}
  if(e.target.closest('[data-film-reset]')){stopHarvestFilm();setFilmFrame(0);return;}
  const play=e.target.closest('[data-film-play]');if(play){if(harvestFilmTimer!==null){stopHarvestFilm();return;}if(document.getElementById('filmScrub').value==='2')setFilmFrame(0);play.textContent='Pause explanation';play.setAttribute('aria-pressed','true');harvestFilmTimer=setInterval(()=>{if(!document.querySelector('.mechanism-film')){stopHarvestFilm();return;}const next=Number(document.getElementById('filmScrub').value)+1;setFilmFrame(Math.min(2,next));if(next>=2)stopHarvestFilm();},3500);}
 });
 document.getElementById('storyJourney').addEventListener('input',e=>{if(e.target.id==='filmScrub'){stopHarvestFilm();setFilmFrame(Number(e.target.value));}if(e.target.id==='calderaZoom')document.getElementById('calderaPhoto').style.transform=`scale(${Number(e.target.value)})`;});
}
