/* A question to test, not a new accepted historical claim. Passage-level leads. */
window.WorldThreadsInvestigation={
  id:'CASE-FRANKENSTEIN',threadId:'THREAD-CLIMATE-CULTURE',targetClaimId:'REL-0009',startingFactId:'WT-1816-0015',
  title:'Was weather the decisive influence on Frankenstein?',
  claim:'Bad weather was the decisive reason Frankenstein began in 1816.',
  boundary:'This is a deliberately strong claim to test, not an established conclusion. “Decisive” means more than being part of the setting.',
  sourceUrl:'https://www.gutenberg.org/files/42324/42324-h/42324-h.htm',
  sourcesNote:'These passages come from one transcribed edition. Four are Mary Shelley’s retrospective 1831 introduction. The reproduced 1817 preface is attributed to Percy Shelley. They are not five independent witnesses.',
  leads:[
    {id:'rain',title:'Rain kept the group indoors',date:'1831 recollection of summer 1816',locator:'Introduction, paragraph beginning “But it proved”',quote:'But it proved a wet, ungenial summer, and incessant rain often confined us for days to the house.',question:'Does confinement explain why a story was written—or only where people spent their time?',limits:'A later recollection of the setting; no measure of how much weather contributed.'},
    {id:'challenge',title:'Byron proposed a ghost-story challenge',date:'1831 recollection of summer 1816',locator:'Introduction, paragraph beginning “We will each write”',quote:'"We will each write a ghost story," said Lord Byron; and his proposition was acceded to.',question:'Was this the immediate trigger? What would distinguish it from the weather as an explanation?',limits:'Reported by the same retrospective witness; a trigger need not be the sole cause.'},
    {id:'science',title:'Conversations explored the principle of life',date:'1831 recollection of summer 1816',locator:'Introduction, paragraph beginning “Many and long”',quote:'During one of these, various philosophical doctrines were discussed, and among others the nature of the principle of life, and whether there was any probability of its ever being discovered and communicated.',question:'Could scientific ideas explain the kind of story Shelley imagined better than the weather?',limits:'The following sentences discuss life and galvanism. This account describes conversations, not proof of the experiments or their relative influence.'},
    {id:'choice',title:'Shelley chose how to turn fear into a story',date:'1831 recollection of summer 1816',locator:'Introduction, paragraph beginning “Swift as light”',quote:'What terrified me will terrify others; and I need only describe the spectre which had haunted my midnight pillow.',question:'What part belongs to the circumstances, and what part belongs to the author’s creative choices?',limits:'A retrospective account of inspiration. Manuscripts can help test the writing chronology.'},
    {id:'serene',title:'An earlier preface says the weather improved',date:'1817 preface about summer 1816',locator:'Preface, paragraph beginning “The weather, however”',quote:'The weather, however, suddenly became serene; and my two friends left me on a journey among the Alps',question:'Does the 1817 account of improved weather weaken the weather explanation, or distinguish the trigger from continued writing?',limits:'An earlier creation account attributed to Percy Shelley. It does not establish exactly when conception or drafting occurred.'}
  ]
};
