const reliefInvestigation=[
 {title:'Where would you start looking?',surface:'You want to know whether food became harder to obtain. Several records survive. Which one directly helps you investigate affordability?',clues:['WT-1816-0033','WT-1816-0032','WT-1816-0035'],required:['WT-1816-0032'],question:'What can the Amsterdam price record establish?',options:['Staple prices rose sharply, increasing pressure on people buying food.','Every Amsterdam household went hungry.','There was no grain anywhere in the Netherlands.'],answer:0,reason:'The record supports a price rise. Hunger in every household and complete absence of grain would require other evidence.'},
 {title:'Two places. What can you connect?',surface:'You have a price signal from Amsterdam. A stock inventory survives from Delft. Compare the clues before deciding how they fit.',clues:['WT-1816-0032','WT-1816-0033'],required:['WT-1816-0032','WT-1816-0033'],question:'What is the careful connection between these records?',options:['The Delft inventory proves Amsterdam families received grain.','Price pressure and later stock monitoring are recorded; they do not prove distribution or a shared local outcome.','The inventory caused the earlier price rise.'],answer:1,reason:'These records show sequence and monitoring in different cities. The graph labels the connection PRECEDED, an association—not a delivery result.',claim:'REL-0024'},
 {title:'Could a response arrive too late?',surface:'Put the price record beside the account of imported grain. Look at both what happened and when. What problem does that reveal?',clues:['WT-1816-0032','WT-1816-0034'],required:['WT-1816-0032','WT-1816-0034'],question:'What do these clues support together?',options:['Any government purchase immediately ended the crisis.','Late arrival proves all imported grain was lost at sea.','Purchases responded to food pressure, but arrival time could delay availability; household benefit remains unmeasured.'],answer:2,reason:'The recorded relationship points from purchases to the pressure they responded to. Arrival is different from purchase, and neither alone measures household benefit.',claim:'REL-0025'},
 {title:'Find the missing layer.',surface:'Now a decree authorizes reduced-price rye. You have reached the edge of the recorded story. Decide which evidence would let you dig further.',clues:['WT-1816-0035','WT-1816-0034'],required:['WT-1816-0035','WT-1816-0034'],question:'Which next discovery would best test whether this relief reached poorer households?',options:['Another copy of the authorization decree, proving it existed.','Dated distribution or sales ledgers identifying recipients, quantities and prices.','A general statement that 1816 was unusually cold.'],answer:1,reason:'Delivery and recipient evidence would connect authorization to implementation. It could show limited reach or failed delivery as well as success; the conclusion remains open.',claim:'REL-0026'}
];
function currentInvestigation(){return story.id==='relief'?reliefInvestigation[story.step]:null;}
function caseSolved(){return storyProgress(story.id).solved.includes(story.step);}
function caseHtml(){
 const task=currentInvestigation();if(!task)return '';const p=storyProgress(story.id),solved=caseSolved(),ready=task.required.every(id=>p.clues.includes(story.step+'/'+id));
 const selected=task.clues.includes(story.clue)?obs(story.clue):null;
 const html=`<section class="case-workbench" aria-label="Evidence workbench"><div class="case-tools"><p class="eyebrow">Field tools · inspect, interpret, connect</p><p>These are summaries of existing sourced records, not invented historical artifacts. Inspect a clue to see what it says; open its source to check the passage and limits.</p></div>${visualClueTray(task,p)}${selected?`<article class="artifact-reading"><p class="eyebrow">Record summary · ${escapeHtml(evidenceClass(selected))}</p><p>${escapeHtml(selected.observation)}</p><p class="artifact-limit">${escapeHtml(selected.uncertainty||'Use the source to check the scope of this record; this summary is not a transcription.')}</p><button class="story-link" data-story-evidence="${selected.id}">Use the source lens: passage, context and limits ↗</button></article>`:'<p class="artifact-empty">Choose a clue above. Its summary will appear here.</p>'}<h2>${escapeHtml(task.question)}</h2><div class="story-choices">${task.options.map((option,i)=>`<button data-case-answer="${i}" ${ready&&!solved?'':'disabled'} aria-pressed="${solved&&i===task.answer}">${escapeHtml(option)}</button>`).join('')}</div><p id="caseFeedback" role="status" tabindex="-1">${solved?'✓ Interpretation supported. '+escapeHtml(task.reason):ready?'Compare the clues and choose the interpretation they support.':'Inspect the relevant clue'+(task.required.length>1?'s':'')+' before interpreting.'}</p>${solved&&task.claim?`<button class="story-link" data-story-claim="${task.claim}">Connection revealed: inspect its reasoning ↗</button>`:''}</section>`;
 if(!solved)return html;
 const sourceId=selected?.id||task.required[0];
 return `<section class="case-reveal"><p>✓ Layer interpreted · 20 points earned once</p><p>${escapeHtml(task.reason)}</p><button class="story-link" data-story-evidence="${sourceId}">Check the source and its limits ↗</button>${task.claim?`<button class="story-link" data-story-claim="${task.claim}">Connection revealed: inspect its reasoning ↗</button>`:''}<details class="completed-layer"><summary>Review the clues and your interpretation</summary>${html}</details></section>`;
}
function inspectCaseClue(id){const task=currentInvestigation();if(!task?.clues.includes(id))return;story.clue=id;recordProgress('clues',story.step+'/'+id);renderStory();document.querySelector(`[data-case-clue="${id}"]`).focus();}
function answerCase(answer){const task=currentInvestigation(),p=storyProgress(story.id);if(!task||!task.required.every(id=>p.clues.includes(story.step+'/'+id))||caseSolved())return;
 if(answer!==task.answer){document.getElementById('caseFeedback').textContent='This interpretation goes beyond—or reverses—the recorded evidence. Reinspect the places, dates and what each document actually establishes. No points lost; try another interpretation.';return;}
 recordProgress('solved',story.step);renderStory();document.querySelector('.case-reveal').setAttribute('tabindex','-1');document.querySelector('.case-reveal').focus();
}
