let restoringNavigation=false;
// A player may choose the next scene before the modal’s history.back() finishes.
// Keep that later route instead of restoring the scene they already left.
let pendingInspectorClose=null;
function investigationRoute(){const mode=!document.getElementById('researchLibrary').hidden?'research':!document.getElementById('objectExplorer').hidden?'objects':'story';const draft=readThesisDraft(),thesis=mode==='story'&&!!document.querySelector('.thesis-workspace');return {worldthreads:true,mode,storyId:thesis?null:story.id,step:story.step,threadId:state.threadId,library:Object.fromEntries(['region','query','period','evidence','sort','system'].map(k=>[k,state[k]])),objects:{...objectBrowse},thesis:thesis?(draft.threadId||draft.objectId):null,stage:document.getElementById('thesisPortfolio')?.open?'present':document.getElementById('researchDesk')?.open?'research':document.getElementById('examinerRound')?.open?'defense':document.getElementById('argumentBoard')?.open||document.getElementById('thesisEvidence')?.open?'evidence':'topic',inspector:document.getElementById('detailDialog').open?{history:inspector.history.map(x=>({...x})),index:inspector.index,tab:inspector.tab,linkFilter:inspector.linkFilter}:null};}
function setupNavigationHistory(){history.replaceState(investigationRoute(),'');document.getElementById('detailDialog').addEventListener('close',()=>{if(restoringNavigation||!history.state?.inspector)return;const next=investigationRoute();if(document.getElementById('defenseDetailDialog')?.open){history.replaceState(next,'');return;}if(pendingInspectorClose){pendingInspectorClose.next=next;return;}const previous={...history.state,inspector:null};if(JSON.stringify(next)===JSON.stringify(previous)){pendingInspectorClose={next:null};history.back();}else history.replaceState(next,'');});}
function rememberNavigation(replace=false){if(restoringNavigation||!appLoaded)return;const next=investigationRoute();if(pendingInspectorClose){pendingInspectorClose.next=next;return;}if(JSON.stringify(next)!==JSON.stringify(history.state)){if(replace||(history.state?.inspector&&next.inspector))history.replaceState(next,'');else history.pushState(next,'');}}
document.addEventListener('click',e=>{if(e.target.closest('#storyMode,#objectsMode,#researchMode,#threadThesis,[data-start-story],[data-story-step],[data-story-home],[data-open-thesis],[data-return-thread],[data-thread-thesis],[data-object-research],[data-thesis-stage],[data-portfolio-stage],[data-story-library],[data-thread],[data-object],[data-observation],[data-object-link],[data-story-evidence],[data-story-claim],[data-inspector-tab],[data-object-tab],[data-history],.card'))rememberNavigation();});
document.addEventListener('change',e=>{if(['threadSelect','regionSelect','periodSelect','evidenceSelect','sortSelect','objectType'].includes(e.target.id))rememberNavigation(true);});
document.addEventListener('input',e=>{if(['searchInput','objectSearch'].includes(e.target.id))rememberNavigation(true);});
window.addEventListener('popstate',e=>{if(pendingInspectorClose){const queued=pendingInspectorClose.next;pendingInspectorClose=null;if(queued){history.replaceState(queued,'');return;}}const route=e.state;if(!route?.worldthreads||!appLoaded)return;restoringNavigation=true;try{document.getElementById('detailDialog').close();Object.assign(state,route.library||{});Object.assign(objectBrowse,route.objects||{});for(const [id,key] of [['searchInput','query'],['regionSelect','region'],['periodSelect','period'],['evidenceSelect','evidence'],['sortSelect','sort']])document.getElementById(id).value=state[key];if(route.mode==='research'){setExperience('research');selectThread(route.threadId);renderCards();}else if(route.mode==='objects'){setExperience('objects');renderObjects();}else{setExperience('story');if(route.thesis){const draft=readThesisDraft();if((draft.threadId||draft.objectId)===route.thesis)openThesisWorkspace();else if(validThread(route.thesis))startThreadThesis(route.thesis);else startObjectResearch(route.thesis);document.querySelector('[data-thesis-stage="'+route.stage+'"]')?.click();}else{story.id=storyCatalog.some(s=>s.id===route.storyId)?route.storyId:null;story.step=Number.isInteger(route.step)?route.step:0;story.choice=story.id?storyProgress(story.id).choice:null;renderStory(true);}}if(route.inspector){Object.assign(inspector,route.inspector);inspector.opener=document.activeElement;renderInspector(true);}}finally{setTimeout(()=>restoringNavigation=false,0);}});
