const objectBrowse={type:'PERSON',query:'',limit:12};
function historicalObject(id){return state.objects.find(x=>x.id===id);}
function openObject(id){if(historicalObject(id))visitInspector({kind:'object',id});}
function objectTypeLabel(id){return state.objectTypes.find(x=>x.id===id)?.label||id;}
function objectLinkStatus(link){return link.relationshipKind==='HISTORICAL_CLAIM'?claimStatus(link):link.relationshipKind==='PARTICIPATION'?'Documented role · not a quantified impact':'Context · no causal claim';}
function renderObjects(){
 const root=document.getElementById('objectExplorer');
 if(!root.querySelector('#objectSearch'))root.innerHTML=`<header class="object-heading"><p class="eyebrow">Another way into the thread</p><h1>Start with someone. Or something.</h1><p>Explore what shaped it, what it changed, and the evidence connecting those forces.</p></header><div class="object-toolbar"><label>Find a person, place or thing<input id="objectSearch" type="search" placeholder="Macquarie, Tambora, Frankenstein…"></label><label>Object type<select id="objectType">${[['ALL','All types'],...state.objectTypes.map(x=>[x.id,x.label])].map(([id,label])=>`<option value="${id}" ${id===objectBrowse.type?'selected':''}>${escapeHtml(label)}</option>`).join('')}</select></label></div><p id="objectCount" class="object-count"></p><div id="objectCards" class="object-cards"></div><button class="story-back" id="moreObjects">Show more</button><p class="story-footnote">Objects identify things. Observations supply evidence about them. Recorded roles, historical causal claims and context remain distinct; missing links are research gaps.</p>`;
 const results=state.objects.filter(o=>(objectBrowse.type==='ALL'||o.type===objectBrowse.type)&&(!objectBrowse.query||[o.label,o.description,o.subtype,...o.regions].join(' ').toLowerCase().includes(objectBrowse.query.toLowerCase()))).sort((a,b)=>a.label.localeCompare(b.label));
 document.getElementById('objectCount').textContent=`${results.length} matching objects · ${state.objects.length} registered from current evidence`;
 document.getElementById('objectCards').innerHTML=results.slice(0,objectBrowse.limit).map(o=>`<button class="object-card" data-object="${o.id}"><span class="eyebrow">${escapeHtml(objectTypeLabel(o.type))}</span><h2>${escapeHtml(o.label)}</h2><p>${escapeHtml(o.regions.join(' · '))}</p><small>${o.observationIds.length} evidence records · ${state.objectRelationships.filter(r=>(r.subjectId===o.id||r.objectId===o.id)&&r.relationshipKind!=='CONTEXT').length} roles or change connections</small><strong>Explore its forces →</strong></button>`).join('')||'<p>No matching objects. Try another type or search.</p>';
 document.getElementById('moreObjects').hidden=results.length<=objectBrowse.limit;
}
function objectNode(o){return `<button class="neighbor-node object-neighbor" data-object="${o.id}"><span class="eyebrow">${escapeHtml(objectTypeLabel(o.type))}</span><strong>${escapeHtml(o.label)}</strong><small>${o.observationIds.length} evidence records</small></button>`;}
function objectEdgeHtml(r,selected,incoming){const neighbor=historicalObject(incoming?r.subjectId:r.objectId);return `<article class="neighbor-branch ${r.causalStatus.toLowerCase()}">${incoming?objectNode(neighbor):''}<button class="neighbor-edge ${r.causalStatus.toLowerCase()}" data-object-link="${r.id}"><span>${escapeHtml(predicateLabel(r))} →</span><small>${escapeHtml(objectLinkStatus(r))}</small><em>Inspect this connection</em></button>${incoming?'':objectNode(neighbor)}</article>`;}
function objectForcesHtml(o){
 const links=state.objectRelationships.filter(r=>(r.subjectId===o.id||r.objectId===o.id)&&r.relationshipKind!=='CONTEXT');const incoming=links.filter(r=>r.objectId===o.id),outgoing=links.filter(r=>r.subjectId===o.id);
 const targets=new Set(outgoing.filter(r=>r.relationshipKind==='PARTICIPATION').map(r=>r.objectId));
 const indirect=state.objectRelationships.filter(r=>r.relationshipKind==='HISTORICAL_CLAIM'&&(targets.has(r.subjectId)||targets.has(r.objectId)));
 const threads=state.threads.filter(t=>t.nodeIds.some(id=>o.observationIds.includes(id)));
 const context=state.objectRelationships.filter(r=>(r.subjectId===o.id||r.objectId===o.id)&&r.relationshipKind==='CONTEXT');
 return `<p class="object-force-intro">Follow an object to move the focus. Inspect a link to see what the evidence supports.</p><div class="focus-map object-force-map"><section class="neighbor-column"><h3>Connections into this object</h3>${incoming.map(r=>objectEdgeHtml(r,o,true)).join('')||`<p class="empty-neighbors">No direct incoming influence or role has been evidenced here yet. That is a research gap, not proof that nothing shaped this object.</p>`}</section><div class="focus-node"><span class="eyebrow">You are here</span><strong>${escapeHtml(o.label)}</strong><small>${escapeHtml(objectTypeLabel(o.type))}</small></div><section class="neighbor-column"><h3>Connections from this object</h3>${outgoing.map(r=>objectEdgeHtml(r,o,false)).join('')||'<p class="empty-neighbors">No outgoing change claims or roles have been evidenced here yet.</p>'}</section></div><p class="graph-key">Arrows read the verb: a response points toward its pressure. Roles identify agency; they do not measure the scale of influence. Associations do not establish causation.</p>${indirect.length?`<details class="indirect-forces"><summary>Forces around linked actions or works · ${indirect.length}</summary><p>These are connections involving this object’s actions or works. They do not establish a person’s motives or a direct influence on that person.</p>${indirect.map(r=>`<button class="object-indirect-link" data-object-link="${r.id}"><span>${escapeHtml(historicalObject(r.subjectId).label)}</span><strong>${escapeHtml(predicateLabel(r))} →</strong><span>${escapeHtml(historicalObject(r.objectId).label)}</span><small>${escapeHtml(objectLinkStatus(r))}</small></button>`).join('')}</details>`:''}<div class="thread-choices"><h3>Enter a thread through this object</h3>${threads.map(t=>`<button data-thread="${t.id}"><strong>${escapeHtml(t.title)}</strong><small>${escapeHtml(t.scope)}</small><span>↗</span></button>`).join('')||'<p>No curated thread includes this object’s evidence yet. Start by researching a missing influence link.</p>'}<button class="story-back" data-object-research="${o.id}">Research what shaped this object—or what it changed →</button></div>${context.length?`<details><summary>Places, institutions and context · ${context.length}</summary><div class="object-context">${context.map(r=>{const id=r.subjectId===o.id?r.objectId:r.subjectId;return `<button class="story-back" data-object="${id}">${escapeHtml(historicalObject(id).label)}</button>`;}).join('')}</div></details>`:''}`;
}
function objectRecordsHtml(o){return `<h3>Evidence about this object</h3><p>Each record retains its own date support, source and uncertainty. An object’s identity is not itself proof of a causal effect.</p><div class="object-evidence">${o.observationIds.map(id=>observationButton(obs(id))).join('')}</div>`;}
function renderObjectInspector(o){const links=state.objectRelationships.filter(r=>(r.subjectId===o.id||r.objectId===o.id)&&r.relationshipKind!=='CONTEXT');return `${inspectorNavigation()}<header class="inspector-heading"><p class="eyebrow">${escapeHtml(objectTypeLabel(o.type))} · ${escapeHtml(o.subtype.replaceAll('_',' '))}</p><h2 id="detailTitle" tabindex="-1">${escapeHtml(o.label)}</h2><p>${escapeHtml(o.description)}</p></header><nav class="inspector-tabs" aria-label="Object views">${[['connections',`Forces & roles · ${links.length}`],['evidence',`Evidence · ${o.observationIds.length}`],['facts','Identity & scope']].map(([id,label])=>`<button data-inspector-tab="${id}" aria-pressed="${inspector.tab===id}" ${inspector.tab===id?'class="selected"':''}>${label}</button>`).join('')}</nav><section class="inspector-body">${inspector.tab==='connections'?objectForcesHtml(o):inspector.tab==='evidence'?objectRecordsHtml(o):`<h3>Identity and focus</h3><p>${escapeHtml(o.identityNote)}</p><p>Evidence window: ${escapeHtml(o.focusDates.start)} → ${escapeHtml(o.focusDates.end)}</p><p>${escapeHtml(o.focusDates.meaning)}</p><p>${escapeHtml(o.regions.join(' · '))} · ${escapeHtml(o.researchStatus)}</p><h3>Sources behind linked observations</h3>${sourceHtml(o.sourceRefs)}`}</section>`;}
function openObjectLink(id){if(state.objectRelationships.some(r=>r.id===id))visitInspector({kind:'objectLink',id});}
function renderObjectLinkInspector(r){return `${inspectorNavigation()}<header class="inspector-heading"><p class="eyebrow">Assess an object connection</p><h2 id="detailTitle" tabindex="-1">What connects these objects?</h2></header><div class="claim-route">${objectNode(historicalObject(r.subjectId))}<div class="claim-arrow"><span>${escapeHtml(predicateLabel(r))}</span><strong aria-hidden="true">→</strong></div>${objectNode(historicalObject(r.objectId))}</div><div class="claim-verdict ${r.causalStatus.toLowerCase()}"><span>${escapeHtml(objectLinkStatus(r))}</span><strong>${escapeHtml(r.confidence)} recorded confidence</strong></div><section class="claim-reason"><h3>What the evidence supports</h3><p>${escapeHtml(r.explanation)}</p></section>${r.alternatives?.length?`<details open><summary>Alternatives</summary><ul>${r.alternatives.map(x=>`<li>${escapeHtml(x)}</li>`).join('')}</ul></details>`:''}<h3>Inspect the underlying claims</h3><div class="object-evidence">${r.evidenceObservationRefs.map(id=>observationButton(obs(id))).join('')}</div>${r.evidenceRelationshipRefs.map(id=>`<button class="story-back" data-relationship="${id}">Inspect original relationship ${id}</button>`).join('')}<h3>Sources</h3>${sourceHtml(r.sourceRefs)}`;}
function observationObjectsHtml(o){return `<details class="record-objects"><summary>People, places and things in this evidence · ${o.objectRefs.length}</summary><div class="object-context">${o.objectRefs.map(id=>`<button class="story-back" data-object="${id}">${escapeHtml(historicalObject(id).label)}</button>`).join('')}</div></details>`;}
