const PORTFOLIO_KEY='worldthreads-thesis-portfolios-v1';
function validPortfolio(x){return !!(x&&x.draft&&typeof x.draft==='object'&&!Array.isArray(x.draft)&&Array.isArray(x.records)&&x.records.every(r=>r&&typeof r.id==='string')&&Array.isArray(x.references)&&typeof x.context==='string'&&typeof x.at==='string'&&Number.isFinite(Date.parse(x.at))&&typeof x.fingerprint==='string');}
function thesisPortfolios(){return readStoredRecords(PORTFOLIO_KEY,validPortfolio);}
function portfolioFingerprint(draft){const copy={...draft};delete copy.savedAt;delete copy.aiCandidateReturn;return JSON.stringify(Object.fromEntries(Object.entries(copy).sort(([a],[b])=>a.localeCompare(b))));}
function portfolioRequirements(draft){const present=k=>String(draft[k]||'').trim();const evidence=Array.from({length:3},(_,i)=>({i,record:thesisRecord(draft['record'+i])})).filter(x=>x.record);return [
 ['Frame and plan your thesis',thesisFields.every(([key])=>present(key)),'topic'],
 ['Explain each selected record’s role and passage verification limits',evidence.length>0&&Array.from({length:3},(_,i)=>draft['record'+i]).filter(Boolean).every(id=>!!thesisRecord(id))&&evidence.every(({i})=>validArgumentRole(draft,i)&&present('claim'+i)&&present('locator'+i)),'evidence'],
 ['Document a research gap, source sought and search plan',['researchQuestion','researchSource','researchPlan'].every(present),'research'],
 ['Record a rival test and decision for the current argument and evidence',(draft.argumentRevisions||[]).some(r=>r.after===draft.argument&&r.evidenceKey===examinerEvidenceKey(draft)&&r.rival&&r.ownPrediction&&r.rivalPrediction&&r.reason),'defense']
 ];}
function portfolioHtml(){return `<details id="thesisPortfolio"><summary>Present your thesis portfolio · finish this research round</summary><p>File a dated copy of your argument, evidence, rival test and open research tasks. The checkpoint records preparation, not accuracy. Unavailable evidence can remain openly unresolved.</p><div id="portfolioRecovery"></div><details id="portfolioSourceReview"><summary>Source provenance · review before defending your thesis</summary><div id="portfolioSourceNotes"></div></details><div id="portfolioChecklist"></div><button type="button" class="story-next" data-file-portfolio>File my thesis portfolio locally</button><p id="portfolioStatus" role="status">Nothing is sent to a reviewer or published. Filing earns the Portfolio presenter badge and 50 points once.</p><button type="button" class="story-back" data-download-portfolio disabled>Download the filed portfolio</button><div id="portfolioHistory"></div></details>`;}
function renderPortfolio(draft){const notes=document.getElementById('portfolioSourceNotes');if(notes)notes.innerHTML='<p>These reminders do not certify independent evidence or checked passages.</p>'+sourceProvenanceNotes(draft).map(note=>'<p>'+escapeHtml(note)+'</p>').join('');const recovery=document.getElementById('portfolioRecovery');if(recovery)recovery.innerHTML=recordRecoveryHtml(PORTFOLIO_KEY,validPortfolio,'Portfolio recovery');const root=document.getElementById('portfolioChecklist');if(!root)return;const requirements=portfolioRequirements(draft),html=requirements.map(([label,done,stage])=>`<p>${done?'✓':'○'} ${escapeHtml(label)} ${done?'':`<button type="button" class="story-link" data-portfolio-stage="${stage}">Work on this step →</button>`}</p>`).join('');if(root.innerHTML!==html)root.innerHTML=html;
 renderPortfolioHistory(draft);
}
function filePortfolio(){const form=document.getElementById('thesisForm');if(!form)return;const status=document.getElementById('portfolioStatus');if(!saveThesisDraft({target:form,preventDefault(){}})){status.textContent='Portfolio not filed: the current draft could not be saved. Resolve the save problem or download your current work.';return;}const draft=readThesisDraft();if(!portfolioRequirements(draft).every(([,done])=>done)){status.textContent='Portfolio not filed. Complete the open preparation steps above; do not invent findings to fill a gap.';return;}const context=draft.threadId||draft.objectId||'cross-story',fingerprint=portfolioFingerprint(draft),entries=thesisPortfolios(),last=entries.filter(x=>x.context===context).at(-1);if(last?.fingerprint===fingerprint){status.textContent='This unchanged portfolio is already filed. No duplicate or extra points added.';return;}const records=[...new Set(Array.from({length:3},(_,i)=>draft['record'+i]).filter(Boolean))].map(thesisRecord).filter(Boolean);const references=[...new Set(records.flatMap(o=>o.sourceRefs||[]))].map(source).filter(Boolean);const entry={at:new Date().toISOString(),context,fingerprint,draft,records,references,status:'Locally filed, unreviewed research portfolio',sourceReview:{status:'Unreviewed provenance reminders',notes:sourceProvenanceNotes(draft)}};try{writeStoredRecords(PORTFOLIO_KEY,[...entries,entry],validPortfolio);renderPortfolio(draft);renderPortfolioHistory(draft,true);renderProgress();status.textContent='Research round completed: portfolio filed locally. Portfolio presenter earned once. Your claims remain unreviewed; the historical gaps remain open.';}catch(e){status.textContent='Portfolio not filed: '+e.message+'. No badge was earned.';}}
function portfolioEntries(draft){const context=draft.threadId||draft.objectId||'cross-story';return thesisPortfolios().filter(x=>x.context===context);}
function selectedPortfolio(){const entries=portfolioEntries(readThesisDraft()),select=document.getElementById('portfolioVersion');return entries[Number(select?.value??entries.length-1)];}
function renderPortfolioHistory(draft,latest=false){const entries=portfolioEntries(draft),last=entries.at(-1),root=document.getElementById('portfolioHistory');if(!root)return;document.querySelector('[data-download-portfolio]').disabled=!last;if(!last){root.textContent='No portfolio filed for this investigation yet.';root.dataset.signature='';return;}const context=draft.threadId||draft.objectId||'cross-story',signature=JSON.stringify(entries.map(x=>[x.at,x.fingerprint]));const previous=root.querySelector('#portfolioVersion')?.value,sameContext=root.dataset.context===context;if(root.dataset.signature!==signature){root.dataset.context=context;root.dataset.signature=signature;root.innerHTML=`<p id="portfolioLatest"></p><label>Review a filed version<select id="portfolioVersion">${entries.map((x,i)=>`<option value="${i}">Version ${i+1} · ${escapeHtml(examinerDate(x.at))}</option>`).join('')}</select></label><details><summary>Compare this draft with the selected filed version</summary><div id="portfolioComparison"></div></details>`;root.querySelector('#portfolioVersion').value=sameContext&&previous!==undefined&&!latest?previous:String(entries.length-1);}if(latest)root.querySelector('#portfolioVersion').value=String(entries.length-1);root.querySelector('#portfolioLatest').textContent=`${entries.length} filed ${entries.length===1?'version':'versions'} · ${examinerDate(last.at)}. `+(last.fingerprint===portfolioFingerprint(draft)?'This draft matches your latest filed version.':'Your working draft has changed since filing. The earlier portfolio is preserved; complete the checks and file a revised version.');renderPortfolioComparison(draft);}
function renderPortfolioComparison(draft){const entry=selectedPortfolio(),root=document.getElementById('portfolioComparison');if(!root||!entry)return;const previous=entry.draft,ids=d=>[...new Set(Array.from({length:3},(_,i)=>d['record'+i]).filter(Boolean))],oldIds=ids(previous),currentIds=ids(draft),title=id=>entry.records.find(x=>x.id===id)?.title||thesisRecord(id)?.title||thesisRecord(id)?.claim||id;const added=currentIds.filter(id=>!oldIds.includes(id)),removed=oldIds.filter(id=>!currentIds.includes(id));const interpretations=Array.from({length:3},(_,i)=>['record','role','claim','locator'].some(key=>previous[key+i]!==draft[key+i])?i+1:null).filter(Boolean);root.innerHTML=`<p><strong>Filed argument:</strong> ${escapeHtml(previous.argument||'[Not drafted]')}</p><p><strong>Working argument:</strong> ${escapeHtml(draft.argument||'[Not drafted]')}</p><p>Evidence added: ${escapeHtml(added.map(title).join('; ')||'None')}</p><p>Evidence removed: ${escapeHtml(removed.map(title).join('; ')||'None')}</p><p>Evidence entries with changed selection, interpretation or citation: ${interpretations.join(', ')||'None'}</p><p>The filed copy stays unchanged. Use Download to take the selected version away for review.</p>`;}
function downloadPortfolio(){const entry=selectedPortfolio();if(!entry)return;const url=URL.createObjectURL(new Blob([JSON.stringify(entry,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download='worldthreads-filed-thesis-portfolio.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
document.addEventListener('click',e=>{if(e.target.closest('[data-file-portfolio]'))filePortfolio();if(e.target.closest('[data-download-portfolio]'))downloadPortfolio();});
document.addEventListener('change',e=>{if(e.target.id==='portfolioVersion')renderPortfolioComparison(readThesisDraft());});
