const PORTFOLIO_KEY='worldthreads-thesis-portfolios-v1';
function thesisPortfolios(){try{const values=JSON.parse(localStorage.getItem(PORTFOLIO_KEY)||'[]');return Array.isArray(values)?values.filter(x=>x&&x.draft&&Array.isArray(x.records)&&typeof x.fingerprint==='string'):[];}catch{return [];}}
function portfolioFingerprint(draft){const copy={...draft};delete copy.savedAt;delete copy.aiCandidateReturn;return JSON.stringify(Object.fromEntries(Object.entries(copy).sort(([a],[b])=>a.localeCompare(b))));}
function portfolioRequirements(draft){const present=k=>String(draft[k]||'').trim();const evidence=Array.from({length:3},(_,i)=>({i,record:thesisRecord(draft['record'+i])})).filter(x=>x.record);return [
 ['Frame and plan your thesis',thesisFields.every(([key])=>present(key)),'topic'],
 ['Explain each selected record’s role and passage verification limits',evidence.length>0&&evidence.every(({i})=>validArgumentRole(draft,i)&&present('claim'+i)&&present('locator'+i)),'evidence'],
 ['Document a research gap, source sought and search plan',['researchQuestion','researchSource','researchPlan'].every(present),'research'],
 ['Record a rival test and decision for the current argument',(draft.argumentRevisions||[]).some(r=>r.after===draft.argument&&r.rival&&r.ownPrediction&&r.rivalPrediction&&r.reason),'defense']
 ];}
function portfolioHtml(){return `<details id="thesisPortfolio"><summary>Present your thesis portfolio · finish this research round</summary><p>File a dated copy of your argument, evidence, rival test and open research tasks. The checkpoint records preparation, not accuracy. Unavailable evidence can remain openly unresolved.</p><div id="portfolioChecklist"></div><button type="button" class="story-next" data-file-portfolio>File my thesis portfolio locally</button><p id="portfolioStatus" role="status">Nothing is sent to a reviewer or published. Filing earns the Portfolio presenter badge and 50 points once.</p><button type="button" class="story-back" data-download-portfolio disabled>Download the filed portfolio</button><div id="portfolioHistory"></div></details>`;}
function renderPortfolio(draft){const root=document.getElementById('portfolioChecklist');if(!root)return;const requirements=portfolioRequirements(draft),html=requirements.map(([label,done,stage])=>`<p>${done?'✓':'○'} ${escapeHtml(label)} ${done?'':`<button type="button" class="story-link" data-portfolio-stage="${stage}">Work on this step →</button>`}</p>`).join('');if(root.innerHTML!==html)root.innerHTML=html;
 const context=draft.threadId||draft.objectId||'cross-story',entries=thesisPortfolios().filter(x=>x.context===context),last=entries.at(-1),history=document.getElementById('portfolioHistory');document.querySelector('[data-download-portfolio]').disabled=!last;history.textContent=last?`${entries.length} filed ${entries.length===1?'version':'versions'} · ${examinerDate(last.at)}. `+(last.fingerprint===portfolioFingerprint(draft)?'This draft matches your latest filed version.':'Your working draft has changed since filing. The earlier portfolio is preserved; complete the checks and file a revised version.'):'No portfolio filed for this investigation yet.';
}
function filePortfolio(){const form=document.getElementById('thesisForm');if(!form)return;saveThesisDraft({target:form,preventDefault(){}});const draft=readThesisDraft(),status=document.getElementById('portfolioStatus');if(!portfolioRequirements(draft).every(([,done])=>done)){status.textContent='Portfolio not filed. Complete the open preparation steps above; do not invent findings to fill a gap.';return;}const context=draft.threadId||draft.objectId||'cross-story',fingerprint=portfolioFingerprint(draft),entries=thesisPortfolios(),last=entries.filter(x=>x.context===context).at(-1);if(last?.fingerprint===fingerprint){status.textContent='This unchanged portfolio is already filed. No duplicate or extra points added.';return;}const records=[...new Set(Array.from({length:3},(_,i)=>draft['record'+i]).filter(Boolean))].map(thesisRecord).filter(Boolean);const references=[...new Set(records.flatMap(o=>o.sourceRefs||[]))].map(source).filter(Boolean);const entry={at:new Date().toISOString(),context,fingerprint,draft,records,references,status:'Locally filed, unreviewed research portfolio'};try{localStorage.setItem(PORTFOLIO_KEY,JSON.stringify([...entries,entry]));renderPortfolio(draft);renderProgress();status.textContent='Research round completed: portfolio filed locally. Portfolio presenter earned once. Your claims remain unreviewed; the historical gaps remain open.';}catch{status.textContent='Browser storage is unavailable. The portfolio was not filed and no badge was earned.';}}
function downloadPortfolio(){const d=readThesisDraft(),context=d.threadId||d.objectId||'cross-story',entry=thesisPortfolios().filter(x=>x.context===context).at(-1);if(!entry)return;const url=URL.createObjectURL(new Blob([JSON.stringify(entry,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download='worldthreads-filed-thesis-portfolio.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
document.addEventListener('click',e=>{if(e.target.closest('[data-file-portfolio]'))filePortfolio();if(e.target.closest('[data-download-portfolio]'))downloadPortfolio();});
