const PROGRESS_KEY='worldthreads-investigation-progress-v1';
function freshProgress(){return {version:1,stories:{},challenges:[]};}
function readProgress(){try{const p=JSON.parse(localStorage.getItem(PROGRESS_KEY)||'null');if(p?.version!==1||!p.stories||typeof p.stories!=='object'||Array.isArray(p.stories))return freshProgress();return {version:1,stories:p.stories,challenges:Array.isArray(p.challenges)?p.challenges.filter(x=>['causation','comparison'].includes(x)):[]};}catch{return freshProgress();}}
let investigationProgress=readProgress(),progressStored=true;
function storyProgress(id){const p=investigationProgress.stories[id]||{};return {caseFiled:p.caseFiled===true,clues:Array.isArray(p.clues)?p.clues.filter(x=>typeof x==='string'):[],solved:Array.isArray(p.solved)?p.solved.filter(Number.isInteger):[],visited:Array.isArray(p.visited)?p.visited.filter(Number.isInteger):[],sources:Array.isArray(p.sources)?p.sources.filter(x=>typeof x==='string'):[],connections:Array.isArray(p.connections)?p.connections.filter(x=>typeof x==='string'):[],choice:['universal','regional'].includes(p.choice)?p.choice:null,draft:p.draft===true,last:Number.isInteger(p.last)?p.last:0};}
function persistProgress(){try{localStorage.setItem(PROGRESS_KEY,JSON.stringify(investigationProgress));progressStored=true;}catch{progressStored=false;}}
function recordProgress(kind,value){
 if(!story.id||!storyCatalog.some(s=>s.id===story.id))return;
 const p=storyProgress(story.id);
 if(['visited','sources','connections','clues','solved'].includes(kind)&&!p[kind].includes(value))p[kind].push(value);
 if(kind==='visited')p.last=value;if(kind==='choice')p.choice=value;if(kind==='draft')p.draft=true;if(kind==='caseFiled')p.caseFiled=true;
 investigationProgress.stories[story.id]=p;persistProgress();renderProgress();
}
function completedStory(s){const p=storyProgress(s.id),n=(s.chapters||storyChapters).length;return Array.from({length:n},(_,i)=>i).every(i=>p.visited.includes(i))&&p.sources.length>0&&p.connections.length>0&&(!s.chapters?p.choice!==null:true)&&(s.id!=='relief'||[0,1,2,3].every(i=>p.solved.includes(i)));}
function pointsFor(s){const p=storyProgress(s.id),n=(s.chapters||storyChapters).length;return new Set(p.visited.filter(i=>i>=0&&i<n)).size*5+(p.sources.length?20:0)+(p.connections.length?20:0)+(p.choice?10:0)+(completedStory(s)?30:0)+(p.draft?15:0)+(p.caseFiled?75:0)+(s.id==='relief'?new Set(p.solved.filter(i=>i>=0&&i<4)).size*20:0);}
function progressTotals(){const complete=storyCatalog.filter(completedStory);const points=storyCatalog.reduce((n,s)=>n+pointsFor(s),0)+new Set(investigationProgress.challenges).size*40+(expeditionFinished()?150:0)+(thesisPortfolios().length?50:0);return {complete,points,rank:expeditionFinished()?'1816 Investigator':filedCases().length?'Case builder':'Curious investigator'};}
function renderProgress(){
 const root=document.getElementById('investigationProgress');if(!root)return;const {complete,points,rank}=progressTotals();
 const active=story.id?storyCatalog.find(s=>s.id===story.id):null,p=active?storyProgress(active.id):null;
 const badges=[['Portfolio presenter',thesisPortfolios().length>0],['Source scout',storyCatalog.some(s=>storyProgress(s.id).sources.length)],['Link examiner',storyCatalog.some(s=>storyProgress(s.id).connections.length)],['Story explorer',complete.length>0],['Evidence interpreter',storyProgress('relief').solved.length===4],['Case builder',filedCases().length>0],['1816 Investigator',expeditionFinished()],['Draft contributor',storyCatalog.some(s=>storyProgress(s.id).draft)],['Claim challenger',investigationProgress.challenges.includes('causation')],['Comparative investigator',investigationProgress.challenges.includes('comparison')]];
 const wasOpen=root.querySelector('details')?.open;
 root.innerHTML=`<div class="progress-summary"><span><strong>${points} investigation points</strong> · ${rank}</span><span>${filedCases().length}/${storyCatalog.length} case files earned</span></div>${active?`<p class="trail-status">${completedStory(active)?'✓ Story investigated · completion reward earned':`This trail: ${new Set(p.visited).size}/${(active.chapters||storyChapters).length} scenes · ${p.sources.length?'✓':'○'} source expanded · ${p.connections.length?'✓':'○'} connection examined`}</p>`:''}<details ${wasOpen?'open':''}><summary>Your field journal · ${badges.filter(([,earned])=>earned).length} badges earned</summary><p>Points recognise recorded activities, not historical truth or the quality of a proposal. Each milestone earns once per story.</p><div class="earned-badges">${badges.map(([name,earned])=>`<span class="${earned?'earned':'locked'}">${earned?'✓':'○'} ${name}</span>`).join('')}</div>${active?`<h3>This story’s trail</h3><ul class="milestone-list"><li>${new Set(p.visited).size}/${(active.chapters||storyChapters).length} scenes visited · 5 points each</li><li>${p.sources.length?'✓':'○'} Expand a source · 20 points</li><li>${p.connections.length?'✓':'○'} Open a connection explanation · 20 points</li>${!active.chapters?`<li>${p.choice?'✓':'○'} Choose a working hypothesis · 10 points</li>`:''}<li>${completedStory(active)?'✓':'○'} Visit every scene and inspect a source and connection · 30 points</li>${active.id==='relief'?`<li>${p.solved.length}/4 evidence interpretations · 20 points each</li>`:''}<li>${p.draft?'✓':'○'} Save a sourced draft · 15 points (unreviewed)</li></ul>`:''}<p>${filedCases().length?'Claim challenge unlocked: return to Choose a story to try it.':'Build a completed case file to unlock the claim challenge.'} ${filedCases().length===storyCatalog.length?'Cross-story comparison is also unlocked.':''}</p><p>${progressStored?'Progress is saved in this browser; it does not sync between devices.':'Browser storage is unavailable. Progress lasts only for this page session.'}</p></details>`;
}
const investigationChallenges=[
 {id:'causation',title:'Claim challenge',requirement:'Earn one case file to unlock',question:'An army crossed the Andes, then won a battle. What does that sequence alone establish?',options:['Crossing the mountains caused the victory.','The crossing preceded the battle; its causal contribution needs other evidence.','The later victory proves all supplies arrived.'],answer:1,explanation:'Chronology establishes order. A causal account also needs mechanisms, evidence and competing explanations.'},
 {id:'comparison',title:'Compare across stories',requirement:'Earn all three case files to unlock',question:'Good Korean harvest reports and a Dutch relief decree are different kinds of evidence. Which comparison respects their limits?',options:['Both prove households had enough food.','The decree proves Dutch relief worked better.','Neither alone establishes who could obtain food; household access needs separate evidence.'],answer:2,explanation:'An aggregate harvest report and a policy authorization do not establish household access or relief effectiveness.'}
];
function challengesHtml(){const complete=filedCases();return `<details class="challenge-shelf"><summary>Unlock new investigations · ${complete.length?1:0}${complete.length===storyCatalog.length?' + 1':''} available</summary><div class="challenge-cards">${investigationChallenges.map(c=>{const unlocked=c.id==='causation'?complete.length>0:complete.length===storyCatalog.length;return `<button data-investigation-challenge="${c.id}" ${unlocked?'':'disabled'}><strong>${c.title}</strong><span>${investigationProgress.challenges.includes(c.id)?'✓ Earned · revisit':unlocked?'Unlocked · earn 40 points':c.requirement}</span></button>`;}).join('')}</div></details>`;}
function openChallenge(id){const c=investigationChallenges.find(c=>c.id===id),complete=filedCases();if(!c||(id==='causation'?complete.length<1:complete.length!==storyCatalog.length))return;
 document.getElementById('storyJourney').innerHTML=`<button class="story-link" data-story-home>← Choose a story</button><article class="story-scene"><p class="eyebrow">Unlocked investigation · 40 points once</p><h1 id="storyHeading" tabindex="-1">${c.title}</h1><p class="story-narrative">${c.question}</p><div class="story-choices">${c.options.map((option,i)=>`<button data-challenge-answer="${id}" data-answer="${i}">${option}</button>`).join('')}</div><p id="challengeFeedback" role="status"></p></article>`;document.getElementById('storyHeading').focus();
}
function answerChallenge(id,answer){const c=investigationChallenges.find(c=>c.id===id);if(!c)return;const correct=answer===c.answer;document.getElementById('challengeFeedback').textContent=correct?`${c.explanation} ${investigationProgress.challenges.includes(id)?'You already earned this badge.':'Badge earned · 40 investigation points.'}`:'That goes beyond what these records establish. Look for the answer that separates the evidence from the inference, then try again.';
 if(correct&&!investigationProgress.challenges.includes(id)){investigationProgress.challenges.push(id);persistProgress();renderProgress();}
}

function sourceBelongsToStory(id){
 const config=storyCatalog.find(s=>s.id===story.id);if(!config||document.getElementById('storyJourney').hidden)return false;
 const recordRefs=config.records.filter(Boolean).flatMap(id=>obs(id)?.sourceRefs||[]);
 const claimRefs=(config.chapters||storyChapters).filter(c=>c.claim).flatMap(c=>state.relationships.find(r=>r.id===c.claim)?.sourceRefs||[]);
 return [...recordRefs,...claimRefs].includes(id);
}

function connectionBelongsToStory(id){
 const config=storyCatalog.find(s=>s.id===story.id);if(!config||document.getElementById('storyJourney').hidden)return false;
 const r=state.relationships.find(r=>r.id===id);return !!r&&((config.chapters||storyChapters).some(c=>c.claim===id)||(config.records.includes(r.subjectId)&&config.records.includes(r.objectId)));
}
