const LOCAL_RESEARCH_KEY='worldthreads-local-research-v1';
function localFindings(){try{const x=JSON.parse(localStorage.getItem(LOCAL_RESEARCH_KEY)||'[]');return Array.isArray(x)?x.filter(v=>v&&typeof v.id==='string'&&typeof v.claim==='string'&&typeof v.url==='string'):[];}catch{return [];}}
function thesisRecord(id){return obs(id)||localFindings().find(x=>x.id===id);}
function validThread(id){return state.threads.some(t=>t.id===id);}
function canUseThesis(){return expeditionFinished()||filedCases().length>0||validThread(readThesisDraft().threadId)||!!historicalObject(readThesisDraft().objectId);}
function startThreadThesis(id){const thread=state.threads.find(t=>t.id===id);if(!thread)return;const existing=readThesisDraft();const previous=existing.threadId||existing.objectId;if(previous&&previous!==id){try{localStorage.setItem(THESIS_KEY+'-archive-'+previous,JSON.stringify(existing));}catch{}}
 let draft=existing.threadId===id?existing:{};try{if(!Object.keys(draft).length)draft=JSON.parse(localStorage.getItem(THESIS_KEY+'-archive-'+id)||'{}');}catch{draft={};}
 draft={...draft,threadId:id,objectId:null,title:draft.title||thread.title,question:draft.question||'How far does the available evidence support this thread’s proposed explanation?',argument:draft.argument||'',status:'Unreviewed research draft'};
 for(let i=0;i<3;i++)if(!draft['record'+i])draft['record'+i]=thread.nodeIds[i]||'';
 try{localStorage.setItem(THESIS_KEY,JSON.stringify(draft));}catch{}
 story.id=null;setExperience('story');openThesisWorkspace(draft);
}
function researchHtml(draft){const thread=state.threads.find(t=>t.id===draft.threadId);const findings=localFindings().filter(x=>draft.objectId?x.objectId===draft.objectId:!thread||x.threadId===thread.id);return `<details class="research-loop"><summary>Research a dead end, then extend your local corpus</summary><p>1. Name the unsupported link. 2. Identify the source that could test it. 3. Check creator, date, place, purpose and passage. 4. Record supporting and conflicting evidence. 5. Import a sourced proposal and revise your thesis.</p><label>Open question / missing link<textarea form="thesisForm" name="researchQuestion" maxlength="4000">${escapeHtml(draft.researchQuestion||'')}</textarea></label><label>Source to seek and what it would establish<textarea form="thesisForm" name="researchSource" maxlength="4000">${escapeHtml(draft.researchSource||'')}</textarea></label><label>Search, archive or bibliography leads and next steps<textarea form="thesisForm" name="researchPlan" maxlength="4000">${escapeHtml(draft.researchPlan||'')}</textarea></label><p>Keep the question open if the source is unavailable, contradictory or too indirect. Revise the scope or claim instead of filling the gap with an assumption.</p><label>Import a sourced finding (downloaded proposal JSON)<input id="researchImport" type="file" accept=".json,application/json"></label><p id="researchImportStatus" role="status"></p><p>Imported entries remain unreviewed and local to this browser. They can be cited as candidate evidence in a draft, but do not change the registered historical graph.</p><h3>Local additions · ${findings.length}</h3>${findings.map(x=>`<article class="local-finding"><p class="eyebrow">Unreviewed ${escapeHtml(x.kind)}</p><p>${escapeHtml(x.claim)}</p><p>${escapeHtml(x.datePlace)} · ${escapeHtml(x.locator)}</p><p>Limits: ${escapeHtml(x.limits)}</p><a href="${escapeAttr(x.url)}" target="_blank" rel="noreferrer">Inspect supplied source ↗</a></article>`).join('')||'<p>No local additions for this thesis yet.</p>'}</details>`;}
async function importResearch(file){const status=document.getElementById('researchImportStatus');if(!file)return;if(file.size>1000000){status.textContent='Import rejected: use a proposal JSON file smaller than 1 MB.';return;}
 try{const proposal=JSON.parse(await file.text());for(const key of ['claim','url','locator','datePlace','limits'])if(typeof proposal[key]!=='string'||!proposal[key].trim()||proposal[key].length>10000)throw Error('Missing or invalid '+key);const url=new URL(proposal.url);if(!['https:','http:'].includes(url.protocol))throw Error('Source URL must use http or https');const draft=readThesisDraft(),threadId=validThread(draft.threadId)?draft.threadId:validThread(proposal.threadId)?proposal.threadId:null,objectId=historicalObject(draft.objectId)?draft.objectId:null;if(!validThread(threadId)&&!objectId)throw Error('Start from a registered thread or object before importing');
 const values=localFindings();if(values.some(x=>x.url===url.href&&x.locator===proposal.locator.trim()&&x.claim===proposal.claim.trim())){status.textContent='This finding is already in the local corpus. No duplicate added.';return;}
 const kind=['Observation','Contributing connection','Association','Challenge to an existing claim'].includes(proposal.kind)?proposal.kind:'Observation';const addition={id:'LOCAL-'+Date.now()+'-'+Math.random().toString(36).slice(2,7),threadId,objectId,claim:proposal.claim.trim(),url:url.href,locator:proposal.locator.trim(),datePlace:proposal.datePlace.trim(),limits:proposal.limits.trim(),kind,reviewStatus:'Unreviewed',importedAt:new Date().toISOString()};
 localStorage.setItem(LOCAL_RESEARCH_KEY,JSON.stringify([...values,addition]));
 const container=document.createElement('div');container.innerHTML=`<option value="${addition.id}">Unreviewed: ${escapeHtml(addition.claim.slice(0,90))}</option>`;document.querySelectorAll('[data-thesis-record]').forEach(select=>select.appendChild(container.firstElementChild.cloneNode(true)));
 status.textContent='Imported into your local corpus as unreviewed. Select it in the evidence table, inspect its source and record how it changes—or fails to change—your argument.';
 }catch(e){status.textContent='Import rejected: '+e.message+'. The registered corpus is unchanged.';}
}
function startObjectResearch(id){const object=historicalObject(id);if(!object)return;const existing=readThesisDraft(),previous=existing.threadId||existing.objectId;if(previous&&previous!==id){try{localStorage.setItem(THESIS_KEY+'-archive-'+previous,JSON.stringify(existing));}catch{}}
 let draft=existing.objectId===id?existing:{};try{if(!Object.keys(draft).length)draft=JSON.parse(localStorage.getItem(THESIS_KEY+'-archive-'+id)||'{}');}catch{draft={};}
 draft={...draft,objectId:id,threadId:null,title:draft.title||object.label+' · influence investigation',question:draft.question||'What shaped '+object.label+', and what changes can the evidence attribute to it?',argument:draft.argument||'',status:'Unreviewed research draft'};for(let i=0;i<3;i++)if(!draft['record'+i])draft['record'+i]=object.observationIds[i]||'';
 try{localStorage.setItem(THESIS_KEY,JSON.stringify(draft));}catch{}story.id=null;document.getElementById('detailDialog').close();setExperience('story');openThesisWorkspace(draft);
}
