const LOCAL_RESEARCH_KEY='worldthreads-local-research-v1';
function validLocalFinding(v){if(!v||typeof v!=='object'||Array.isArray(v))return false;if(typeof v.id!=='string'||!/^LOCAL-[A-Za-z0-9-]+$/.test(v.id))return false;if(!['id','claim','url','locator','datePlace','limits'].every(k=>typeof v[k]==='string'&&v[k].trim()&&v[k].length<=10000))return false;try{const url=new URL(v.url);return ['https:','http:'].includes(url.protocol)&&!url.username&&!url.password&&v.reviewStatus==='Unreviewed';}catch{return false;}}
function localFindings(){try{const x=JSON.parse(localStorage.getItem(LOCAL_RESEARCH_KEY)||'[]');return Array.isArray(x)?x.filter(validLocalFinding).map(v=>({...v,contexts:Array.isArray(v.contexts)?v.contexts.filter(x=>typeof x==='string'):[],kind:typeof v.kind==='string'?v.kind:'Observation'})):[];}catch{return [];}}

function findingBelongsToDraft(finding,draft){const context=draft.objectId||draft.threadId;return !context||(finding.contexts||[]).includes(context)||(finding.objectId||finding.threadId)===context;}
function findingsForDraft(draft){return localFindings().filter(x=>findingBelongsToDraft(x,draft));}
function thesisRecord(id){return obs(id)||localFindings().find(x=>x.id===id&&!x.excludedAt);}
function validThread(id){return state.threads.some(t=>t.id===id);}
function canUseThesis(){return expeditionFinished()||filedCases().length>0||validThread(readThesisDraft().threadId)||!!historicalObject(readThesisDraft().objectId);}
function startThreadThesis(id){const thread=state.threads.find(t=>t.id===id);if(!thread)return;const existing=readThesisDraft();const previous=existing.threadId||existing.objectId;if(previous&&previous!==id){if(!archiveCurrentDraft(previous)){setExperience('story');openThesisWorkspace(existing);document.getElementById('thesisStatus').textContent='Previous investigation could not be archived. Your current work remains here; download it and resolve the storage problem or tab conflict before switching investigations.';return;}}
 let draft=existing.threadId===id?existing:{};if(!Object.keys(draft).length)draft=readArchivedDraft(id);
 draft={...draft,threadId:id,objectId:null,title:draft.title||thread.title,question:draft.question||'How far does the available evidence support this thread’s proposed explanation?',argument:draft.argument||'',status:'Unreviewed research draft'};
 const learningCase=storyCatalog.find(s=>s.thread===id&&storyProgress(s.id).caseFiled),task=learningCase&&caseFileTasks[learningCase.id];
 const seeds=task?[...task.required,...thread.nodeIds.filter(n=>!task.required.includes(n))]:thread.nodeIds;
 if(!draft.savedAt)for(let i=0;i<3;i++)if(!draft['record'+i])draft['record'+i]=seeds[i]||'';
 if(task){if(!draft.savedAt&&draft.question==='How far does the available evidence support this thread’s proposed explanation?')draft.question=learningCase.question;draft.researchQuestion=draft.researchQuestion||learningCase.question;draft.researchSource=draft.researchSource||task.next[0];draft.caseLimit=draft.caseLimit||task.limits[0];}

 activateDraft(draft);
 story.id=null;setExperience('story');openThesisWorkspace(draft);
}
function researchHtml(draft){const findings=findingsForDraft(draft);return `<details id="researchDesk" class="research-loop"><summary>Research a dead end, then extend your local corpus</summary><p>1. Name the unsupported link. 2. Identify the source that could test it. 3. Check creator, date, place, purpose and passage. 4. Record supporting and conflicting evidence. 5. Import a sourced proposal and revise your thesis.</p><label>Open question / missing link<textarea form="thesisForm" name="researchQuestion" maxlength="4000">${escapeHtml(draft.researchQuestion||'')}</textarea></label><label>Source to seek and what it would establish<textarea form="thesisForm" name="researchSource" maxlength="4000">${escapeHtml(draft.researchSource||'')}</textarea></label><label>Search, archive or bibliography leads and next steps<textarea form="thesisForm" name="researchPlan" maxlength="4000">${escapeHtml(draft.researchPlan||'')}</textarea></label><p>Keep the question open if the source is unavailable, contradictory or too indirect. Revise the scope or claim instead of filling the gap with an assumption.</p>${aiResearchHtml(draft)}<label>Import a sourced finding (downloaded proposal JSON)<input id="researchImport" type="file" accept=".json,application/json"></label><p id="researchImportStatus" role="status"></p><p>Imported entries remain unreviewed and local to this browser. They can be cited as candidate evidence in a draft, but do not change the registered historical graph.</p><div id="researchFindings">${researchFindingsHtml(findings)}</div></details>`;}
async function importResearch(file){const status=document.getElementById('researchImportStatus');if(!file)return;if(file.size>1000000){status.textContent='Import rejected: use a proposal JSON file smaller than 1 MB.';return;}
 try{const proposal=JSON.parse(await file.text());if(!proposal||typeof proposal!=='object'||Array.isArray(proposal))throw Error('Use one proposal JSON object');for(const key of ['claim','url','locator','datePlace','limits'])if(typeof proposal[key]!=='string'||!proposal[key].trim()||proposal[key].length>10000)throw Error('Missing or invalid '+key);const url=new URL(proposal.url);if(!['https:','http:'].includes(url.protocol))throw Error('Source URL must use http or https');if(url.username||url.password)throw Error('Source URL must not contain login credentials');const draft=readThesisDraft(),threadId=validThread(draft.threadId)?draft.threadId:validThread(proposal.threadId)?proposal.threadId:null,objectId=historicalObject(draft.objectId)?draft.objectId:null;if(!validThread(threadId)&&!objectId)throw Error('Start from a registered thread or object before importing');
 const values=localFindings(),existing=values.find(x=>x.url===url.href&&x.locator===proposal.locator.trim()&&x.claim===proposal.claim.trim());if(existing){if(findingBelongsToDraft(existing,draft)){status.textContent='This finding is already in the local corpus for this investigation. No duplicate added.';return;}existing.contexts=[...new Set([...(existing.contexts||[]),existing.objectId||existing.threadId,objectId||threadId].filter(Boolean))];localStorage.setItem(LOCAL_RESEARCH_KEY,JSON.stringify(values));addFindingOptions(existing);renderResearchFindings();status.textContent='Existing finding linked to this investigation as unreviewed. No duplicate evidence created; inspect its relevance before assigning a role.';return;}
 const kind=['Observation','Contributing connection','Association','Challenge to an existing claim'].includes(proposal.kind)?proposal.kind:'Observation';const addition={id:'LOCAL-'+Date.now()+'-'+Math.random().toString(36).slice(2,7),threadId,objectId,contexts:[objectId||threadId],claim:proposal.claim.trim(),url:url.href,locator:proposal.locator.trim(),datePlace:proposal.datePlace.trim(),limits:proposal.limits.trim(),kind,reviewStatus:'Unreviewed',importedAt:new Date().toISOString()};
 localStorage.setItem(LOCAL_RESEARCH_KEY,JSON.stringify([...values,addition]));
 addFindingOptions(addition);
 renderResearchFindings();
 status.textContent='Imported into your local corpus as unreviewed. Select it in the evidence table, inspect its source and record how it changes—or fails to change—your argument.';
 }catch(e){status.textContent='Import rejected: '+(e instanceof SyntaxError?'Paste one JSON object with claim, url, locator, datePlace and limits; prose answers and code fences cannot be imported':e.message)+'. The registered corpus is unchanged.';}
}
function startObjectResearch(id){const object=historicalObject(id);if(!object)return;const existing=readThesisDraft(),previous=existing.threadId||existing.objectId;if(previous&&previous!==id){if(!archiveCurrentDraft(previous)){setExperience('story');openThesisWorkspace(existing);document.getElementById('thesisStatus').textContent='Previous investigation could not be archived. Your current work remains here; download it and resolve the storage problem or tab conflict before switching investigations.';return;}}
 let draft=existing.objectId===id?existing:{};if(!Object.keys(draft).length)draft=readArchivedDraft(id);
 draft={...draft,objectId:id,threadId:null,title:draft.title||object.label+' · influence investigation',question:draft.question||'What shaped '+object.label+', and what changes can the evidence attribute to it?',argument:draft.argument||'',status:'Unreviewed research draft'};if(!draft.savedAt)for(let i=0;i<3;i++)if(!draft['record'+i])draft['record'+i]=object.observationIds[i]||'';
 activateDraft(draft);story.id=null;document.getElementById('detailDialog').close();setExperience('story');openThesisWorkspace(draft);
}

function aiResearchHtml(draft){return `<details><summary>Take this question to an AI research assistant</summary><p>The assistant helps find sources and competing explanations. You inspect the original source, then decide what the finding means here.</p><button type="button" class="story-link" data-build-ai-brief>Prepare my research brief</button><label>Copy this brief into your preferred AI assistant<textarea id="aiResearchBrief" readonly rows="10"></textarea></label><p>This sends nothing automatically. The brief includes your current thesis and research question. Review it before sharing.</p><label>Bring back one sourced candidate (paste the assistant’s JSON)<textarea id="aiResearchReturn" form="thesisForm" name="aiCandidateReturn" maxlength="50000" rows="7" placeholder='{"claim": "…", "url": "https://…", "locator": "…", "datePlace": "…", "limits": "…"}'>${escapeHtml(draft.aiCandidateReturn||'')}</textarea></label><button type="button" class="story-link" data-import-ai-return>Add as unreviewed evidence</button><p>A valid format cannot verify a citation. Open the original source, find the passage, check its date and scope, and classify it on your evidence board. Missing sources remain research leads, not imported facts. No points are awarded for importing an answer.</p></details>`;}
function aiResearchBrief(draft){return `WORLDTHREADS RESEARCH BRIEF
WorldThreads is a single-player historical investigation of 1816. Players move from stories and historical objects to provisional thesis arguments, source checks and revisions. Progress measures research practice, never factual truth.
Model: Source (provenance and citation) → Observation (what the source records, date/place, limitations) → Relationship (a sourced link, with association distinguished from causal inference) → Thread (an explanatory path to test) → Mechanism (the proposed process explaining change). People, places, inventions, movements and events are entry points; a linked object is not automatically a cause.
Your job is to investigate the missing link, challenge the player’s premise and supply traceable research candidates. Do not assume the curated thread or player’s argument is correct. Imported candidates remain local and unreviewed; no graph relationship is accepted automatically.
Help me investigate a historical thesis, without filling gaps with invented facts.
Topic: ${draft.title||'[Unspecified]'}
Current argument: ${draft.argument||'[Not drafted]'}
Open question: ${draft.researchQuestion||draft.question||'[Not drafted]'}
Source sought: ${draft.researchSource||'[Not specified]'}
Research leads: ${draft.researchPlan||'[None yet]'}
Current evidence context (registered summaries are not original-source verification):
${JSON.stringify(Array.from({length:3},(_,i)=>thesisRecord(draft['record'+i])).filter(Boolean).map(o=>({id:o.id,claim:o.observation||o.claim,date:o.startDate||o.datePlace,place:o.place,limits:o.uncertainty||o.limits,status:o.reviewStatus||'Registered observation',sources:o.url?[{url:o.url,locator:o.locator}]:(o.sourceRefs||[]).map(source).filter(Boolean).map(s=>({title:s.title,creator:s.authorOrOrg,year:s.year,url:s.url,limits:s.notes}))})),null,2)}
Find supporting AND conflicting primary evidence. Distinguish observation, association and causal inference. For each source supply its creator, date, purpose, URL and exact page/section/passage locator. Say whether you accessed the original or only a citation; never fabricate a quotation or locator. Explain uncertainty and what the source cannot establish. If unavailable, return a research lead and say the question remains open.
For ONE candidate grounded in an accessible source, return a plain JSON object (no code fences) with these string fields: claim, url, locator, datePlace, limits; optional kind: Observation, Contributing connection, Association, or Challenge to an existing claim. Keep the main claim tied to the principal URL. Return separate candidates for claims from different documents; comparisons and unresolved disagreements belong in limits. Include access limitations in limits. Do not return a candidate if you cannot identify its source and locator. This will be imported as unreviewed, not as established history.`;}
document.addEventListener('click',e=>{if(e.target.closest('[data-build-ai-brief]')){saveThesisDraft({target:document.getElementById('thesisForm'),preventDefault(){}});document.getElementById('aiResearchBrief').value=aiResearchBrief(readThesisDraft());}if(e.target.closest('[data-import-ai-return]')){const text=document.getElementById('aiResearchReturn').value;importResearch(new File([text],'ai-candidate.json',{type:'application/json'}));}});

function researchFindingsHtml(findings){return `<h3>Local additions · ${findings.length}</h3>${findings.map(x=>`<article class="local-finding"><p class="eyebrow">${x.excludedAt?'Excluded research lead · source not verified':'Unreviewed '+escapeHtml(x.kind)}</p><p>${escapeHtml(x.claim)}</p><details class="candidate-review"><summary>Source, scope and review this candidate</summary><p>${escapeHtml(x.datePlace)} · ${escapeHtml(x.locator)}</p><p>Limits: ${escapeHtml(x.limits)}</p><a href="${escapeAttr(x.url)}" target="_blank" rel="noreferrer">Inspect supplied source ↗</a>${x.excludedAt?`<p>Reason for exclusion: ${escapeHtml(x.exclusionReason)}</p><button type="button" class="story-back" data-restore-finding="${escapeAttr(x.id)}">Restore as unreviewed candidate</button>`:`<label>Why should this candidate be excluded?<textarea data-exclusion-reason="${escapeAttr(x.id)}" maxlength="4000" placeholder="For example: source cannot be located, passage does not support the claim, or outside the scope."></textarea></label><button type="button" class="story-back" data-exclude-finding="${escapeAttr(x.id)}">Exclude from usable evidence</button>`}</details></article>`).join('')||'<p>No local additions for this thesis yet.</p>'}`;}
function renderResearchFindings(){const draft=readThesisDraft(),root=document.getElementById("researchFindings");if(!root)return;const findings=findingsForDraft(draft);root.innerHTML=researchFindingsHtml(findings);}

function addFindingOptions(addition){document.querySelectorAll('[data-thesis-record]').forEach(select=>{if([...select.options].some(o=>o.value===addition.id))return;const option=document.createElement('option');option.value=addition.id;option.textContent='Unreviewed: '+addition.claim.slice(0,90);select.appendChild(option);});}

document.addEventListener('click',e=>{const button=e.target.closest('[data-exclude-finding],[data-restore-finding]');if(!button)return;const id=button.dataset.excludeFinding||button.dataset.restoreFinding,values=localFindings(),finding=values.find(x=>x.id===id),status=document.getElementById('researchImportStatus');if(!finding)return;
 if(button.dataset.excludeFinding){const reason=button.closest('article').querySelector('textarea').value.trim();if(!reason){status.textContent='State why you are excluding this candidate. Its source has not been verified.';return;}finding.excludedAt=new Date().toISOString();finding.exclusionReason=reason;}else{delete finding.excludedAt;delete finding.exclusionReason;}
 try{localStorage.setItem(LOCAL_RESEARCH_KEY,JSON.stringify(values));document.querySelectorAll('[data-thesis-record] option').forEach(o=>{if(o.value===id)o.textContent=(finding.excludedAt?'Excluded: ':'Unreviewed: ')+finding.claim.slice(0,90);});for(let i=0;i<3;i++)showThesisRecord(i,readThesisDraft()['record'+i]);renderResearchFindings();renderArgumentBoard(readThesisDraft(),true);renderPortfolio(readThesisDraft());renderExaminerHistory(readThesisDraft());status.textContent=finding.excludedAt?'Candidate excluded from usable evidence. The research lead and reason remain recorded; replace it or leave the claim unresolved.':'Candidate restored as unreviewed. Verify the original source before using it.';}catch{status.textContent='The candidate decision could not be saved. Nothing was changed.';}
});
