const THESIS_KEY='worldthreads-thesis-draft-v1';
const thesisFields=[['title','Working title'],['question','Research question and why it matters'],['argument','Provisional thesis: your arguable answer'],['historiography','Existing scholarship: what you build on, challenge or leave unresolved'],['scope','Scope: places, dates and populations'],['method','Method: source types, provenance, selection and comparison limits'],['counterargument','Strongest counterargument or contrary evidence'],['response','Your response: revise, qualify or defend the thesis'],['revision','What evidence would make you change your thesis?'],['chapters','Chapter plan: the claim and evidence each chapter contributes'],['schedule','Research and writing plan: archives, tasks and revision stages']];
function readThesisDraft(){try{const p=JSON.parse(localStorage.getItem(THESIS_KEY)||'null');return p&&typeof p==='object'&&!Array.isArray(p)?p:{};}catch{return {};}}
function openThesisWorkspace(){if(!expeditionFinished())return;story.id=null;renderProgress();const draft=readThesisDraft();
 const field=(name,label)=>`<label>${escapeHtml(label)}<textarea name="${name}" maxlength="8000">${escapeHtml(draft[name]||'')}</textarea></label>`;
 const rows=Array.from({length:3},(_,i)=>`<fieldset class="thesis-evidence-row"><legend>Evidence entry ${i+1}</legend><label>Recorded observation<select name="record${i}" data-thesis-record="${i}"><option value="">Choose a record</option>${state.observations.map(o=>`<option value="${o.id}" ${draft['record'+i]===o.id?'selected':''}>${escapeHtml(o.title)} · ${escapeHtml(o.place)}</option>`).join('')}</select></label><div id="thesisRecord${i}"></div><label>Your subclaim and how this record supports, complicates or challenges it<textarea name="claim${i}" maxlength="4000">${escapeHtml(draft['claim'+i]||'')}</textarea></label><label>Source page, passage or archival reference you checked<input name="locator${i}" maxlength="1500" value="${escapeAttr(draft['locator'+i]||'')}"></label></fieldset>`).join('');
 document.getElementById('storyJourney').innerHTML=`<button class="story-link" data-story-home>← Expedition board</button><article class="thesis-workspace"><p class="eyebrow">Unlocked tool · from cases to an argument</p><h1 id="storyHeading" tabindex="-1">Build a thesis, not a collection of facts.</h1><p>Write your own provisional argument. Link each subclaim to evidence, confront the strongest objection and plan the chapters that would establish your case. This exports a research draft, not a verified dissertation.</p><form id="thesisForm"><details open><summary>1. Frame the question and argument</summary>${thesisFields.slice(0,4).map(([n,l])=>field(n,l)).join('')}</details><details><summary>2. Define scope and method</summary>${thesisFields.slice(4,6).map(([n,l])=>field(n,l)).join('')}</details><details><summary>3. Build a claim–evidence table</summary><p>Keep the recorded observation separate from your inference. Citations below come from the registered sources; identify the actual passage you checked.</p>${rows}</details><details><summary>4. Test the argument and plan the document</summary>${thesisFields.slice(6).map(([n,l])=>field(n,l)).join('')}</details><button class="story-next" type="submit">Save my research draft locally</button></form><p id="thesisStatus" role="status">${draft.savedAt?'A local draft is available. Edit it and save before exporting.':'Drafts stay in this browser. Nothing is submitted or added to the evidence graph.'}</p><button class="story-back" data-download-thesis ${draft.savedAt?'':'disabled'}>Download the saved thesis draft</button><p class="story-footnote">Workflow informed by <a href="https://history.fas.harvard.edu/graduate-program-dissertation-prospectus" target="_blank" rel="noreferrer">Harvard History’s dissertation prospectus guidance</a>. Field completion does not assess originality, source interpretation or scholarly validity.</p></article>`;
 for(let i=0;i<3;i++)showThesisRecord(i,draft['record'+i]);document.getElementById('storyHeading').focus();
}
function showThesisRecord(i,id){const o=obs(id),root=document.getElementById('thesisRecord'+i);if(!root)return;root.innerHTML=o?`<div class="thesis-record-summary"><p><strong>Recorded observation:</strong> ${escapeHtml(o.observation)}</p><small>${escapeHtml(evidenceClass(o))} · ${escapeHtml(o.uncertainty||'Check the source-specific scope and limits.')}</small><button type="button" class="story-link" data-story-evidence="${o.id}">Inspect evidence and sources ↗</button></div>`:'';}
function saveThesisDraft(e){if(e.target.id!=='thesisForm')return;e.preventDefault();if(!expeditionFinished())return;const values=Object.fromEntries(new FormData(e.target));values.savedAt=new Date().toISOString();values.status='Unreviewed research draft';try{localStorage.setItem(THESIS_KEY,JSON.stringify(values));const filled=thesisFields.filter(([key])=>String(values[key]||'').trim()).length;document.getElementById('thesisStatus').textContent=`Draft saved locally: ${filled}/${thesisFields.length} planning fields filled. This counts structure, not argument quality. Nothing was submitted.`;document.querySelector('[data-download-thesis]').disabled=false;}catch{document.getElementById('thesisStatus').textContent='Browser storage is unavailable. The draft could not be saved.';}}
function downloadThesisDraft(){if(!expeditionFinished())return;const d=readThesisDraft();if(!d.savedAt)return;const value=k=>String(d[k]||'').trim()||'[Not yet drafted]';const chosen=Array.from({length:3},(_,i)=>({o:obs(d['record'+i]),claim:value('claim'+i),locator:value('locator'+i)}));const refs=[...new Set(chosen.filter(x=>x.o).flatMap(x=>x.o.sourceRefs))].map(source).filter(Boolean);
 let text=`# ${value('title')}\n\nStatus: unreviewed research draft. Registered observations and sources are distinguished from the writer’s arguments.\n\n`;
 for(const [key,label] of thesisFields.slice(1,6))text+=`## ${label}\n\n${value(key)}\n\n`;
 text+='## Claim–evidence table\n\n';for(let i=0;i<chosen.length;i++){const {o,claim,locator}=chosen[i];text+=`### Entry ${i+1}\n\nWriter’s subclaim and interpretation: ${claim}\n\nRecorded observation: ${o?o.observation:'[No record selected]'}\n\nRecord: ${o?o.id+' · '+o.title+' · '+o.place+' · '+o.startDate:'[Not selected]'}\n\nEvidence basis: ${o?o.evidenceType.join('; '):'[Not selected]'}\n\nRecord limits: ${o?.uncertainty||'[Consult source-specific limitations]'}\n\nPassage checked by writer: ${locator}\n\nRegistered source references: ${o?o.sourceRefs.join(', '):'[None selected]'}\n\n`;}
 for(const [key,label] of thesisFields.slice(6))text+=`## ${label}\n\n${value(key)}\n\n`;
 text+='## Bibliography from selected records\n\n'+refs.map(s=>`- ${s.authorOrOrg}. ${s.title}. ${s.year??'Undated'}. Type: ${s.type}. Reference: ${s.id}. ${s.url}`).join('\n')+'\n\n## Further work\n\nVerify cited passages, evaluate source provenance, expand primary-source research and relevant scholarship, revise the argument, and apply the required citation style. This is a draft plan, not an independently reviewed thesis.\n';
 const url=URL.createObjectURL(new Blob([text],{type:'text/markdown'}));const a=document.createElement('a');a.href=url;a.download='worldthreads-thesis-draft.md';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);
}
