const {chromium}=require('playwright');const assert=require('node:assert/strict');const fs=require('node:fs');
const url=process.env.WORLDTHREADS_URL||'http://127.0.0.1:8765';
const key='worldthreads-thesis-draft-v1';
(async()=>{const browser=await chromium.launch({headless:true});try{
const context=await browser.newContext({acceptDownloads:true}),page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(url);await page.click('#researchMode');await page.selectOption('#threadSelect','THREAD-BRAZIL-PATRONAGE');await page.click('#threadThesis');await page.fill('[name=argument]','Earlier saved argument');
await page.evaluate(()=>{window.originalSet=Storage.prototype.setItem;Storage.prototype.setItem=function(k,v){if(k==='worldthreads-thesis-draft-v1')throw new DOMException('Quota full','QuotaExceededError');return originalSet.call(this,k,v);};});
await page.fill('[name=argument]','Current argument after failed save');await page.click('[data-thesis-stage=present]');await page.click('[data-file-portfolio]');assert.match(await page.locator('#portfolioStatus').innerText(),/not filed.*sav|save.*failed|not saved/i);
const event=page.waitForEvent('download');await page.click('[data-download-thesis]');const text=fs.readFileSync(await(await event).path(),'utf8');assert(text.includes('Current argument after failed save'));assert(!text.includes('Earlier saved argument'));assert.match(await page.locator('#thesisStatus').innerText(),/not saved|could not be saved|session/i);
await page.evaluate(()=>Storage.prototype.setItem=originalSet);await page.click('#thesisForm button[type=submit]');assert.equal(await page.evaluate(k=>JSON.parse(localStorage.getItem(k)).argument,key),'Current argument after failed save');
// The same browser profile has two independent pages with competing drafts.
const other=await context.newPage();other.on('pageerror',e=>errors.push(e.message));await other.goto(url);await other.getByRole('button',{name:'Resume my thesis →',exact:true}).click();await other.fill('[name=argument]','Argument from the other tab');
await page.locator('#draftRecovery').waitFor({state:'visible'});await page.click('[data-thesis-stage=topic]');await page.fill('[name=argument]','My competing argument');assert.equal(await page.evaluate(k=>JSON.parse(localStorage.getItem(k)).argument,key),'Argument from the other tab');assert.match(await page.locator('#draftRecovery').innerText(),/Another tab/);
const recovery=page.waitForEvent('download');await page.click('[data-recover-download]');assert(fs.readFileSync(await(await recovery).path(),'utf8').includes('My competing argument'));
await page.click('[data-use-other-draft]');assert.equal(await page.locator('[name=argument]').inputValue(),'Argument from the other tab');
await other.fill('[name=argument]','Second competing draft');await page.locator('#draftRecovery').waitFor({state:'visible'});await page.fill('[name=argument]','Deliberately keep this version');await page.click('[data-keep-this-draft]');assert.equal(await page.evaluate(k=>JSON.parse(localStorage.getItem(k)).argument,key),'Deliberately keep this version');await other.close();
// Archive failure must not erase the investigation being left.
await page.evaluate(()=>{window.originalSet=Storage.prototype.setItem;Storage.prototype.setItem=function(k,v){if(k.includes('-archive-'))throw new DOMException('Full','QuotaExceededError');return originalSet.call(this,k,v);};});await page.click('#researchMode');await page.selectOption('#threadSelect','THREAD-DUTCH-RELIEF');await page.click('#threadThesis');assert.equal(await page.locator('[name=argument]').inputValue(),'Deliberately keep this version');assert.match(await page.locator('#thesisStatus').innerText(),/could not be archived/);await page.evaluate(()=>Storage.prototype.setItem=originalSet);
// Corrupt each storage family: wrong shapes must not crash or grant a portfolio badge.
const broken=await browser.newContext();await broken.addInitScript(()=>{localStorage.setItem('worldthreads-thesis-draft-v1',JSON.stringify({threadId:'THREAD-BRAZIL-PATRONAGE',argument:['bad'],argumentRevisions:[null,7,{}]}));localStorage.setItem('worldthreads-thesis-portfolios-v1',JSON.stringify([{draft:7,records:[null],fingerprint:'bad'}]));localStorage.setItem('worldthreads-local-research-v1',JSON.stringify([{id:'LOCAL-bad',claim:'bad',url:'javascript:alert(1)',contexts:7}]));localStorage.setItem('worldthreads-thesis-draft-v1-archive-THREAD-DUTCH-RELIEF','null');});const corrupt=await broken.newPage();corrupt.on('pageerror',e=>errors.push(e.message));await corrupt.goto(url);await corrupt.getByRole('button',{name:'Resume my thesis →',exact:true}).click();assert.equal(await corrupt.locator('[name=argument]').inputValue(),'');assert((await corrupt.locator('.progress-summary').innerText()).includes('0 investigation points'));await corrupt.click('[data-thesis-stage=research]');assert((await corrupt.locator('#researchFindings').innerText()).includes('Local additions · 0'));await broken.close();
// All storage access denied: allow a session-only investigation and honest export.
const denied=await browser.newContext();await denied.addInitScript(()=>{Storage.prototype.getItem=function(){throw new DOMException('Denied','SecurityError');};Storage.prototype.setItem=function(){throw new DOMException('Denied','SecurityError');};});const session=await denied.newPage();session.on('pageerror',e=>errors.push(e.message));await session.goto(url);await session.click('#researchMode');await session.selectOption('#threadSelect','THREAD-BRAZIL-PATRONAGE');await session.click('#threadThesis');await session.fill('[name=argument]','Session-only work');assert.match(await session.locator('#draftRecovery').innerText(),/not saved/);const deniedDownload=session.waitForEvent('download');await session.click('[data-recover-download]');assert(fs.readFileSync(await(await deniedDownload).path(),'utf8').includes('Session-only work'));await denied.close();
assert.deepEqual(errors,[]);console.log('PASS: failed draft writes block filing, current unsaved draft remains downloadable, persistence recovers; conflicting tabs require explicit resolution; malformed storage and denied reads recover without crashes or false rewards.');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exit(1)});
