const {chromium}=require('playwright');
const assert=require('node:assert/strict');
(async()=>{
 const browser=await chromium.launch({headless:true});const page=await browser.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto(process.env.WORLDTHREADS_URL||'http://127.0.0.1:8765');await page.waitForFunction(()=>document.querySelectorAll('.card').length>0);

 assert(await page.locator('#storyJourney').isVisible());assert(!(await page.locator('#researchLibrary').isVisible()));
 await page.click('[data-story-step="1"]');await page.click('[data-story-evidence]');assert(await page.locator('.evidence-limits').isVisible());await page.click('#closeDialog');
 await page.click('[data-story-step="2"]');await page.click('[data-story-step="3"]');assert(await page.locator('.story-next').isDisabled());
 await page.click('[data-story-choice="universal"]');assert(!(await page.locator('.story-next').isDisabled()));await page.click('[data-story-step="4"]');assert((await page.locator('#storyHeading').innerText()).includes('Korea'));await page.click('[data-story-step="5"]');
 await page.click('[data-story-library]');assert(await page.locator('#researchLibrary').isVisible());assert.equal(await page.locator('#threadSelect').inputValue(),'THREAD-DUTCH-RELIEF');
 await page.selectOption('#threadSelect','THREAD-CENTRAL-EUROPE-FOOD');

 const data=await page.evaluate(async()=>({threads:await(await fetch('data/1816/threads.json')).json(),rels:await(await fetch('data/1816/relationships.json')).json(),obs:await(await fetch('data/1816/observations.json')).json()}));
 assert.equal(await page.locator('.card').count(),data.obs.length);assert.equal(Number(await page.locator('#statThreads').innerText()),data.threads.length);
 for(const t of data.threads){await page.selectOption('#threadSelect',t.id);assert.equal(await page.locator('.connection-row').count(),t.relationshipIds.length);for(let i=0;i<t.relationshipIds.length;i++){const r=data.rels.find(r=>r.id===t.relationshipIds[i]);const row=page.locator('.connection-row').nth(i);assert.equal(await row.locator('.thread-node').first().locator('strong').innerText(),data.obs.find(o=>o.id===r.subjectId).title);assert.equal(await row.locator('.thread-node').last().locator('strong').innerText(),data.obs.find(o=>o.id===r.objectId).title);await row.locator('.edge-label').click();assert.equal(await page.locator('.claim-endpoint').count(),2);assert.equal((await page.locator('.claim-reason p').textContent()).trim(),r.explanation.trim());assert.equal(await page.locator('.evidence-source[open]').count(),0);await page.click('#closeDialog');}}
 await page.selectOption('#regionSelect','Oceania');assert.equal(await page.locator('.card').count(),data.obs.filter(o=>o.continent==='Oceania').length);
 await page.locator('.card').first().press('Enter');const initialTitle=await page.locator('#detailTitle').innerText();await page.click('[data-inspector-tab="evidence"]');assert((await page.locator('#dialogContent').innerText()).includes('What this evidence can establish'));assert.equal(await page.locator('.evidence-source[open]').count(),0);await page.locator('.evidence-source summary').first().click();assert.equal(await page.locator('.evidence-source[open]').count(),1);await page.click('[data-inspector-tab="connections"]');await page.locator('#dialogContent [data-observation]').first().click();await page.locator('#dialogContent [data-history="0"]').first().click();assert.equal(await page.locator('#detailTitle').innerText(),initialTitle);assert(await page.locator('#detailDialog').evaluate(x=>x.open));await page.click('#closeDialog');
 await page.click('#clearFilters');await page.fill('#searchInput','nonexistent evidence xyz');assert.equal(await page.locator('.card').count(),0);await page.click('#clearFilters');
 await page.selectOption('#periodSelect','YEAR');assert.equal(await page.locator('.card').count(),data.obs.filter(o=>Number(o.startDate.slice(0,4))<=1816&&Number(o.endDate.slice(0,4))>=1816).length);
 await page.selectOption('#regionSelect','Asia');await page.selectOption('#evidenceSelect','Tree-ring precipitation-index reconstruction');assert.equal(await page.locator('.card').count(),1);
 await page.locator('.card').first().click();await page.click('[data-inspector-tab="evidence"]');assert((await page.locator('#dialogContent').innerText()).includes('November–May'));await page.click('#closeDialog');await page.click('#clearFilters');
 await page.locator('#researchGaps details').first().evaluate(e=>e.open=true);await page.locator('#researchGaps [data-observation]').first().click();assert(await page.locator('#detailDialog').evaluate(e=>e.open));await page.click('#closeDialog');await page.locator('#researchGaps [data-thread]').first().click();assert((await page.locator('#threadTitle').innerText()).includes('Asante'));
 await page.selectOption('#threadSelect','THREAD-KOREA-RECOVERY');await page.locator('#mechanismPanel details').first().evaluate(e=>e.open=true);await page.locator('#mechanismPanel [data-observation]').first().click();assert((await page.locator('#dialogContent').innerText()).includes('Korean'));await page.click('#closeDialog');
 await page.setViewportSize({width:390,height:844});await page.selectOption('#threadSelect','THREAD-APPIN');assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
 await page.locator('.thread-node').first().click();assert(await page.locator('#detailDialog').evaluate(e=>e.scrollWidth<=e.clientWidth));await page.screenshot({path:'../../worldthreads-mobile-inspector.png'});await page.click('#closeDialog');await page.setViewportSize({width:1440,height:1000});await page.locator('.thread-node').first().click();await page.screenshot({path:'../../worldthreads-desktop-inspector.png'});await page.click('#closeDialog');await page.screenshot({path:'../../worldthreads-mobile.png',fullPage:true});await page.screenshot({path:'../../worldthreads-mobile-top.png',fullPage:false});await page.click('#storyMode');await page.setViewportSize({width:390,height:844});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.screenshot({path:'../../worldthreads-story-mobile.png'});assert.deepEqual(errors,[]);await browser.close();console.log('PASS: all thread endpoints, relationship dialogs, filters, keyboard navigation, nested evidence and mobile width');
})().catch(e=>{console.error(e);process.exit(1)});
