const {chromium}=require('playwright');
const assert=require('node:assert/strict');
(async()=>{
 const browser=await chromium.launch({headless:true});const page=await browser.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto(process.env.WORLDTHREADS_URL||'http://127.0.0.1:8765');await page.waitForFunction(()=>document.querySelectorAll('.card').length>0);

 assert(await page.locator('#storyJourney').isVisible());assert(!(await page.locator('#researchLibrary').isVisible()));
 assert.equal(await page.locator('[data-start-story]').count(),3);await page.click('[data-start-story="harvests"]');
 await page.click('.story-next');await page.click('[data-story-evidence]');assert(await page.locator('.evidence-limits').isVisible());await page.click('#closeDialog');
 await page.click('.story-next');await page.click('.story-next');assert(await page.locator('.story-next').isDisabled());
 await page.click('[data-story-choice="universal"]');assert(!(await page.locator('.story-next').isDisabled()));await page.click('.story-next');assert((await page.locator('#storyHeading').innerText()).includes('Korea'));await page.click('.story-next');
 await page.click('[data-story-frontier]');await page.fill('#proposalClaim','A proposed additional record');await page.fill('[name=url]','https://example.com/archive');await page.fill('[name=locator]','Page 12');await page.fill('[name=datePlace]','1816, Korea');await page.fill('[name=limits]','Requires verification; does not establish household benefit.');await page.locator('#proposalForm button[type=submit]').click();assert((await page.locator('#proposalStatus').innerText()).includes('has not been submitted'));const downloadPromise=page.waitForEvent('download');await page.click('[data-download-proposal]');const downloaded=await downloadPromise;assert.equal(downloaded.suggestedFilename(),'worldthreads-harvests-proposal.json');
 await page.click('[data-story-library]');assert(await page.locator('#researchLibrary').isVisible());assert.equal(await page.locator('#threadSelect').inputValue(),'THREAD-KOREA-RECOVERY');
 await page.selectOption('#threadSelect','THREAD-CENTRAL-EUROPE-FOOD');

 const data=await page.evaluate(async()=>({threads:await(await fetch('data/1816/threads.json')).json(),rels:await(await fetch('data/1816/relationships.json')).json(),obs:await(await fetch('data/1816/observations.json')).json()}));
 assert.equal(await page.locator('.card').count(),data.obs.length);assert.equal(Number(await page.locator('#statThreads').innerText()),data.threads.length);
 for(const t of data.threads){await page.selectOption('#threadSelect',t.id);assert.equal(await page.locator('.connection-row').count(),t.relationshipIds.length);for(let i=0;i<t.relationshipIds.length;i++){const r=data.rels.find(r=>r.id===t.relationshipIds[i]);const row=page.locator('.connection-row').nth(i);assert.equal(await row.locator('.thread-node').first().locator('strong').innerText(),data.obs.find(o=>o.id===r.subjectId).title);assert.equal(await row.locator('.thread-node').last().locator('strong').innerText(),data.obs.find(o=>o.id===r.objectId).title);await row.locator('.edge-label').click();assert.equal(await page.locator('.claim-endpoint').count(),2);assert.equal((await page.locator('.claim-reason p').textContent()).trim(),r.explanation.trim());assert.equal(await page.locator('.evidence-source[open]').count(),0);await page.click('#closeDialog');}}
 await page.selectOption('#regionSelect','Oceania');assert.equal(await page.locator('.card').count(),data.obs.filter(o=>o.continent==='Oceania').length);
 await page.locator('.card').first().press('Enter');const initialTitle=await page.locator('#detailTitle').innerText();await page.click('[data-inspector-tab="evidence"]');assert((await page.locator('#dialogContent').innerText()).includes('What this evidence can establish'));assert.equal(await page.locator('.evidence-source[open]').count(),0);await page.locator('.evidence-source summary').first().click();assert.equal(await page.locator('.evidence-source[open]').count(),1);await page.click('[data-inspector-tab="connections"]');await page.locator('#dialogContent [data-observation]').first().click();await page.locator('#dialogContent [data-history="0"]').first().click();assert.equal(await page.locator('#detailTitle').innerText(),initialTitle);assert(await page.locator('#detailDialog').evaluate(x=>x.open));await page.click('#closeDialog');
 await page.click('#clearFilters');await page.fill('#searchInput','nonexistent evidence xyz');assert.equal(await page.locator('.card').count(),0);await page.click('#clearFilters');
 await page.selectOption('#periodSelect','YEAR');assert.equal(await page.locator('.card').count(),data.obs.filter(o=>Number(o.startDate.slice(0,4))<=1816&&Number(o.endDate.slice(0,4))>=1816).length);
 await page.selectOption('#regionSelect','Asia');await page.selectOption('#evidenceSelect','Tree-ring precipitation-index reconstruction');assert.equal(await page.locator('.card').count(),1);
 await page.locator('.card').first().click();await page.click('[data-inspector-tab="evidence"]');assert((await page.locator('#dialogContent').innerText()).includes('November–May'));await page.click('#closeDialog');await page.click('#clearFilters');
 await page.locator('#researchGaps details').first().evaluate(e=>e.open=true);await page.locator('#researchGaps [data-observation]').first().click();assert(await page.locator('#detailDialog').evaluate(e=>e.open));await page.click('#closeDialog');await page.locator('#researchGaps [data-thread]').first().click();assert((await page.locator('#threadTitle').innerText()).includes('Asante'));
 await page.selectOption('#threadSelect','THREAD-KOREA-RECOVERY');await page.locator('#mechanismPanel details').first().evaluate(e=>e.open=true);await page.locator('#mechanismPanel [data-observation]').first().click();assert((await page.locator('#dialogContent').innerText()).includes('Korean'));await page.click('#closeDialog');
 await page.setViewportSize({width:390,height:844});await page.selectOption('#threadSelect','THREAD-APPIN');assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
 await page.locator('.thread-node').first().click();assert(await page.locator('#detailDialog').evaluate(e=>e.scrollWidth<=e.clientWidth));await page.screenshot({path:'../../worldthreads-mobile-inspector.png'});await page.click('#closeDialog');await page.setViewportSize({width:1440,height:1000});await page.locator('.thread-node').first().click();await page.screenshot({path:'../../worldthreads-desktop-inspector.png'});await page.click('#closeDialog');await page.screenshot({path:'../../worldthreads-mobile.png',fullPage:true});await page.screenshot({path:'../../worldthreads-mobile-top.png',fullPage:false});await page.click('#storyMode');for(const id of ['relief','andes']){await page.click('[data-start-story="'+id+'"]');for(let i=0;i<4;i++){if(id==='relief'){assert(await page.locator('.story-next').isDisabled());for(const clue of await page.locator('[data-case-clue]').all())await clue.click();await page.locator('[data-case-answer]').nth([0,1,2,1][i]).click();}if(i<3){assert(await page.locator('.story-next').isEnabled());await page.click('.story-next');}}assert(await page.locator('.evidence-frontier').isVisible());assert.equal(await page.locator('.story-stop[aria-current]').count(),1);assert(await page.locator('[data-story-frontier]').isEnabled());assert(await page.locator('.map-connection.associated').count()>0);await page.evaluate(()=>window.scrollTo({top:0,behavior:'instant'}));await page.screenshot({path:'../../worldthreads-story-'+id+'.png',fullPage:true});await page.click('[data-story-home]');}await page.setViewportSize({width:390,height:844});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.evaluate(()=>window.scrollTo({top:0,behavior:'instant'}));await page.screenshot({path:'../../worldthreads-story-mobile.png',fullPage:true});assert.deepEqual(errors,[]);await browser.close();console.log('PASS: all thread endpoints, relationship dialogs, filters, keyboard navigation, nested evidence and mobile width');
})().catch(e=>{console.error(e);process.exit(1)});
