import {test} from 'node:test';import assert from 'node:assert/strict';
import worker,{purge} from '../feedback-worker/index.mjs';import {feedbackEnv} from './feedback-db.mjs';import {validateFeedback,safePage} from '../feedback-core.mjs';
const origin='https://stewartdavidp-ship-it.github.io';
const payload=()=>({requestId:crypto.randomUUID(),kind:'problem',note:'Synthetic test report, not a real player message.',email:'',website:'',page:origin+'/worldthreads/?token=SECRET#PRIVATE',context:{appVersion:'v0.5.14',view:'story',stage:'evidence',threadId:'THREAD-BRAZIL-PATRONAGE',argument:'PRIVATE ARGUMENT',evidence:[{id:'WT-1816-0058',role:'support',claim:'PRIVATE REASON'}],progress:{points:185,cases:1,badges:3}},diagnostics:{viewport:{width:390,height:844,scale:2},errors:[{kind:'script',source:'https://site.test/app.js?secret=PRIVATE',message:'PRIVATE ERROR',line:20,column:4}],requests:[{resource:'https://site.test/api/submissions/PRIVATE?token=PRIVATE',status:503,body:'PRIVATE REQUEST'}],actions:[{control:'data-thesis-stage',value:'evidence',text:'PRIVATE'}]}});
const call=(env,p=payload(),headers={},method='POST')=>worker.fetch(new Request('https://feedback.test/api/feedback',{method,headers:{Origin:origin,'Content-Type':'application/json','CF-Connecting-IP':'203.0.113.9',...headers},...(method==='POST'?{body:typeof p==='string'?p:JSON.stringify(p)}:{})}),env);
test('state and message save privately; server projects only allowlisted data; lost acknowledgement retry deduplicates',async()=>{const env=feedbackEnv();try{const p=payload(),first=await call(env,p);assert.equal(first.status,201);assert.equal((await first.json()).receipt,p.requestId);const row=env.DB.raw.prepare('SELECT * FROM player_feedback').get();assert.equal(row.note,p.note);assert.equal(row.page,origin+'/worldthreads/');assert.equal(JSON.stringify(row).includes('PRIVATE'),false);assert.equal(JSON.parse(row.context_json).progress.points,185);assert.equal(JSON.parse(row.context_json).appVersion,'v0.5.14');assert.equal(JSON.parse(row.diagnostics_json).requests[0].resource,'/api/submissions');assert.equal(JSON.parse(row.context_json).evidence[0].role,'support');assert.equal((await call(env,p)).status,200);assert.equal(env.DB.raw.prepare('SELECT count(*) n FROM player_feedback').get().n,1);assert.equal((await call(env,{...p,note:'Different content under the same request ID.'})).status,409);assert.equal((await call(env,null,{},'GET')).status,405);assert.equal((await worker.fetch(new Request('https://feedback.test/api/inbox'),env)).status,404);}finally{env.DB.raw.close();}});
test('validation, origins, bot field, payload size and storage failures reject without false success',async()=>{const env=feedbackEnv();try{for(const bad of [null,[],{}, {...payload(),note:''},{...payload(),note:'x'.repeat(4001)},{...payload(),email:'invalid'},{...payload(),website:'spam'},{...payload(),kind:'approved'}])assert.equal((await call(env,JSON.stringify(bad))).status,400);assert.equal((await call(env,payload(),{Origin:'https://other.test'})).status,403);assert.equal((await call(env,payload(),{Origin:''})).status,403);assert.equal((await call(env,payload(),{'Content-Type':'text/plain'})).status,415);assert.equal((await call(env,'x'.repeat(32769))).status,413);assert.equal(env.DB.raw.prepare('SELECT count(*) n FROM player_feedback').get().n,0);assert.equal((await call({...env,DB:null})).status,503);assert.equal((await call({...env,DB:{prepare(){throw Error('database unavailable');}}})).status,503);assert.equal((await call(env,null,{},'OPTIONS')).status,204);}finally{env.DB.raw.close();}});
test('rate limit is atomic, connection identifiers are keyed and retention removes only expired data',async()=>{const env=feedbackEnv();try{for(let i=0;i<8;i++)assert.equal((await call(env)).status,201);assert.equal((await call(env)).status,429);const keys=env.DB.raw.prepare('SELECT key FROM feedback_quota').all();assert.equal(JSON.stringify(keys).includes('203.0.113.9'),false);env.DB.raw.prepare("UPDATE player_feedback SET status='done',resolved_at=datetime('now','-181 days') WHERE rowid=1").run();env.DB.raw.prepare("UPDATE player_feedback SET created_at=datetime('now','-366 days') WHERE rowid=2").run();env.DB.raw.prepare("UPDATE player_feedback SET status='done',resolved_at=datetime('now') WHERE rowid=3").run();await purge(env);assert.equal(env.DB.raw.prepare('SELECT count(*) n FROM player_feedback').get().n,6);}finally{env.DB.raw.close();}});
test('Unicode feedback remains exact; query/hash and unrelated captured state are dropped',()=>{const p=payload();p.note='資料と解釈\n¿Dónde está la evidencia?';p.diagnostics=null;assert.equal(validateFeedback(p).note,p.note);assert.equal(validateFeedback(p).diagnostics,null);assert.equal(safePage('https://site.test/private/secret-id?key=x#token'),'https://site.test/[other-page]');});
