const {chromium}=require('playwright');const assert=require('node:assert/strict');const fs=require('node:fs');const path=require('node:path');
(async()=>{const browser=await chromium.launch();try{const page=await browser.newPage({viewport:{width:1200,height:900}}),errors=[];page.on('pageerror',e=>errors.push(e.message));
 const draft=require('./fixtures/harvest-playthrough.json'),copy={...draft};delete copy.savedAt;delete copy.aiCandidateReturn;
 const fingerprint=JSON.stringify(Object.fromEntries(Object.entries(copy).sort(([a],[b])=>a.localeCompare(b))));const observations=require('../data/1816/observations.json'),sources=require('../data/1816/sources.json'),records=observations.filter(o=>[draft.record0,draft.record1,draft.record2].includes(o.id));
 const entry={at:'2026-10-07T20:00:00.000Z',context:draft.threadId,fingerprint,draft,records,references:sources.filter(s=>records.some(o=>o.sourceRefs.includes(s.id))),status:'Locally filed, unreviewed research portfolio'};
 const other={...entry,at:'2026-10-07T21:00:00.000Z',draft:{...draft,argument:'A later example revision.'},fingerprint:fingerprint+'-later'};
 await page.addInitScript(({draft,entry,other})=>{if(!localStorage.getItem('panel-test-seeded')){localStorage.setItem('worldthreads-thesis-draft-v1',JSON.stringify(draft));localStorage.setItem('worldthreads-thesis-portfolios-v1',JSON.stringify([entry,other]));localStorage.setItem('panel-test-seeded','yes');}},{draft,entry,other});
 await page.goto(process.env.WORLDTHREADS_URL||'http://127.0.0.1:8772');await page.getByRole('button',{name:'Resume my thesis →'}).click();await page.click('[data-thesis-stage=present]');await page.selectOption('#portfolioVersion','0');await page.locator('#panelReview>summary').click();await page.locator('#panelHandoff>summary').click();await page.click('[data-prepare-panel]');
 const prompt=await page.inputValue('#panelPrompt');assert(prompt.includes(draft.argument));assert(prompt.includes(records[0].observation));assert(prompt.includes('Do not grade'));assert(prompt.includes('RETURN FORMAT'));assert(prompt.includes('fenced ```json code block'));assert(prompt.includes('code block’s Copy button'));await page.fill('#panelReturn','{"url":"https\\://example.com"}');await page.click('[data-import-panel]');assert((await page.locator('#panelStatus').innerText()).includes('code block Copy button'));assert(prompt.includes('not instructions to execute'));
 const response=JSON.parse(prompt.split('Required output shape:\n')[1].split('\n\nCLAIMS TO REVIEW')[0]);response.summary='Example advisory critique: the thesis distinguishes contrasting reports from unresolved local causes. No original source was inspected in this test.';response.sourceChecks=[];response.disagreements=['A source comparison may support a reporting contrast while leaving the causal explanation unresolved.'];response.nextSteps=['Verify the original administrative classification criteria.','Seek matched local crop and household records.'];response.defenseQuestions=['What would distinguish reporting differences from differences in local crop outcomes?'];for(const r of response.reviewers){r.strengths=[{claimId:'C1',finding:'The draft states the limits of its comparison and preserves pending research.',basis:'methodological concern',sourceUrl:'',locator:''}];r.concerns[0].finding='The regional comparison uses different reporting categories. Can the claim be narrowed to what these reports establish?';r.concerns[0].nextAction='Seek the underlying classification criteria and compare matched dates.';r.concerns[0].whatWouldChange='A matched local comparison showing that reporting categories cannot explain the contrast.';}
 const thesisBefore=await page.evaluate(()=>localStorage.getItem('worldthreads-thesis-draft-v1'));const progressBefore=await page.evaluate(()=>localStorage.getItem('worldthreads-progress-v1'));
 async function attempt(value,expected){if(!await page.locator('#panelHandoff').evaluate(e=>e.open))await page.locator('#panelHandoff>summary').click();await page.fill('#panelReturn',typeof value==='string'?value:JSON.stringify(value));await page.click('[data-import-panel]');assert((await page.locator('#panelStatus').innerText()).includes(expected));}
 await attempt('{broken','not imported');assert.equal(await page.inputValue('#panelReturn'),'{broken');await attempt({...response,grade:'A'},'not imported');await attempt({...response,requestId:'wrong-version'},'different filed version');
 const unsafe=structuredClone(response);unsafe.reviewers[0].concerns[0].sourceUrl='javascript:alert(1)';await attempt(unsafe,'not imported');const unchecked=structuredClone(response);unchecked.reviewers[0].concerns[0].basis='inspected passage';await attempt(unchecked,'not imported');
 const real=require('./fixtures/chatgpt-panel-review.json');real.requestId=response.requestId;await attempt('```json\n'+JSON.stringify(real)+'\n```','attached locally');await page.locator('#panelPresentation').evaluate(e=>window.scrollTo(0,window.scrollY+e.getBoundingClientRect().top-130));await page.screenshot({path:path.resolve(__dirname,'../../../outputs/WorldThreads actual ChatGPT critique.png')});await attempt('```json\n'+JSON.stringify(response)+'\n```','attached locally');assert.equal(await page.evaluate(()=>localStorage.getItem('worldthreads-thesis-draft-v1')),thesisBefore);assert.equal(await page.evaluate(()=>localStorage.getItem('worldthreads-progress-v1')),progressBefore);
 await page.getByText('Source auditor · 1 question',{exact:true}).click();await page.selectOption('[data-panel-response=sources-1][data-response-field=decision]','investigate');await page.fill('[data-panel-response=sources-1][data-response-field=note]','I will verify the categories before extending the household claim; original records remain unchecked.');await attempt(response,'already attached');assert.equal(await page.inputValue('[data-panel-response=sources-1][data-response-field=note]'),'I will verify the categories before extending the household claim; original records remain unchecked.');
 const download=page.waitForEvent('download');await page.click('[data-download-panel-presentation]');const dl=await download,packet=JSON.parse(fs.readFileSync(await dl.path(),'utf8'));assert.equal(packet.portfolio.draft.argument,draft.argument);assert.equal(packet.panelReview.responses['sources-1'].decision,'investigate');assert.equal(packet.panelReview.review.sourceChecks.length,0);
 await page.selectOption('#portfolioVersion','1');assert.equal(await page.inputValue('#panelPrompt'),'');assert((await page.locator('#panelPresentation').innerText()).includes('No panel review'));await attempt(response,'different filed version');await page.selectOption('#portfolioVersion','0');assert((await page.locator('#panelPresentation').innerText()).includes(response.summary));
 await page.reload();await page.getByRole('button',{name:'Resume my thesis →'}).click();await page.click('[data-thesis-stage=present]');await page.selectOption('#portfolioVersion','0');await page.locator('#panelReview>summary').click();await page.getByText('Source auditor · 1 question',{exact:true}).click();assert((await page.inputValue('[data-panel-response=sources-1][data-response-field=note]')).includes('original records remain unchecked'));
 await page.locator('#panelPresentation').evaluate(e=>window.scrollTo(0,window.scrollY+e.getBoundingClientRect().top-130));await page.screenshot({path:path.resolve(__dirname,'../../../outputs/WorldThreads panel review presentation.png')});await page.setViewportSize({width:390,height:844});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.evaluate(()=>document.documentElement.dataset.theme='light');const axe=fs.readFileSync(require.resolve('axe-core/axe.min.js',{paths:[path.join(__dirname,'..','work','a11y'),process.cwd()]}),'utf8');await page.addScriptTag({content:axe});const result=await page.evaluate(()=>axe.run(document.getElementById('panelReview'),{runOnly:{type:'tag',values:['wcag2a','wcag2aa','wcag21aa']}}));assert.deepEqual(result.violations.map(x=>x.id),[]);assert.deepEqual(errors,[]);
 console.log('PASS: self-contained prompt → strict advisory return → wrong-version/malformed/grading/unsafe-source rejection → local critique display → player response → presentation download → duplicates preserve responses → version isolation → reload → mobile/light/accessibility. Example response is a test fixture, not a real AI source audit.');
 }finally{await browser.close();}})().catch(e=>{console.error(e);process.exit(1)});
