const {chromium}=require('playwright');
const assert=require('node:assert/strict');
(async()=>{
 const browser=await chromium.launch({headless:true});const page=await browser.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));
 const url=process.env.WORLDTHREADS_URL||'http://127.0.0.1:8765';
 const points=async()=>Number((await page.locator('.progress-summary strong').innerText()).split(' ')[0]);
 const source=async()=>{await page.locator('[data-story-evidence]:visible').first().click();await page.locator('.evidence-source summary').first().click();await page.click('#closeDialog');};
 const fileCase=async(id)=>{const ids={harvests:['WT-1816-0006','WT-1816-0045'],relief:['WT-1816-0035','WT-1816-0034'],andes:['WT-1816-0060','WT-1816-0030']}[id];for(const record of ids)await page.check('#caseFileForm input[value="'+record+'"]');await page.selectOption('#caseFileForm [name=limit]','0');await page.selectOption('#caseFileForm [name=next]','0');await page.locator('#caseFileForm button[type=submit]').click();assert(await page.locator('.case-victory').isVisible());};
 const connection=async()=>{await page.locator('.story-proof [data-story-claim],.case-reveal [data-story-claim]:visible').first().click();await page.click('#closeDialog');};
 await page.goto(url);await page.waitForSelector('[data-start-story]');assert.equal(await points(),0);
 await page.locator('.challenge-shelf summary').click();assert(await page.locator('[data-investigation-challenge=causation]').isDisabled());
 await page.click('[data-start-story=harvests]');assert.equal(await points(),5);await page.click('.story-next');await source();await connection();assert.equal(await points(),50);
 await source();await connection();assert.equal(await points(),50);await page.click('.story-next');assert.equal(await points(),55);
 await page.reload();await page.waitForSelector('[data-start-story]');assert((await page.locator('[data-start-story=harvests]').innerText()).includes('Resume'));await page.click('[data-start-story=harvests]');assert((await page.locator('#storyHeading').innerText()).includes('table'));assert.equal(await points(),55);
 await page.click('.story-next');await page.click('[data-story-choice=regional]');await page.click('.story-next');await page.click('.story-next');assert.equal(await points(),110);assert(await page.locator('#caseFileForm').isVisible());await page.selectOption('#caseFileForm [name=limit]','1');await page.selectOption('#caseFileForm [name=next]','0');await page.locator('#caseFileForm button[type=submit]').click();assert.equal(await points(),110);assert(await page.locator('#caseFileFeedback').isVisible());await page.check('#caseFileForm input[value="WT-1816-0006"]');await page.check('#caseFileForm input[value="WT-1816-0045"]');await page.locator('#caseFileForm button[type=submit]').click();assert.equal(await points(),110);assert((await page.locator('#caseFileFeedback').innerText()).includes('Reconsider'));await fileCase('harvests');assert.equal(await points(),185);const caseDownload=page.waitForEvent('download');await page.click('[data-download-case]');assert.equal((await caseDownload).suggestedFilename(),'worldthreads-harvests-case-file.md');
 await page.click('[data-story-home]');await page.locator('.challenge-shelf summary').click();assert(await page.locator('[data-investigation-challenge=causation]').isEnabled());assert(await page.locator('[data-investigation-challenge=comparison]').isDisabled());
 await page.click('[data-investigation-challenge=causation]');await page.click('[data-answer="0"]');assert.equal(await points(),185);await page.click('[data-answer="1"]');assert.equal(await points(),225);await page.click('[data-answer="1"]');assert.equal(await points(),225);await page.click('[data-story-home]');
 for(const id of ['relief','andes']){await page.click('[data-start-story='+id+']');for(let i=0;i<4;i++){if(id==='relief'){assert(await page.locator('.story-next').isDisabled());assert(await page.locator('[data-case-answer]').first().isDisabled());for(const clue of await page.locator('[data-case-clue]').all())await clue.click();if(i===0){await page.reload();await page.waitForSelector('[data-start-story]');await page.click('[data-start-story=relief]');assert(await page.locator('[data-case-answer]').first().isEnabled());}const before=await points();await page.locator('[data-case-answer]').nth(([0,1,2,1][i]+1)%3).click();assert.equal(await points(),before);assert(await page.locator('.story-next').isDisabled());await page.locator('[data-case-answer]').nth([0,1,2,1][i]).click();assert.equal(await points(),before+20+(i===3?30:0));}if(i===0)await source();if(i===1)await connection();if(i<3)await page.click('.story-next');}await fileCase(id);await page.click('[data-story-home]');}
 assert.equal(await points(),635);await page.locator('.challenge-shelf summary').click();assert(await page.locator('[data-investigation-challenge=comparison]').isEnabled());await page.click('[data-investigation-challenge=comparison]');await page.click('[data-answer="2"]');assert.equal(await points(),825);await page.click('[data-answer="2"]');assert.equal(await points(),825);
 await page.reload();await page.waitForSelector('[data-start-story]');assert.equal(await points(),825);assert((await page.locator('.expedition-goal').innerText()).includes('Expedition completed'));assert.equal(await page.locator('.expedition-goal>details').getAttribute('open'),null);await page.locator('.expedition-goal>details>summary').click();assert((await page.locator('.expedition-meter strong').innerText()).includes('5/5'));assert((await page.locator('[data-start-story=andes]').innerText()).includes('Revisit'));await page.locator('#investigationProgress summary').click();assert.equal(await page.locator('.earned-badges .earned').count(),8);
 await page.click('[data-start-story=relief]');await page.screenshot({path:'../../worldthreads-investigation-desktop.png',fullPage:true});await page.click('[data-story-home]');await page.setViewportSize({width:390,height:844});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.screenshot({path:'../../worldthreads-progress-mobile.png',fullPage:true});
 if(!await page.locator('.expedition-goal>details').evaluate(d=>d.open))await page.locator('.expedition-goal>details>summary').click();await page.click('[data-open-thesis]');assert(await page.locator('#thesisForm').isVisible());await page.locator('.thesis-workspace details').evaluateAll(ds=>ds.forEach(d=>d.open=true));
 for(const key of ['title','question','argument','historiography','scope','method','counterargument','response','revision','chapters','schedule'])await page.fill('#thesisForm [name='+key+']','Working research note for '+key);
 for(let i=0;i<3;i++){await page.selectOption('[name=record'+i+']',['WT-1816-0035','WT-1816-0034','WT-1816-0045'][i]);await page.fill('[name=claim'+i+']','A provisional subclaim, pending verification.');await page.fill('[name=locator'+i+']','Passage needs independent checking.');}
 await page.locator('#thesisForm button[type=submit]').click();assert((await page.locator('#thesisStatus').innerText()).includes('11/11'));assert.equal(await points(),825);const thesisDownload=page.waitForEvent('download');await page.click('[data-download-thesis]');const thesis=await thesisDownload;assert.equal(thesis.suggestedFilename(),'worldthreads-thesis-draft.md');const fs=require('node:fs');const exported=fs.readFileSync(await thesis.path(),'utf8');assert(exported.includes('Claim–evidence table'));assert(exported.includes('Bibliography from selected records'));assert(exported.includes('Unreviewed')||exported.includes('unreviewed'));assert(exported.includes('SRC-'));assert(exported.includes('Counter')||exported.includes('counterargument'));
 await page.reload();await page.waitForSelector('[data-start-story]');if(!await page.locator('.expedition-goal>details').evaluate(d=>d.open))await page.locator('.expedition-goal>details>summary').click();await page.click('[data-open-thesis]');assert.equal(await page.locator('[name=title]').inputValue(),'Working research note for title');assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
 await page.evaluate(()=>localStorage.setItem('worldthreads-investigation-progress-v1','broken'));await page.reload();await page.waitForSelector('[data-start-story]');assert.equal(await points(),0);assert.deepEqual(errors,[]);
 await browser.close();console.log('PASS: unique rewards, resume after reload, locked/unlocked challenges, wrong-answer and repeat protection, persistent badges, case files, expedition completion, thesis draft export, mobile width and corrupt-storage recovery');
})().catch(e=>{console.error(e);process.exit(1)});
