const {chromium}=require('playwright');
const assert=require('node:assert/strict');
(async()=>{
 const browser=await chromium.launch({headless:true});const page=await browser.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));
 const url=process.env.WORLDTHREADS_URL||'http://127.0.0.1:8765';
 const points=async()=>Number((await page.locator('.progress-summary strong').innerText()).split(' ')[0]);
 const source=async()=>{await page.locator('[data-story-evidence]:visible').first().click();await page.locator('.evidence-source summary').first().click();await page.click('#closeDialog');};
 const connection=async()=>{await page.locator('.story-proof [data-story-claim],.case-reveal [data-story-claim]:visible').first().click();await page.click('#closeDialog');};
 await page.goto(url);await page.waitForSelector('[data-start-story]');assert.equal(await points(),0);
 await page.locator('.challenge-shelf summary').click();assert(await page.locator('[data-investigation-challenge=causation]').isDisabled());
 await page.click('[data-start-story=harvests]');assert.equal(await points(),5);await page.click('.story-next');await source();await connection();assert.equal(await points(),50);
 await source();await connection();assert.equal(await points(),50);await page.click('.story-next');assert.equal(await points(),55);
 await page.reload();await page.waitForSelector('[data-start-story]');assert((await page.locator('[data-start-story=harvests]').innerText()).includes('Resume'));await page.click('[data-start-story=harvests]');assert((await page.locator('#storyHeading').innerText()).includes('table'));assert.equal(await points(),55);
 await page.click('.story-next');await page.click('[data-story-choice=regional]');await page.click('.story-next');await page.click('.story-next');assert.equal(await points(),110);
 await page.click('[data-story-home]');await page.locator('.challenge-shelf summary').click();assert(await page.locator('[data-investigation-challenge=causation]').isEnabled());assert(await page.locator('[data-investigation-challenge=comparison]').isDisabled());
 await page.click('[data-investigation-challenge=causation]');await page.click('[data-answer="0"]');assert.equal(await points(),110);await page.click('[data-answer="1"]');assert.equal(await points(),150);await page.click('[data-answer="1"]');assert.equal(await points(),150);await page.click('[data-story-home]');
 for(const id of ['relief','andes']){await page.click('[data-start-story='+id+']');for(let i=0;i<4;i++){if(id==='relief'){assert(await page.locator('.story-next').isDisabled());assert(await page.locator('[data-case-answer]').first().isDisabled());for(const clue of await page.locator('[data-case-clue]').all())await clue.click();if(i===0){await page.reload();await page.waitForSelector('[data-start-story]');await page.click('[data-start-story=relief]');assert(await page.locator('[data-case-answer]').first().isEnabled());}const before=await points();await page.locator('[data-case-answer]').nth(([0,1,2,1][i]+1)%3).click();assert.equal(await points(),before);assert(await page.locator('.story-next').isDisabled());await page.locator('[data-case-answer]').nth([0,1,2,1][i]).click();assert.equal(await points(),before+20+(i===3?30:0));}if(i===0)await source();if(i===1)await connection();if(i<3)await page.click('.story-next');}await page.click('[data-story-home]');}
 assert.equal(await points(),410);await page.locator('.challenge-shelf summary').click();assert(await page.locator('[data-investigation-challenge=comparison]').isEnabled());await page.click('[data-investigation-challenge=comparison]');await page.click('[data-answer="2"]');assert.equal(await points(),450);
 await page.reload();await page.waitForSelector('[data-start-story]');assert.equal(await points(),450);assert((await page.locator('[data-start-story=andes]').innerText()).includes('Revisit'));await page.locator('#investigationProgress summary').click();assert.equal(await page.locator('.earned-badges .earned').count(),6);
 await page.click('[data-start-story=relief]');await page.screenshot({path:'../../worldthreads-investigation-desktop.png',fullPage:true});await page.click('[data-story-home]');await page.setViewportSize({width:390,height:844});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.screenshot({path:'../../worldthreads-progress-mobile.png',fullPage:true});
 await page.evaluate(()=>localStorage.setItem('worldthreads-investigation-progress-v1','broken'));await page.reload();await page.waitForSelector('[data-start-story]');assert.equal(await points(),0);assert.deepEqual(errors,[]);
 await browser.close();console.log('PASS: unique rewards, resume after reload, locked/unlocked challenges, wrong-answer and repeat protection, persistent badges, mobile width and corrupt-storage recovery');
})().catch(e=>{console.error(e);process.exit(1)});
