// Reconfirm each scenario in a separate browser process and retain an explicit result ledger.
const {spawnSync,execFileSync}=require('node:child_process');const fs=require('node:fs');
const suites=['explorer','progress','objects','research-flow','argument-board','examiner','ai-research','winning-game','returning-player','durability','interruption','adversarial-research','accessibility','concurrent-progress','navigation-matrix','navigation-race'].map(name=>({name,env:{}}));
if(process.env.WORLDTHREADS_AXE==='1')suites.push({name:'semantic-accessibility',env:{}},{name:'feedback',env:{}});
if(process.env.WORLDTHREADS_PUBLISHED_PREVIEW)suites.push({name:'feedback-published',env:{}});
suites.push({name:'winning-game',label:'winning-game-keyboard',env:{WORLDTHREADS_KEYBOARD:'1'}});
if(process.env.WORLDTHREADS_CROSS_BROWSER==='1')for(const browser of ['firefox','webkit'])suites.push({name:'winning-game',label:'winning-game-'+browser,env:{WORLDTHREADS_BROWSER:browser}});
const report={commit:execFileSync('git',['rev-parse','HEAD'],{encoding:'utf8'}).trim(),startedAt:new Date().toISOString(),scope:'Functional browser confirmation; not historical or human usability certification',results:[]};
for(const suite of suites){const label=suite.label||suite.name;console.log('START '+label);const result=spawnSync(process.execPath,['tests/'+suite.name+'.cjs'],{encoding:'utf8',env:{...process.env,WORLDTHREADS_KEYBOARD:'',WORLDTHREADS_BROWSER:'chromium',...suite.env},timeout:240000});const entry={suite:label,at:new Date().toISOString(),passed:result.status===0,output:(result.stdout||'')+(result.stderr||''),error:result.error?.message};report.results.push(entry);console.log(entry.output.trim());console.log((entry.passed?'PASS ':'FAIL ')+label);if(process.env.WORLDTHREADS_CONFIRMATION_OUTPUT)fs.writeFileSync(process.env.WORLDTHREADS_CONFIRMATION_OUTPUT,JSON.stringify(report,null,2));}
report.completedAt=new Date().toISOString();report.passed=report.results.every(x=>x.passed);if(process.env.WORLDTHREADS_CONFIRMATION_OUTPUT)fs.writeFileSync(process.env.WORLDTHREADS_CONFIRMATION_OUTPUT,JSON.stringify(report,null,2));console.log(`${report.results.filter(x=>x.passed).length}/${report.results.length} confirmations passed`);process.exitCode=report.passed?0:1;
