const {chromium}=require('playwright');
const assert=require('node:assert/strict');
(async()=>{
 const browser=await chromium.launch({headless:true});const page=await browser.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));
 const url=process.env.WORLDTHREADS_URL||'http://127.0.0.1:8765';
 const points=async()=>Number((await page.locator('.progress-summary strong').innerText()).split(' ')[0]);
 const source=async()=>{await page.locator('[data-story-evidence]:visible').first().click();await page.locator('.evidence-source summary').first().click();await page.click('#closeDialog');};
 const fileCase=async(id)=>{const ids={harvests:['WT-1816-0006','WT-1816-0045'],relief:['WT-1816-0035','WT-1816-0034'],andes:['WT-1816-0060','WT-1816-0030']}[id];for(const record of ids)await page.check('#caseFileForm input[value="'+record+'"]');await page.selectOption('#caseFileForm [name=limit]','0');await page.selectOption('#caseFileForm [name=next]','0');await page.locator('#caseFileForm button[type=submit]').click();assert(await page.locator('.case-victory').isVisible());};
 const connection=async()=>{await page.locator('.story-proof [data-story-claim],.case-reveal [data-story-claim]:visible').first().click();await page.click('#closeDialog');};
 await page.goto(url);await page.waitForSelector('[data-start-story]');assert.equal(await points(),0);
 await page.locator('.challenge-shelf summary').click();assert(await page.locator('[data-investigation-challenge=causation]').isDisabled());
 await page.click('[data-start-story=harvests]');assert.equal(await points(),5);await page.click('.story-next');await source();await connection();assert.equal(await points(),50);
 await source();await connection();assert.equal(await points(),50);await page.click('.story-next');assert.equal(await points(),55);
 await page.reload();await page.waitForSelector('[data-start-story]');assert((await page.locator('[data-start-story=harvests]').innerText()).includes('Resume'));await page.click('[data-start-story=harvests]');assert((await page.locator('#storyHeading').innerText()).includes('table'));assert.equal(await points(),55);
 await page.click('.story-next');await page.click('[data-story-choice=regional]');await page.click('.story-next');await page.click('.story-next');assert.equal(await points(),110);assert(await page.locator('#caseFileForm').isVisible());await page.selectOption('#caseFileForm [name=limit]','1');await page.selectOption('#caseFileForm [name=next]','0');await page.locator('#caseFileForm button[type=submit]').click();assert.equal(await points(),110);assert(await page.locator('#caseFileFeedback').isVisible());await page.check('#caseFileForm input[value="WT-1816-0006"]');await page.check('#caseFileForm input[value="WT-1816-0045"]');await page.locator('#caseFileForm button[type=submit]').click();assert.equal(await points(),110);assert((await page.locator('#caseFileFeedback').innerText()).includes('Reconsider'));await fileCase('harvests');assert.equal(await points(),185);const caseDownload=page.waitForEvent('download');await page.click('[data-download-case]');assert.equal((await caseDownload).suggestedFilename(),'worldthreads-harvests-case-file.md');
 await page.click('[data-story-home]');await page.locator('.challenge-shelf summary').click();assert(await page.locator('[data-investigation-challenge=causation]').isEnabled());assert(await page.locator('[data-investigation-challenge=comparison]').isDisabled());
 await page.click('[data-investigation-challenge=causation]');await page.click('[data-answer="0"]');assert.equal(await points(),185);await page.click('[data-answer="1"]');assert.equal(await points(),225);await page.click('[data-answer="1"]');assert.equal(await points(),225);await page.click('[data-story-home]');
 for(const id of ['relief','andes']){await page.click('[data-start-story='+id+']');for(let i=0;i<4;i++){if(id==='relief'){assert(await page.locator('.story-next').isDisabled());assert(await page.locator('[data-case-answer]').first().isDisabled());for(const clue of await page.locator('[data-case-clue]').all())await clue.click();if(i===0){await page.reload();await page.waitForSelector('[data-start-story]');await page.click('[data-start-story=relief]');assert(await page.locator('[data-case-answer]').first().isEnabled());}const before=await points();await page.locator('[data-case-answer]').nth(([0,1,2,1][i]+1)%3).click();assert.equal(await points(),before);assert(await page.locator('.story-next').isDisabled());await page.locator('[data-case-answer]').nth([0,1,2,1][i]).click();assert.equal(await points(),before+20+(i===3?30:0));}if(i===0)await source();if(i===1)await connection();if(i<3)await page.click('.story-next');}await fileCase(id);await page.click('[data-story-home]');}
 assert.equal(await points(),635);await page.locator('.challenge-shelf summary').click();assert(await page.locator('[data-investigation-challenge=comparison]').isEnabled());await page.click('[data-investigation-challenge=comparison]');await page.click('[data-answer="2"]');assert.equal(await points(),825);await page.click('[data-answer="2"]');assert.equal(await points(),825);
 await page.reload();await page.waitForSelector('[data-start-story]');assert.equal(await points(),825);assert((await page.locator('.expedition-goal').innerText()).includes('Expedition completed'));assert((await page.locator('.expedition-meter strong').innerText()).includes('5/5'));assert((await page.locator('[data-start-story=andes]').innerText()).includes('Revisit'));await page.locator('#investigationProgress summary').click();assert.equal(await page.locator('.earned-badges .earned').count(),8);
 // Complete the optional contribution badge, then enter independent thesis research.
 await page.click('[data-start-story=relief]');await page.locator('#storyContribution > summary').click();const proposal={claim:'Research lead: authorization does not establish who received subsidized rye.',url:'https://doi.org/10.1093/pastj/gtaa014',locator:'Section IV; passage verification remains required',datePlace:'Amsterdam, 1817',limits:'An existing research gap, not newly verified delivery evidence.'};for(const [key,value] of Object.entries(proposal))await page.fill('#proposalForm [name='+key+']',value);await page.locator('#proposalForm button[type=submit]').click();assert.equal(await points(),840);await page.locator('#proposalForm button[type=submit]').click();assert.equal(await points(),840);await page.click('[data-thread-thesis]');await page.click('[data-thesis-stage=present]');await page.click('[data-file-portfolio]');assert((await page.locator('#portfolioStatus').innerText()).includes('not filed'));assert.equal(await points(),840);await page.click('[data-portfolio-stage=research]');assert(await page.locator('#researchDesk').getAttribute('open')!==null);
 await page.click('[data-return-thread]');await page.selectOption('#threadSelect','THREAD-BRAZIL-PATRONAGE');await page.click('#threadThesis');assert.equal(await page.locator('[name=argument]').inputValue(),'');
 await page.locator('#thesisForm details').evaluateAll(ds=>ds.forEach(d=>d.open=true));const before='The royal decree proves the proposed academy was fully operating in 1816.';const after='The 1816 decree records patronage toward planned instruction. A retrospective account describes teaching before the academy operated fully in 1826; neither source establishes the scale or recipients of instruction in 1816.';
 const fields={title:'Patronage and implementation: testing the Brazilian academy project',question:'What distinguishes legal authorization, private teaching and full institutional operation between 1816 and 1826?',argument:before,historiography:'Compare the registered Biblioteca Nacional account and royal decree with the Arquivo Nacional interpretation. Institutional founding dates may encode legal creation rather than actual teaching; this is a pilot, not a complete literature review.',scope:'Rio de Janeiro, 1816–1826; distinguish the decree date from later operation. Do not generalize to every artist or student.',method:'Compare the decree with retrospective interpretation; seek dated class, payroll and attendance records. Treat institutional summaries as secondary accounts and compare source dependencies.',counterargument:'Private teaching may predate full academy operation. A delayed building does not prove that no instruction occurred.',response:'Separate patronage, private instruction and full institutional operation. Preserve uncertainty about teaching scale and recipients.',revision:'Dated attendance, teaching accounts and payroll could revise the chronology and scope; negative archive searches are not proof of no teaching.',chapters:'1. Founding versus operation. 2. Decree and patronage. 3. Private teaching and institutional development. 4. Rival explanations and the missing attendance evidence.',schedule:'Locate cited scholarship and contemporary class records. Verify dates and provenance, then revise the implementation chapter.'};for(const [key,value] of Object.entries(fields))await page.fill('[name='+key+']',value);
 await page.click('[data-thesis-stage=research]');for(const [key,value] of Object.entries({researchQuestion:'How much teaching occurred before full academy operation?',researchSource:'Dated class registers, payroll, correspondence and attendance records.',researchPlan:'Search archival descriptions and cited scholarship; log unavailable documents and conflicting dates. Do not equate a building opening with the start of all instruction.'}))await page.fill('[name='+key+']',value);await page.getByText('Take this question to an AI research assistant',{exact:true}).click();await page.click('[data-build-ai-brief]');assert((await page.locator('#aiResearchBrief').inputValue()).includes(before));await page.fill('#aiResearchReturn',JSON.stringify({claim:'The school worked immediately',url:'https://example.com',datePlace:'1816',limits:'None'}));await page.click('[data-import-ai-return]');await page.waitForFunction(()=>document.getElementById('researchImportStatus').textContent.includes('rejected'));assert.equal(await points(),840);
 const candidate={claim:'Arquivo Nacional’s retrospective account reports private teaching before the academy was established and distinguishes official founding in 1816 from full operation in its completed building in 1826.',url:'https://www.gov.br/arquivonacional/pt-br/sites_eventos/sites-tematicos-1/brasil-oitocentista/documentos/ordem-imperial-do-cruzeiro-para-jean-baptiste-debret',locator:'Explanatory paragraphs beginning Chegado no Brasil, Fundada oficialmente and Sem uma sede própria (before Transcrição).',datePlace:'Rio de Janeiro, 1816–1826; web interpretation updated 12 September 2023',limits:'The explanatory text is retrospective. The displayed 1840 honorary appointment does not itself establish 1816 attendance. Original class records remain needed.',kind:'Challenge to an existing claim'};await page.fill('#aiResearchReturn',JSON.stringify(candidate));await page.click('[data-import-ai-return]');await page.waitForFunction(()=>document.getElementById('researchImportStatus').textContent.includes('Imported'));const local=await page.evaluate(()=>JSON.parse(localStorage.getItem('worldthreads-local-research-v1')));assert.equal(local.length,1);assert((await page.locator('#researchFindings').innerText()).includes('Local additions · 1'));assert.equal(local[0].reviewStatus,'Unreviewed');
 await page.click('[data-thesis-stage=evidence]');await page.click('[data-thesis-table]');await page.selectOption('[name=record2]',local[0].id);for(let i=0;i<3;i++)await page.fill('[name=locator'+i+']',i===2?'Read explanatory web paragraphs; contemporary class records not inspected.':'Registered passage locator; original passage requires independent rechecking.');
 await page.click('[data-thesis-stage=defense]');await page.click('[data-reframe-examiner]');const test={testRival:'Patronage authorized a developing institution; private instruction could occur before full academy operation.',testOwnPrediction:'Dated institutional classes and attendance would show full academy operation in 1816.',testRivalPrediction:'Records might show private teaching alongside delayed full institutional operation.',testDiscriminator:'Compare the retrospective account with dated class and payroll records, distinguishing legal creation and teaching scale.',testReason:'The decree cannot establish implementation. The retrospective candidate complicates the early-operation premise while leaving class scale unresolved.',testRevisedArgument:after};for(const [key,value] of Object.entries(test))await page.fill('[name='+key+']',value);await page.selectOption('[name=testRecord]',local[0].id);await page.selectOption('[name=testResult]','rival');await page.selectOption('[name=testDecision]','narrow');await page.click('[data-apply-examiner]');assert.equal(await page.locator('[name=argument]').inputValue(),after);assert.equal(await points(),840);
 await page.click('[data-thesis-stage=evidence]');for(let i=0;i<3;i++){await page.click('[data-board-record="'+i+'"]');await page.click('[data-board-role='+['context','support','challenge'][i]+']');await page.fill('#boardReason',['Arrival establishes context, not the scale of instruction.','The decree supports planned patronage; it does not demonstrate full operation.','The retrospective candidate challenges immediate full operation while also warning against assuming no earlier private teaching.'][i]);}
 await page.click('[data-thesis-stage=present]');assert.equal(await page.locator('#portfolioChecklist').getByText(/^○/).count(),0);await page.click('[data-file-portfolio]');assert((await page.locator('#portfolioStatus').innerText()).includes('Research round completed'));assert.equal(await points(),890);await page.click('[data-file-portfolio]');assert.equal(await points(),890);assert((await page.locator('#portfolioStatus').innerText()).includes('No duplicate'));
 const event=page.waitForEvent('download');await page.click('[data-download-portfolio]');const fs=require('node:fs');const download=await event;const filed=JSON.parse(fs.readFileSync(await download.path(),'utf8'));assert.equal(filed.draft.argument,after);assert.equal(filed.records.length,3);assert(filed.records.some(o=>o.reviewStatus==='Unreviewed'));assert.equal(filed.draft.argumentRevisions[0].before,before);assert(filed.references.length);if(process.env.WORLDTHREADS_PORTFOLIO_OUTPUT)await download.saveAs(process.env.WORLDTHREADS_PORTFOLIO_OUTPUT);
 const manuscriptEvent=page.waitForEvent('download');await page.click('[data-download-thesis]');const manuscript=await manuscriptEvent;if(process.env.WORLDTHREADS_THESIS_OUTPUT)await manuscript.saveAs(process.env.WORLDTHREADS_THESIS_OUTPUT);const text=fs.readFileSync(await manuscript.path(),'utf8');assert(text.includes(after));assert(text.includes('Before: '+before));assert(text.includes('not a registered observation'));assert(text.includes('Research tasks and dead ends'));
 await page.click('[data-thesis-stage=topic]');await page.fill('[name=argument]','Changed claim requiring a new rival test.');await page.click('[data-thesis-stage=present]');assert((await page.locator('#portfolioHistory').innerText()).includes('changed since filing'));await page.click('[data-file-portfolio]');assert((await page.locator('#portfolioStatus').innerText()).includes('not filed'));assert.equal(await points(),890);assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('worldthreads-thesis-portfolios-v1'))[0].draft.argument),after);
 await page.click('[data-thesis-stage=topic]');await page.fill('[name=argument]',after);await page.reload();await page.waitForSelector('[data-start-story]');assert((await page.locator('.expedition-goal').innerText()).includes('Expedition completed'));await page.locator('#investigationProgress summary').click();assert.equal(await page.locator('.earned-badges .earned').count(),10);assert.equal(await points(),890);await page.getByRole('button',{name:'Resume my thesis →'}).click();await page.click('[data-thesis-stage=present]');assert((await page.locator('#portfolioHistory').innerText()).includes('matches'));await page.setViewportSize({width:390,height:844});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));assert.deepEqual(errors,[]);
 await browser.close();console.log('PASS: fresh player → 3 cases → 2 challenges → all 10 badges / 890 points → sourced proposal → AI research return → rival test → thesis revision → evidence reassessment → local portfolio filing → immutable download → duplicate protection → changed-draft rejection → reload / mobile. No external submission or scholarly certification.');
})().catch(e=>{console.error(e);process.exit(1)});
