const {test}=require('node:test'),assert=require('node:assert/strict');
const fs=require('node:fs'),path=require('node:path');
const core=require('../community-core.js'),intake=require('../contribution.js');
const read=n=>JSON.parse(fs.readFileSync(path.join(__dirname,'../data/1816',n+'.json'),'utf8'));
const existing={observations:read('observations'),relationships:read('relationships'),sources:read('sources'),threads:read('threads'),gaps:read('research-gaps'),missions:read('research-missions')};
function research(){const o=structuredClone(existing.observations[0]);Object.assign(o,{id:'NEW-FACT',sourceRefs:['NEW-SOURCE'],evidenceRefs:['NEW-EVIDENCE'],researchStatus:core.pending});return {kind:'research',consent:true,draft:{schemaVersion:1,context:{question:'What happened locally?',threadId:existing.threads[0].id,year:1816,place:'Salem',direction:'continue_thread'},contributor:{name:'Local researcher'},review:{status:'pending'},observations:[o],relationships:[],sources:[{id:'NEW-SOURCE',title:'An archive entry',type:'Archive',authorOrOrg:'Archivist',url:'https://archive.example.edu/1816'}],evidence:[{id:'NEW-EVIDENCE',claimId:o.id,sourceId:'NEW-SOURCE',locator:'1816 entry',quote:'A sufficiently long exact quotation from the archive.',accessedAt:'2026-10-01',provenance:'Read the archive page',limitations:'One account; incomplete context',reviewer:'Local researcher',reviewStatus:'pending_independent_review',accessScope:'full_text'}],searchLog:[{query:'Local alternative causes',result:'No comparable archive located.'}]}};}
const report=(verdict='supports')=>({factual:true,civil:true,claims:[{id:'NEW-FACT',verdict,reason:'The passage supports the bounded assertion.',limitations:['One account'],alternatives:[],evidenceIds:['NEW-EVIDENCE']}]});
const checks=[{id:'NEW-EVIDENCE',claimId:'NEW-FACT',matched:true}];
test('intake requires exact passages, consent and public source addresses',()=>{const p=research();assert.deepEqual(core.validateCommunity(p,existing,intake),[]);p.consent=false;assert.match(core.validateCommunity(p,existing,intake).join(' '),/Confirm/);p.consent=true;p.draft.evidence[0].quote='';p.draft.sources[0].url='https://127.0.0.1/';assert.equal(core.validateCommunity(p,existing,intake).length,2);});
test('an unavailable quote or reviewer disagreement cannot become supported',()=>{const p=research();assert.equal(core.auditReviews(p,[report(),report()],checks)[0].status,'automated_support');assert.equal(core.auditReviews(p,[report(),report('contradicts')],checks)[0].status,'provisional');assert.equal(core.auditReviews(p,[report(),report()],[{...checks[0],matched:false}])[0].status,'provisional');assert.equal(core.auditReviews(p,[],checks)[0].status,'provisional');});
test('reviewer cannot cite invented evidence or bypass factual/civil requirements',()=>{const a=report();a.claims[0].evidenceIds=['invented'];assert.equal(core.auditReviews(research(),[a,report()],checks)[0].status,'provisional');const b=report();b.civil=false;assert.equal(core.auditReviews(research(),[b,report()],checks)[0].status,'provisional');});
test('graph remaps records without changing baseline facts and preserves uncertainty',()=>{const p=research(),before=JSON.stringify(existing);const result=core.graphPatch(p,'abcdef1234567890',core.auditReviews(p,[report(),report('unclear')],checks),existing);assert.equal(result.observations[0].communityStatus,'provisional');assert.equal(result.observations[0].confidence,'Low');assert.equal(result.evidence[0].claimId,result.observations[0].id);assert.equal(result.extension.nodeIds[0],result.observations[0].id);assert.equal(JSON.stringify(existing),before);});
test('contradicted new facts do not become graph facts',()=>{const p=research(),result=core.graphPatch(p,'abcdef1234567890',core.auditReviews(p,[report('contradicts'),report('contradicts')],checks),existing);assert.equal(result.observations.length,0);assert.equal(result.evidence.length,0);});
test('canonical source identity is reused rather than manufacturing corroboration',()=>{const p=research();p.draft.sources[0].url=existing.sources[0].url;const patch=core.graphPatch(p,'abcdef1234567890',[],existing);assert.equal(patch.sources.length,0);assert.equal(patch.observations[0].sourceRefs[0],existing.sources[0].id);assert.equal(patch.evidence[0].sourceId,existing.sources[0].id);});
test('a new branch must explicitly connect its own facts',()=>{const p=research();p.draft.context.direction='new_thread';p.draft.proposedThread={title:'Local new branch',perspective:'A specific local perspective',nodeIds:['NEW-FACT']};assert.match(core.validateCommunity(p,existing,intake).join(' '),/at least one evidenced relationship/);});
test('dangerous source addresses are rejected, including encoded private hosts',()=>{for(const u of ['http://archive.org/a','https://localhost/a','https://2130706433/a','https://[::1]/a','https://u:p@archive.org/a','https://archive.org:8443/a','https://host.internal/a'])assert.equal(core.publicSourceUrl(u),false,u);assert.equal(core.publicSourceUrl('https://www.loc.gov/item/example'),true);});
test('unrequested contact fields do not cross into public graph records',()=>{const p=research();p.draft.contributor.email='private@example.edu';p.draft.observations[0].privateContact='private@example.edu';const g=core.graphPatch(p,'abcdef1234567890',[],existing);assert.equal(JSON.stringify(g).includes('private@example.edu'),false);});
test('badges require supported findings and never reward provisional uploads',()=>{const p=research(),patch=core.graphPatch(p,'abcdef1234567890',[],existing);assert.deepEqual(core.recognitionFor(p,[{status:'provisional'}],patch),[]);patch.thread={id:'NEW-THREAD'};patch.relationships=[{id:'NEW-EDGE',causalStatus:'CONTRIBUTORY'}];const awards=core.recognitionFor(p,[{status:'automated_support'}],patch);assert.deepEqual(awards.map(a=>a.id),['THREAD_FINDER','CAUSALITY_EXPLORER']);});
test('counterevidence must weaken its target, not merely support unrelated wording',()=>{const p={kind:'evidence',claimId:'NEW-FACT',stance:'counterevidence',relevance:'A source-supported but unrelated statement'};const a=report();a.claims[0].targetEffect='unclear';assert.equal(core.auditReviews(p,[a,a],checks)[0].status,'provisional');a.claims[0].targetEffect='weakens';assert.equal(core.auditReviews(p,[a,a],checks)[0].status,'automated_support');});
