const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const {validateSubmission}=require('../contribution.js');
const read=n=>JSON.parse(fs.readFileSync(path.join(__dirname,'../data/1816',n+'.json'),'utf8'));
const existing={observations:read('observations'),relationships:read('relationships'),sources:read('sources'),threads:read('threads'),gaps:read('research-gaps')};
function draft(){const o=structuredClone(existing.observations[0]);o.id='C-OBS-1';o.sourceRefs=['C-SRC-1'];o.evidenceRefs=['C-EV-1'];o.researchStatus='Contributor draft; independent review pending';return {schemaVersion:1,context:{gapId:existing.gaps[0].id,threadId:existing.threads[0].id,question:'Test a bounded claim'},contributor:{name:'Researcher'},review:{status:'pending'},sources:[{id:'C-SRC-1',title:'Source',authorOrOrg:'Author',type:'Article',url:'https://example.org/source'}],observations:[o],relationships:[],evidence:[{id:'C-EV-1',claimId:o.id,sourceId:'C-SRC-1',locator:'p. 1',accessedAt:'2026-10-01',provenance:'Full article read',limitations:'One source only',reviewer:'Researcher',reviewStatus:'pending_independent_review',accessScope:'full_text'}],searchLog:[{query:'Competing causes',result:'Unresolved; more sources needed'}]};}
test('valid intake leaves accepted data unchanged',()=>{const before=JSON.stringify(existing);assert.deepEqual(validateSubmission(draft(),existing),[]);assert.equal(JSON.stringify(existing),before);});
test('claimed approval is blocked',()=>{const p=draft();p.evidence[0].reviewStatus='approved';assert.match(validateSubmission(p,existing).join(' '),/approval/);});
test('wrong evidence ownership and accepted ID reuse are blocked',()=>{const p=draft();p.evidence[0].claimId='other';p.observations[0].id=existing.observations[0].id;const errors=validateSubmission(p,existing).join(' ');assert.match(errors,/collision/);assert.match(errors,/owned evidence/);});
test('unsearched alternatives and unsafe source URLs are blocked',()=>{const p=draft();p.searchLog=[];p.sources[0].url='javascript:alert(1)';const errors=validateSubmission(p,existing).join(' ');assert.match(errors,/counterevidence/);assert.match(errors,/https/);});
test('a hypothesis needs explicit alternative review',()=>{const p=draft();p.relationships=[{id:'C-REL-1',subjectId:p.observations[0].id,objectId:existing.observations[0].id,predicate:'CONTESTED_CONNECTION',causalStatus:'CONTESTED',explanation:'Unresolved',lag:'unknown',confidence:'Low',sourceRefs:['C-SRC-1'],evidenceRefs:[],researchStatus:'Contributor draft; independent review pending'}];assert.match(validateSubmission(p,existing).join(' '),/alternatives/);});
