import {test} from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import fs from 'node:fs';
import worker,{processSubmission,privateAddress} from '../worker/.test-build/index.js';
const origin='https://stewartdavidp-ship-it.github.io';
function dbAdapter(){const db=new DatabaseSync(':memory:');db.exec(fs.readFileSync(new URL('../worker/schema.sql',import.meta.url),'utf8'));return {raw:db,prepare(sql){const s=db.prepare(sql);let params=[];const q={bind(...values){params=values;return q;},async first(){return s.get(...params)||null;},async all(){return {results:s.all(...params)};},async run(){const r=s.run(...params);return {meta:{changes:r.changes},success:true};}};return q;},async batch(queries){db.exec('BEGIN');try{const results=[];for(const q of queries)results.push(await q.run());db.exec('COMMIT');return results;}catch(e){db.exec('ROLLBACK');throw e;}}};}
function payload(){return {kind:'evidence',claimId:'WT-1816-0001',stance:'supports',alias:'Fixture researcher',sourceTitle:'Fixture archive',sourceUrl:'https://history.example.edu/1816',locator:'Entry for 1816',quote:'The year 1816 brought unusually cold weather to Salem.',relevance:'This passage provides a direct account of unusually cold weather in Salem during 1816.',limitations:'One local account cannot establish a global cause.',consent:true,receipt:'a'.repeat(64)};}
function env(options={}){return {DB:dbAdapter(),APP_ORIGIN:origin,AI_MODEL:'fixture-model',DAILY_REVIEW_LIMIT:'12',DAILY_AI_CALL_LIMIT:'24',AI:{async run(model,input){if(options.throwAI)throw Error('AI unavailable');const data=JSON.parse(input.messages[1].content);return {response:JSON.stringify({factual:true,civil:!options.uncivil,claims:data.claims.map(c=>({id:c.id,targetEffect:data.kind==='evidence'?(data.stance==='counterevidence'?'weakens':'supports'):'unclear',verdict:'supports',reason:'The retrieved passage directly addresses this bounded assertion.',limitations:['One historical witness'],alternatives:[],evidenceIds:data.evidence.filter(e=>e.matched&&e.claimId===c.id).map(e=>e.id)}))})};}}};}
async function request(e,path,method='GET',body,token){const tasks=[];const response=await worker.fetch(new Request('https://service.example.edu'+path,{method,headers:{Origin:origin,'Content-Type':'application/json',...(token?{Authorization:'Bearer '+token}:{})},...(body?{body:JSON.stringify(body)}:{})}),e,{waitUntil(p){tasks.push(p);}});return {response,body:await response.json(),tasks};}
function mockSources(){const real=globalThis.fetch;globalThis.fetch=async value=>{const u=String(value);if(u.includes('dns-query'))return Response.json({Answer:[{type:1,data:'93.184.216.34'}]});if(u.includes('api.crossref.org'))return Response.json({message:{items:[]}});return new Response('A historical source. The year 1816 brought unusually cold weather to Salem. More contextual information follows this local observation.',{headers:{'Content-Type':'text/plain'}});};return ()=>{globalThis.fetch=real;};}
test('source fetch rejects private and local destination ranges',()=>{for(const ip of ['127.0.0.1','10.1.2.3','172.16.1.1','192.168.0.1','169.254.169.254','100.64.0.1','::1','fe80::1','fc00::1'])assert.equal(privateAddress(ip),true,ip);assert.equal(privateAddress('93.184.216.34'),false);});
test('saved research runs review, publishes evidence and exposes only receipt-scoped progress',async()=>{const restore=mockSources(),e=env();try{const r=await request(e,'/api/submissions','POST',payload());assert.equal(r.response.status,202);await Promise.all(r.tasks);const progress=await request(e,'/api/submissions/'+r.body.id,'GET',null,r.body.receipt);assert.equal(progress.body.status,'automated_support');assert.deepEqual(progress.body.events.map(x=>x.phase),['intake','research','source_checks','audit','fix','publication']);const denied=await request(e,'/api/submissions/'+r.body.id,'GET',null,'wrong');assert.equal(denied.response.status,404);const g=await request(e,'/api/graph');assert.equal(g.body.evidenceUpdates.length,1);assert.equal(g.body.evidenceUpdates[0].assessment,'automated_support');assert.equal(JSON.stringify(g.body).includes('receipt'),false);assert.equal(JSON.stringify(g.body).includes('sourceHash'),true);}finally{restore();e.DB.raw.close();}});
test('duplicate retry recovers the original receipt and does not re-run review',async()=>{const restore=mockSources(),e=env();try{const first=await request(e,'/api/submissions','POST',payload());await Promise.all(first.tasks);const again=await request(e,'/api/submissions','POST',payload());assert.equal(again.response.status,200);assert.equal(again.body.id,first.body.id);assert.equal(again.tasks.length,0);const p=payload();p.receipt='b'.repeat(64);const other=await request(e,'/api/submissions','POST',p);assert.equal(other.response.status,409);}finally{restore();e.DB.raw.close();}});
test('uncivil material stays private with correction instructions',async()=>{const restore=mockSources(),e=env({uncivil:true});try{const r=await request(e,'/api/submissions','POST',payload());await Promise.all(r.tasks);const progress=await request(e,'/api/submissions/'+r.body.id,'GET',null,r.body.receipt);assert.equal(progress.body.status,'needs_correction');const g=await request(e,'/api/graph');assert.equal(g.body.evidenceUpdates.length,0);assert.equal((await request(e,'/api/activity')).body.length,0);}finally{restore();e.DB.raw.close();}});
test('review service failures remain private and stop after bounded automatic retries',async()=>{const restore=mockSources(),e=env({throwAI:true});try{const r=await request(e,'/api/submissions','POST',payload());await Promise.all(r.tasks);await processSubmission(e,r.body.id);await processSubmission(e,r.body.id);await processSubmission(e,r.body.id);const row=e.DB.raw.prepare('SELECT attempts,status FROM submission').get();assert.equal(row.attempts,3);assert.equal(row.status,'review_unavailable');assert.equal((await request(e,'/api/graph')).body.evidenceUpdates.length,0);}finally{restore();e.DB.raw.close();}});
test('cross-origin and structurally invalid submissions are blocked',async()=>{const e=env();try{const r=await worker.fetch(new Request('https://service.example.edu/api/submissions',{method:'POST',headers:{Origin:'https://attacker.example.edu','Content-Type':'application/json'},body:JSON.stringify(payload())}),e,{});assert.equal(r.status,403);const p=payload();p.quote='short';const invalid=await request(e,'/api/submissions','POST',p);assert.equal(invalid.response.status,422);assert.equal(e.DB.raw.prepare('SELECT count(*) n FROM submission').get().n,0);}finally{e.DB.raw.close();}});
function researchPayload(){const data=JSON.parse(fs.readFileSync(new URL('../data/1816/observations.json',import.meta.url),'utf8'))[0];const o={...data,id:'NEW-LOCAL-FACT',title:'Fixture local weather observation',sourceRefs:['NEW-SOURCE'],evidenceRefs:['NEW-OBS-EV'],researchStatus:'Contributor draft; independent review pending'};const r={id:'NEW-LINK',subjectId:'WT-1816-0001',objectId:o.id,predicate:'ASSOCIATED_WITH',causalStatus:'ASSOCIATED',explanation:'These two bounded observations share local weather context; no causal conclusion is asserted.',lag:'Same year',confidence:'Low',sourceRefs:['NEW-SOURCE'],evidenceRefs:['NEW-REL-EV'],researchStatus:'Contributor draft; independent review pending'};const ev=(id,claimId)=>({id,claimId,sourceId:'NEW-SOURCE',locator:'1816 entry',quote:payload().quote,accessedAt:'2026-10-01',provenance:'Fixture source text',limitations:'One account only',reviewer:'Fixture researcher',reviewStatus:'pending_independent_review',accessScope:'full_text'});return {kind:'research',consent:true,receipt:'c'.repeat(64),draft:{schemaVersion:1,context:{threadId:'THR-001',question:'A local weather branch',year:1816,place:'Salem',direction:'new_thread'},contributor:{name:'Fixture researcher'},review:{status:'pending'},sources:[{id:'NEW-SOURCE',url:payload().sourceUrl,title:'Fixture historical entry',type:'Archive',authorOrOrg:'Fixture archive'}],observations:[o],relationships:[r],evidence:[ev('NEW-OBS-EV',o.id),ev('NEW-REL-EV',r.id)],searchLog:[{query:'Other local influences',result:'No further material found in the fixture.'}],proposedThread:{title:'Local branch fixture',perspective:'A bounded local association',nodeIds:['WT-1816-0001',o.id]}}};}
test('research adds a connected branch with remapped facts, evidence and relationship IDs',async()=>{const restore=mockSources(),e=env();try{const p=researchPayload();const baseThreads=JSON.parse(fs.readFileSync(new URL('../data/1816/threads.json',import.meta.url),'utf8'));p.draft.context.threadId=baseThreads[0].id;const r=await request(e,'/api/submissions','POST',p);assert.equal(r.response.status,202,JSON.stringify(r.body));await Promise.all(r.tasks);const g=await request(e,'/api/graph');assert.equal(g.body.patches.length,1);const patch=g.body.patches[0];assert.equal(patch.observations.length,1);assert.equal(patch.relationships.length,1);assert.equal(patch.thread.nodeIds[0],'WT-1816-0001');assert.equal(patch.relationships[0].objectId,patch.observations[0].id);assert.equal(patch.thread.relationshipIds[0],patch.relationships[0].id);assert.equal(patch.observations[0].confidence,'Medium');assert.equal(patch.evidence[0].claimId,patch.observations[0].id);}finally{restore();e.DB.raw.close();}});
test('daily reviewer budget leaves a saved draft queued rather than dropping it',async()=>{const e=env();e.DAILY_REVIEW_LIMIT='0';try{const r=await request(e,'/api/submissions','POST',payload());await Promise.all(r.tasks);const row=e.DB.raw.prepare('SELECT status,attempts FROM submission').get();assert.equal(row.status,'queued');assert.equal(row.attempts,0);}finally{e.DB.raw.close();}});
test('public review history contains only published events, never private receipts or raw drafts',async()=>{const restore=mockSources(),e=env();try{const r=await request(e,'/api/submissions','POST',payload());await Promise.all(r.tasks);const h=await request(e,'/api/reviews/'+r.body.id);assert.equal(h.response.status,200);assert.equal(h.body.events[0].phase,'research');assert.equal(JSON.stringify(h.body).includes(r.body.receipt),false);assert.equal(JSON.stringify(h.body).includes('receipt_hash'),false);assert.equal(h.body.events.some(x=>x.phase==='intake'),false);}finally{restore();e.DB.raw.close();}});
